---
title: "Study3SSQ"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
  library(tidyverse)
  library(readr)
  library(janitor)
  library(emmeans)
  library(car)
  library(tidyr)
  library(stringr)
  library(lme4)
  library(lmerTest)
  library(dplyr)
  library(report)

```


```{r, include=FALSE}
#Set the working directory of the data ***HARD CODED ***
 #setwd("D:/Study2Data/qualtrics_data/SSQ")
SSQdataRaw = read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 4/data/Qualtrics/SSQ/Study4SSQ.csv") %>%  
    select(starts_with('Q')) 
  
  #Format the column names by removing excess characters
SSQdataFilter <- SSQdataRaw
SSQdataFilter[1,] <- sub(".*- ", "", SSQdataFilter[1,])
    
#change the row names to the column headers
SSQdataOrg <- row_to_names(SSQdataFilter, row_number = 1)

SSQdataOrg <- SSQdataOrg %>% 
  rename(participant = `eg TH03ON)`) %>% 
   rename(Timepoint = `Which timepoint is this?`)


```

```{r}

SSQdataOrg <- SSQdataOrg %>% 
  subset(participant != "P01") %>%
  subset(participant != "P02") %>%
  subset(participant != "P03") %>% 
  subset(participant != "P04") %>%
  subset(participant != "P05") %>%
  subset(participant != "P06") %>%
  subset(participant != "P13") %>%
  subset(participant != "P21") 

```


```{r}
Counterbalancing <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 4/Study4Counterbalancing.csv", header = T)

Counterbalancing <- Counterbalancing%>%  select(PID, First, Second, Third, Fourth)

Counterbalancing <- na.omit(Counterbalancing)

Counterbalancing$participant <- Counterbalancing$PID
  


```

```{r,include=FALSE}

#Recode Values so they are computable

SSQdata <- SSQdataOrg

SSQdata[SSQdata== '0 - None at all'] <- '0'
SSQdata[SSQdata== '1 - Mild'] <- '1'
SSQdata[SSQdata== '2 - Moderate'] <- '2'
SSQdata[SSQdata== '3 - Severe'] <- '3'

SSQdata[SSQdata== 'Start of Experiment'] <- 'Baseline'
SSQdata[SSQdata== 'End of Block 1'] <- '1'
SSQdata[SSQdata== 'End of Block 2'] <- '2'
SSQdata[SSQdata== 'End of Block 3'] <- '3'
SSQdata[SSQdata== 'End of Experiment'] <- '4'




#Convert columns with ratings in to numeric
SSQdata[3:18] = lapply(SSQdata[3:18], FUN = function(y){as.numeric(y)})

SSQdata <- SSQdata[!is.na(SSQdata$Fatigue),]


```


```{r}
SSQdata <- left_join(SSQdata, Counterbalancing, by = 'participant') 
SSQdata$Block <- '' 


SSQdata$Block <-if_else(SSQdata$Timepoint == "4", SSQdata$Fourth,
                                  if_else(SSQdata$Timepoint == "3", SSQdata$Third,
                                          if_else(SSQdata$Timepoint == "2", SSQdata$Second,
                                                  if_else(SSQdata$Timepoint == "1", SSQdata$First, 
                                                          if_else(SSQdata$Timepoint == "Baseline",'Baseline', 'Baseline')))))


SSQdata$Timepoint <- factor(SSQdata$Timepoint, levels = c('Baseline','1','2','3','4'))



```


```{r}
#Calculate the SSQ score weightings according to Kennedy et al 1993
SSQConversion <- SSQdata 

SSQConversion$NauseaSum <- colSums(SSQConversion[, c("General Discomfort","Increased Salivation", "Sweating", "Nausea", "Difficulty Concentrating","Stomach Awareness", "Burping")])

SSQConversion$OculomotorSum <- colSums(SSQConversion[, c("General Discomfort", "Fatigue","Headache", "Eye Strain", "Difficulty Focusing","Difficulty Concentrating", "Blurred Vision")])

SSQConversion$DisorientationSum <- colSums(SSQConversion[, c("Difficulty Focusing","Nausea", "Fullness of Head", "Blurred Vision","Dizzy (Eye Open)","Dizzy ( Eyes Closed)", "Vertigo")])

SSQConversion$DisorientationSum <- colSums(SSQConversion[, c(7,10, 12, 13,14,15, 16)])


#Calculate the final weighted SSQ scores

  SSQConversion <- SSQConversion %>% 
      mutate(NauseaWeight = (SSQConversion$NauseaSum * 9.54)) %>% 
      mutate(OculomotorWeight = (SSQConversion$OculomotorSum*7.58)) %>% 
      mutate(DisorientationWeight = (SSQConversion$DisorientationSum *13.92)) %>% 
      mutate(TotalSSQScore = 
               (SSQConversion$NauseaSum +
               SSQConversion$OculomotorSum +
               SSQConversion$DisorientationSum)*
               3.74)
  
 # write.csv(SSQConversion,"D:/Qualtrics_Data/Study1/SSQ/EXP1SSQSort.csv", row.names = FALSE)
  
  # SSQConversion <- SSQConversion %>% 
  #   
  #     subset(Block != "Tablet")

  
```

```{r}
#Calculate the SSQ score weightings according to Kennedy et al 1993
SSQConversion <- SSQdata 

SSQConversion <- SSQConversion %>% 
  mutate(NauseaSum = 
           (SSQConversion$`General Discomfort` + 
            SSQConversion$`Increased Salivation` + 
            SSQConversion$Sweating + 
            SSQConversion$Nausea + 
            SSQConversion$`Difficulty Concentrating`+
            SSQConversion$`Stomach Awareness` +
            SSQConversion$Burping)) %>% 
  mutate(OculomotorSum = 
           (SSQConversion$`General Discomfort` +
            SSQConversion$Fatigue +
            SSQConversion$Headache +
            SSQConversion$`Eye Strain` +
            SSQConversion$`Difficulty Focusing` +
            SSQConversion$`Difficulty Concentrating`+
            SSQConversion$`Blurred Vision`)) %>% 
  mutate(DisorientationSum =
           (SSQConversion$`Difficulty Focusing` +
            SSQConversion$Nausea +
            SSQConversion$`Fullness of Head` +
            SSQConversion$`Blurred Vision` +
            SSQConversion$`Dizzy (Eye Open)` +
            SSQConversion$`Dizzy ( Eyes Closed)`+
            SSQConversion$Vertigo)) 

#Calculate the final weighted SSQ scores

  SSQConversion <- SSQConversion %>% 
      mutate(NauseaWeight = (SSQConversion$NauseaSum * 9.54)) %>% 
      mutate(OculomotorWeight = (SSQConversion$OculomotorSum*7.58)) %>% 
      mutate(DisorientationWeight = (SSQConversion$DisorientationSum *13.92)) %>% 
      mutate(TotalSSQScore = 
               (SSQConversion$NauseaSum +
               SSQConversion$OculomotorSum +
               SSQConversion$DisorientationSum)*
               3.74)
  
 # write.csv(SSQConversion,"D:/Qualtrics_Data/Study1/SSQ/EXP1SSQSort.csv", row.names = FALSE)
  
  # SSQConversion <- SSQConversion %>% 
  #   
```



```{r}
#Summarise the descriptives for the converted scores
SSQConversionSummary <- SSQConversion %>% 
  
  group_by(Timepoint) %>%  # can add Block here to split by condition
  summarise(
  n = n(),
  mean = mean(TotalSSQScore),
  sd = sd(TotalSSQScore),
  min = min(TotalSSQScore),
  max = max(TotalSSQScore)) 

SSQConversionBlockSummary <- SSQConversion %>% 
  
  group_by(Timepoint, Block) %>%  # can add Block here to split by condition
  summarise(
  n = n(),
  mean = mean(TotalSSQScore),
  sd = sd(TotalSSQScore),
  min = min(TotalSSQScore),
  max = max(TotalSSQScore)) 
#Summarise the descriptives for the converted  Nausea scores
SSQNauseaSummary <- SSQConversion %>% 
  
  group_by(Timepoint, Block) %>% 
  summarise(
  n = n(),
  mean = mean(NauseaWeight),
  sd = sd(NauseaWeight),
  min = min(NauseaWeight),
  max = max(NauseaWeight))   
#Summarise the descriptives for the converted Oculomotor scores
SSQOculoSummary <- SSQConversion %>% 
  
  group_by(Timepoint, Block) %>% 
  summarise(
  n = n(),
  mean = mean(OculomotorWeight),
  sd = sd(OculomotorWeight),
  min = min(OculomotorWeight),
  max = max(OculomotorWeight))  
#Summarise the descriptives for the converted Disorientation scores
SSQDisoriSummary <- SSQConversion %>% 
  
  group_by(Timepoint, Block) %>% 
  summarise(
  n = n(),
  mean = mean(DisorientationWeight),
  sd = sd(DisorientationWeight),
  min = min(DisorientationWeight),
  max = max(DisorientationWeight)) 
```


```{r}
  ########################END OF DATA WRANGLING########################
  #####################################################################
```

        
```{r}
#Visualise the spread of the data
ggplot(SSQConversion, aes(x = TotalSSQScore, fill = Timepoint))+
  geom_histogram(binwidth = 3)

```
           
```{r}
#Create violin plots for each of the Weighted totals to show the spread of the data
ggplot(SSQConversion, aes(Timepoint, TotalSSQScore, fill = Timepoint ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Total SSQ Score")

ggplot(SSQConversion, aes(Timepoint, OculomotorWeight, fill = Block ))+
  geom_violin(alpha = 0.5) +
  labs(title = "Oculomotor Score")
ggplot(SSQConversion, aes(Timepoint, NauseaWeight, fill = Block ))+
  geom_violin(alpha = 0.5) +
  labs(title = "Nausea score")
ggplot(SSQConversion, aes(Timepoint, DisorientationWeight, fill = Block ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Disorientation Score")
```
```{r}
S4TotalSSQ <- ggplot(SSQConversionSummary,  aes(x = Timepoint, y = mean, colour = Timepoint, group = Timepoint, shape = Timepoint))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_point (size = 3.5, position = position_dodge(width = 0.5)) +
  scale_shape_manual(values=c(0,15,1,16,2,17,18,19,20,21,22,23,24))+
  scale_color_brewer(palette="Dark2")+
  geom_line(position = position_dodge(width = 0.5))+
  labs(x = "Block",
      y = "Total SSQ Score",
      title = "Total SSQ Score",
      tag = "")+  

    scale_fill_hue(l = 2)+
   
    geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, position = position_dodge(width = 0.5))+



  theme_classic()

S4TotalSSQ

ggsave(filename = "S4TotalSSQ.png", S4TotalSSQ)


```


```{r}
ggplot(SSQConversionBlockSummary,  aes(x = Timepoint, y = mean, colour = Block, group = Block, shape = Block))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_point (size = 3.5, position = position_dodge(width = 0.5)) +
  scale_shape_manual(values=c(0,15,1,16,2,17,18,19,20,21,22,23,24))+
  scale_color_brewer(palette="Dark2")+
  geom_line(position = position_dodge(width = 0.5))+
  labs(x = "Block",
      y = "Total SSQ Score",
      title = "Total SSQ Score",
      tag = "")+  
    scale_fill_hue(l = 2)+
   
    geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, position = position_dodge(width = 0.5))+



  theme_bw()
```




```{r}
#Create interaction plots for the mean of each condition at each of the 3 timepoints
#**pch = type of shape on the point graph
interaction.plot(x.factor =  SSQConversion$Timepoint,
                 trace.factor = SSQConversion$Block,
                 response = SSQConversion$TotalSSQScore,
                 fun = mean,
                 xlab = "Timepoint",
                 ylab = "Total SSQ Score",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Total SSQ Score",
                 fixed=T,
                 leg.bty ="o")
interaction.plot(x.factor =  SSQConversion$Timepoint,
                 trace.factor = SSQConversion$Timepoint,
                 response = SSQConversion$NauseaWeight,
                 fun = mean,
                 xlab = "Timepoint",
                 ylab = "Nausea subscale",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Nausea",
                 fixed=T,
                 leg.bty ="o")
interaction.plot(x.factor =  SSQConversion$Timepoint,
                 trace.factor = SSQConversion$Timepoint,
                 response = SSQConversion$OculomotorWeight,
                 fun = mean,
                 xlab = "Timepoint",
                 ylab = "Oculomotor subscale",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Oculomotor",
                 fixed=T,
                 leg.bty ="o")
interaction.plot(x.factor =  SSQConversion$Timepoint,
                 trace.factor = SSQConversion$Timepoint,
                 response = SSQConversion$DisorientationWeight,
                 fun = mean,
                 xlab = "Timepoint",
                 ylab = "Disorientation subscale",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Disorientation",
                 fixed=T,
                 leg.bty ="o")
```

```{r}
# Generate linear modals for each of the weighted scores
SSQModel = lm(TotalSSQScore ~ Timepoint*Block,data = SSQConversion)


test = aov(TotalSSQScore ~ Timepoint,data = SSQConversion)

summary(test)

Anova(SSQModel,
      type = "II")

```
```{r}
#Calculate comparison means for Overall scores
#SSQmarginal = emmeans(SSQModel,~Timepoint)
#pairs(SSQmarginal, adjust="tukey")

```
 
```{r}
# Generate linear modals for Oculomotor subscale
# 
# OcuModel = lm(OculomotorWeight ~ Timepoint, data = SSQConversion)
# 
# Anova(OcuModel,
#       type = "II")

```

```{r}
#Calculate comparison means for Oculomotor subscale
# 
# Ocumarginal = emmeans(OcuModel, ~Timepoint)
# pairs(Ocumarginal, adjust="tukey")

```
 
```{r}
# # Generate linear modals for Nausea subscale
# NauModel = lm(NauseaWeight ~ Timepoint,data = SSQConversion)
# 
# Anova(NauModel,
#       type = "II")
```

```{r}
#Calculate comparison means for Nausea subscale
# 
# Naumarginal = emmeans(NauModel, ~Timepoint)
# pairs(Naumarginal, adjust="tukey")
# 
# #Significatn effect of conidtion, but is meaningless in the comparisons

```
 
```{r}
# #Generate linear modals for Disorientation  subscale
# DisModel = lm(DisorientationWeight ~ Timepoint,data = SSQConversion)
# 
# Anova(DisModel,
#       type = "II")
```

```{r}
#Calculate comparison means for Disorientation subscale 
# 
# Dismarginal = emmeans(DisModel, ~Timepoint)
# pairs(Dismarginal, adjust="tukey")

```

```{r}
TotalSSQNullmodel <- lmer(data = SSQConversion, TotalSSQScore ~ 1+ (1|participant), REML = F)

TotalSSQmodel1 <- lmer(data = SSQConversion, TotalSSQScore ~Timepoint + (1|participant), REML = F)

TotalSSQmodel2 <- lmer(data = SSQConversion, TotalSSQScore ~Timepoint + Block + (1|participant), REML = F)

TotalSSQmodelTPRBlock <- lmer(data = SSQConversion, TotalSSQScore ~Timepoint  + (1|participant) + (1|Block), REML = F)

summary(TotalSSQmodelTPRBlock)
TotalSSQmodel3 <- lmer(data = SSQConversion, TotalSSQScore ~Timepoint * Block + (1|participant), REML = F)

TotalSSQmodel4 <- lmer(data = SSQConversion, TotalSSQScore ~Timepoint  + (1|participant) + (1|Block), REML = F)

TotalSSQmodel5 <- lmer(data = SSQConversion, TotalSSQScore ~ Block  + (1|participant) , REML = F)

anova(TotalSSQNullmodel, TotalSSQmodel1, TotalSSQmodel2, TotalSSQmodel3, TotalSSQmodel4,TotalSSQmodel5)

anova(TotalSSQmodelTPRBlock, TotalSSQmodel2)

```


```{r}



anova(TotalSSQmodel1, TotalSSQmodel2, TotalSSQmodel3,TotalSSQmodel5)
summary(TotalSSQmodel1)
#summary(TotalSSQmodel2)

#summary(TotalSSQmodel5)
```


```{r}
SSQConversion$Timepoint <- relevel(SSQConversion$Timepoint, ref = "3")
TotalSSQmodel1 <- lmer(data = SSQConversion, TotalSSQScore ~Timepoint + (1|participant), REML = F)
summary(TotalSSQmodel1)

anova(TotalSSQmodel1, TotalSSQNullmodel)
library(report)
TotalSSQresults <- report(TotalSSQmodel1, CI = 95)

#summary(results)
print(TotalSSQresults)
```
```{r}
OculoNullmodel <- lmer(data = SSQConversion, OculomotorWeight ~ (1|participant), REML = F)

Oculomodel0 <- lmer(data = SSQConversion, OculomotorWeight ~ Timepoint + (1|participant), REML = F)


Oculomodel1 <- lmer(data = SSQConversion, OculomotorWeight ~ Timepoint + Block + (1|participant), REML = F)

anova(OculoNullmodel, Oculomodel0, Oculomodel1)

summary(Oculomodel0)
```

```{r}

NauseaNullmodel <- lmer(data = SSQConversion, NauseaWeight ~ (1|participant), REML = F)

Nauseamodel0 <- lmer(data = SSQConversion, NauseaWeight ~ Timepoint + (1|participant), REML = F)


Nauseamodel1 <- lmer(data = SSQConversion, NauseaWeight ~ Timepoint + Block + (1|participant), REML = F)

anova(NauseaNullmodel, Nauseamodel0, Nauseamodel1)

summary(Nauseamodel1)
```
```{r}

DisorientNullmodel <- lmer(data = SSQConversion, DisorientationWeight ~ (1|participant), REML = F)

Disorientmodel0 <- lmer(data = SSQConversion, DisorientationWeight ~ Timepoint + (1|participant), REML = F)


Disorientmodel1 <- lmer(data = SSQConversion, DisorientationWeight ~ Timepoint + Block + (1|participant), REML = F)

Disorientmodel2 <- lmer(data = SSQConversion, DisorientationWeight ~  Block + (1|participant), REML = F)

anova(DisorientNullmodel, Disorientmodel0, Disorientmodel1,Disorientmodel2)

summary(Disorientmodel0)

```
```{r}
SSQConversion$Timepoint <- relevel(SSQConversion$Timepoint, ref = "Baseline")
Disorientmodel0 <- lmer(data = SSQConversion, DisorientationWeight ~ Timepoint + (1|participant), REML = F)

library(report)
DisoriTotalSSQresults <- report(Disorientmodel0, CI = 95)

#summary(results)
print(DisoriTotalSSQresults)
```


```{r}
##################  CONVERT DATA TO LOOK AT DIFFERENCES OVER TIME ###########
#############################################################################
```

```{r}
#Convert the dataset to look out differences over time
# 
 SSQKPConversion <- SSQConversion

```


```{r}

SSQKPConversion$participant <- as.factor(SSQKPConversion$participant)
SSQKPConversion$Block <- as.factor(SSQKPConversion$Block)

# SSQKPConversion$Timepoint[SSQKPConversion$Timepoint== '1'] <- 'Baseline'
# SSQKPConversion$Timepoint[SSQKPConversion$Timepoint== '2'] <- 'T1'
# SSQKPConversion$Timepoint[SSQKPConversion$Timepoint== '3'] <- 'T2'
# SSQKPConversion$Timepoint[SSQKPConversion$Timepoint== '4'] <- 'T3'
# SSQKPConversion$Timepoint[SSQKPConversion$Timepoint== '5'] <- 'T4'
# SSQKPConversion$Timepoint[SSQKPConversion$Timepoint== '6'] <- 'T5'


#SSQKPConversion$Timepoint <- as.factor(SSQKPConversion$Timepoint)


```

```{r}
## Reformat data and wrtie csv file to to be read in JASP  


SSQKPConversionTotalSSQ <- SSQKPConversion %>% 
  select(-(5:7)) %>% 
  mutate(TotalSSQChange = TotalSSQScore)

SSQKPConversionTotalSSQ$Timepoint <- factor(SSQKPConversionTotalSSQ$Timepoint, levels = c("Baseline", "1","2", "3", "4", "5"))
SSQKPConversionTotalSSQ$TotalSSQChange <- 0
SSQKPConversionTotalSSQ$OculoChange <- 0
SSQKPConversionTotalSSQ$NauseaChange <- 0
SSQKPConversionTotalSSQ$DisoriChange <- 0

TotalSSQChange <- diff(SSQKPConversionTotalSSQ$TotalSSQScore) 
TotalSSQChange <- append(0, TotalSSQChange)


DisoriChange <- diff(SSQKPConversionTotalSSQ$DisorientationWeight) 
DisoriChange <- append(0, DisoriChange)

NauseaChange <- diff(SSQKPConversionTotalSSQ$NauseaWeight) 
NauseaChange <- append(0, NauseaChange)

OculoChange <- diff(SSQKPConversionTotalSSQ$OculomotorWeight) 
OculoChange <- append(0, OculoChange)
 
SSQKPConversionTotalSSQ$TotalSSQChange <- TotalSSQChange
SSQKPConversionTotalSSQ$DisoriChange <- DisoriChange
SSQKPConversionTotalSSQ$NauseaChange <- NauseaChange
SSQKPConversionTotalSSQ$OculoChange <- OculoChange


SSQKPConversionTotalSSQ$TotalSSQScoreChange <- if_else(SSQKPConversionTotalSSQ$Timepoint == "Baseline", 0, SSQKPConversionTotalSSQ$TotalSSQChange)

SSQKPConversionTotalSSQ$DisoriScoreChange <- if_else(SSQKPConversionTotalSSQ$Timepoint == "Baseline", 0, SSQKPConversionTotalSSQ$DisoriChange)

SSQKPConversionTotalSSQ$NauseaScoreChange <- if_else(SSQKPConversionTotalSSQ$Timepoint == "Baseline", 0, SSQKPConversionTotalSSQ$NauseaChange)

SSQKPConversionTotalSSQ$OculoScoreChange <- if_else(SSQKPConversionTotalSSQ$Timepoint == "Baseline", 0, SSQKPConversionTotalSSQ$OculoChange)



```


```{r}
##Create summary tables for the Total SSQ 
#'
SSQKPConversionTotalSSQSummary <- SSQKPConversionTotalSSQ %>% 
  
  group_by(Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(TotalSSQScoreChange, na.rm = T),
  sd = sd(TotalSSQScoreChange, na.rm = T)
  )   

SSQKPConversionTotalSSQBlockSummary <- SSQKPConversionTotalSSQ %>% 
  
  group_by(Timepoint, Block) %>% 
  summarise(
  n = n(),
  mean = mean(TotalSSQScoreChange, na.rm = T),
  sd = sd(TotalSSQScoreChange, na.rm = T)
  )   

```

```{r}
ggplot(SSQKPConversionTotalSSQ, aes(Timepoint, TotalSSQScoreChange, colour = Block, group = Block ))+
  geom_boxplot()+
  labs(title = "Total SSQ Score")

# interaction.plot(x.factor =  SSQKPConversionTotalSSQSummary$Timepoint,
#                  trace.factor = SSQKPConversionTotalSSQSummary$Block,
#                  response = SSQKPConversionTotalSSQSummary$mean,
#                  fun = mean,
#                  ylim = c(-10, 20),
#                  xlab = "Timepoint",
#                  ylab = "Total SSQ Score",
#                  type= "b",
#                  col=c("red","blue"),
#                  pch=c(19,17,15),
#                  trace.label = "Total SSQ Score",
#                  fixed=F,
#                  leg.bty ="o")
```



```{r}
ggplot(SSQKPConversionTotalSSQSummary,  aes(x = Timepoint, y = mean, colour = Timepoint, group = 1))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_point (size = 3.5, shape = 20) +
  labs(x = "Block",
      y = "Total Change in SSQ Score",
      title = "Total Change in SSQ Score",
      tag = "")+  
  ylim(-5,10) +
    geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, 
                position = position_dodge(0.9))+
  geom_hline(yintercept = 0, linetype = "dashed", alpha = 0.3)+

  theme_bw()
```

```{r}
ggplot(SSQKPConversionTotalSSQSummary,  aes(x = Timepoint, y = mean, colour = Timepoint, group = Timepoint, shape = Timepoint))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_point (size = 3.5, position = position_dodge(width = 0.5)) +
  scale_shape_manual(values=c(0,15,1,16,2,17,18,19,20,21,22,23,24))+
  scale_color_brewer(palette="Dark2")+
  geom_line(position = position_dodge(width = 0.5))+
  labs(x = "Block",
      y = "Total SSQ Score",
      title = "Total SSQ Score",
      tag = "")+ 
    scale_fill_hue(l = 2)+
   
    geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, position = position_dodge(width = 0.5))+
  geom_hline(yintercept = 0, linetype = 'dotted')+



  theme_classic()
```



```{r}
ggplot(SSQKPConversionTotalSSQBlockSummary,  aes(x = Timepoint, y = mean, colour = Block, group = Block, shape = Block))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_point (size = 3.5, position = position_dodge(width = 0.5)) +
  scale_shape_manual(values=c(0,15,1,16,2,17,18,19,20,21,22,23,24))+
  scale_color_brewer(palette="Dark2")+
  geom_line(position = position_dodge(width = 0.5))+
  labs(x = "Block",
      y = "Total Change in  SSQ Score",
      title = "Total Change in SSQ Score",
      tag = "")+  
    scale_fill_hue(l = 2)+
   
    geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, position = position_dodge(width = 0.5))+
  geom_hline(yintercept = 0, linetype = 'dotted')+



  theme_bw()
```


```{r}
KPSSQModelTotalSSQ = aov(TotalSSQScoreChange ~ Timepoint,
              data = SSQKPConversionTotalSSQ)

Anova(KPSSQModelTotalSSQ,
      type = "II")
```

```{r}
KPSSQModelTotalSSQ = emmeans(KPSSQModelTotalSSQ, ~Timepoint)
pairs(KPSSQModelTotalSSQ, adjust="tukey")

```


```{r}
TotalKPSSQNullmodel <- lmer(data = SSQKPConversionTotalSSQ, TotalSSQScoreChange ~ (1|participant), REML = F)

TotalKPSSQmodel1 <- lmer(data = SSQKPConversionTotalSSQ, TotalSSQScoreChange ~ Timepoint + (1|participant),REML = F)

TotalKPSSQmodel2 <- lmer(data = SSQKPConversionTotalSSQ, TotalSSQScoreChange ~Timepoint + Block + (1|participant),REML = F)

TotalKPSSQmodel3 <- lmer(data = SSQKPConversionTotalSSQ, TotalSSQScoreChange ~ Block + (1|participant),REML = F)

anova(TotalKPSSQNullmodel, TotalKPSSQmodel1, TotalKPSSQmodel2, TotalKPSSQmodel3)

summary(TotalKPSSQmodel3)

```
```{r}
library(report)
TotalSSQresults <- report(TotalKPSSQmodel2, CI = 95)

summary(TotalSSQresults)


```



```{r}
#############################################################################
```

```{r}

SSQKPConversionOculoSummary <- SSQKPConversionTotalSSQ %>% 
  
  group_by(Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(OculoScoreChange, na.rm = T),
  sd = sd(OculoScoreChange, na.rm = T)
  )   

SSQKPConversionOculoBlockSummary <- SSQKPConversionTotalSSQ %>% 
  
  group_by(Timepoint, Block) %>% 
  summarise(
  n = n(),
  mean = mean(OculoScoreChange, na.rm = T),
  sd = sd(OculoScoreChange, na.rm = T)
  )   

```

```{r}
interaction.plot(x.factor =  SSQKPConversionOculoSummary$Timepoint,
                 trace.factor = SSQKPConversionOculoSummary$mean,
                 response = SSQKPConversionOculoSummary$mean,
                 fun = mean,
                 xlab = "Timepoint",
                 ylab = "Change in Oculomotor subscore",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Oculomotor",
                 fixed=F,
                 leg.bty ="o")

ggplot(SSQKPConversionOculoBlockSummary,  aes(x = Timepoint, y = mean, colour = Block, group = Block, shape = Block))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_point (size = 3.5, position = position_dodge(width = 0.5)) +
  scale_shape_manual(values=c(0,15,1,16,2,17,18,19,20,21,22,23,24))+
  scale_color_brewer(palette="Dark2")+
  geom_line(position = position_dodge(width = 0.5))+
  labs(x = "Block",
      y = "Oculomotor",
      title = "Oculomotor subscale",
      tag = "")+  
    scale_fill_hue(l = 2)+
   
    geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, position = position_dodge(width = 0.5))+
  geom_hline(yintercept = 0, linetype = 'dotted')+



  theme_bw()

```

```{r}
KPSSQModelOculo = lm(OculoScoreChange ~ Timepoint,data = SSQKPConversionTotalSSQ)

Anova(KPSSQModelOculo,
      type = "II")

```


```{r}
OculoNullmodel <- lmer(data = SSQKPConversionTotalSSQ, OculoScoreChange ~ (1|participant), REML = F)

Oculomodel0 <- lmer(data = SSQKPConversionTotalSSQ, OculoScoreChange ~ Timepoint + (1|participant), REML = F)


Oculomodel1 <- lmer(data = SSQKPConversionTotalSSQ, OculoScoreChange ~ Timepoint + Block + (1|participant), REML = F)

anova(OculoNullmodel, Oculomodel0, Oculomodel1)

summary(Oculomodel1)
```
```{r}
# Oculoresults <- report(Oculomodel1, CI = 95)
# 
# #summary(results)
# summary(Oculoresults)
```

```{r}
#############################################################################
```


```{r}

SSQKPConversionNauseaSummary <- SSQKPConversionTotalSSQ %>% 
  
  group_by(Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(NauseaScoreChange, na.rm = T),
  sd = sd(NauseaScoreChange, na.rm = T)
  )   

SSQKPConversionNauseaBlockSummary <- SSQKPConversionTotalSSQ %>% 
  
  group_by(Timepoint, Block) %>% 
  summarise(
  n = n(),
  mean = mean(NauseaScoreChange, na.rm = T),
  sd = sd(NauseaScoreChange, na.rm = T)
  )   

```

```{r}

interaction.plot(x.factor =  SSQKPConversionNauseaSummary$Timepoint,
                 trace.factor = SSQKPConversionNauseaSummary$Timepoint,
                 response = SSQKPConversionNauseaSummary$mean,
                 fun = mean,
                 xlab = "Timepoint",
                 ylab = "Score",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Nausea",
                 fixed=F,
                 leg.bty ="o")


ggplot(SSQKPConversionNauseaBlockSummary,  aes(x = Timepoint, y = mean, colour = Block, group = Block, shape = Block))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_point (size = 3.5, position = position_dodge(width = 0.5)) +
  scale_shape_manual(values=c(0,15,1,16,2,17,18,19,20,21,22,23,24))+
  scale_color_brewer(palette="Dark2")+
  geom_line(position = position_dodge(width = 0.5))+
  labs(x = "Block",
      y = "Nausea",
      title = "Nausea subscale",
      tag = "")+  
    scale_fill_hue(l = 2)+
   
    geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, position = position_dodge(width = 0.5))+
  geom_hline(yintercept = 0, linetype = 'dotted')+



  theme_bw()


```

```{r}

KPSSQModelNausea = lm(NauseaScoreChange ~ Timepoint,
              data = SSQKPConversionTotalSSQ)

Anova(KPSSQModelNausea,
      type = "II")
```
```{r}
NauseaNullmodel <- lmer(data = SSQKPConversionTotalSSQ, NauseaScoreChange ~ (1|participant), REML = F)

Nauseamodel1 <- lmer(data = SSQKPConversionTotalSSQ, NauseaScoreChange ~ Timepoint +(1|participant), REML = F)


Nauseamodel2 <- lmer(data = SSQKPConversionTotalSSQ, NauseaScoreChange ~ Timepoint + Block + (1|participant), REML = F)

anova(NauseaNullmodel, Nauseamodel1, Nauseamodel2)

summary(NauseaNullmodel)
```

```{r}
# Nausearesults <- report(NauseaNullmodel, CI = 95)
# 
# #summary(results)
# summary(Nausearesults)
```


```{r}
#############################################################################
```

```{r}

SSQKPConversionDisoriSummary <- SSQKPConversionTotalSSQ %>% 
  
  group_by(Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(DisoriScoreChange, na.rm = T),
  sd = sd(DisoriScoreChange, na.rm = T)
  )   

SSQKPConversionDisoriBlockSummary <- SSQKPConversionTotalSSQ %>% 
  
  group_by(Timepoint, Block) %>% 
  summarise(
  n = n(),
  mean = mean(DisoriScoreChange, na.rm = T),
  sd = sd(DisoriScoreChange, na.rm = T)
  )   


```

```{r}

interaction.plot(x.factor =  SSQKPConversionDisoriSummary$Timepoint,
                 trace.factor = SSQKPConversionDisoriSummary$Timepoint,
                 response = SSQKPConversionDisoriSummary$mean,
                 fun = mean,
                 xlab = "Timepoint",
                 ylab = "Change in Disorientation subscore",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Disorientation",
                 fixed=F,
                 leg.bty ="o")


ggplot(SSQKPConversionDisoriBlockSummary,  aes(x = Timepoint, y = mean, colour = Block, group = Block, shape = Block))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_point (size = 3.5, position = position_dodge(width = 0.5)) +
  scale_shape_manual(values=c(0,15,1,16,2,17,18,19,20,21,22,23,24))+
  scale_color_brewer(palette="Dark2")+
  geom_line(position = position_dodge(width = 0.5))+
  labs(x = "Block",
      y = "Disorientation",
      title = "Disorientation Subscale",
      tag = "")+  
    scale_fill_hue(l = 2)+
   
    geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, position = position_dodge(width = 0.5))+
  geom_hline(yintercept = 0, linetype = 'dotted')+



  theme_bw()
```

```{r}
KPSSQModelDisori = lm(DisoriScoreChange ~ Timepoint,
              data = SSQKPConversionTotalSSQ)

Anova(KPSSQModelDisori,
      type = "II")

```

```{r}
DisoriNullmodel <- lmer(data = SSQKPConversionTotalSSQ, DisoriScoreChange ~ (1|participant), REML = F)

Disorimodel1 <- lmer(data = SSQKPConversionTotalSSQ, DisoriScoreChange ~Timepoint + (1|participant), REML = F)

Disorimodel2 <- lmer(data = SSQKPConversionTotalSSQ, DisoriScoreChange ~Timepoint + Block + (1|participant), REML = F)

anova(DisoriNullmodel, Disorimodel1, Disorimodel2)

summary(Disorimodel2)
```
```{r}
Disoriresults <- report(Disorimodel2, CI = 95)

#summary(results)
summary(Disoriresults)
```

