---
title: "Study1_Demogs"
output: html_document
date: '2022-04-24'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(tidyverse)
  library(readr)
  library(janitor)
  library(stringr)

```

```{r}
  #Read in the data
  DemogDataRaw <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 4/data/Qualtrics/Demogs/TGStudy4Demogs.csv") %>%  
    select(starts_with('Q')) 
```
```{r}
#Change the first row into column headers
DemogDataOrg <- row_to_names(DemogDataRaw, row_number = 1)
#Remove consent form columns


```



```{r}
DemogDataOrg <- DemogDataOrg %>% 
  rename(Age = `What is your age?`) %>% 
  rename(Gender = `Which gender do you identify with?`) %>% 
  rename(UKLicense = `Do you have a UK driving license?`) %>%
  rename(CountryLicense = `Which country did you get your driving license in?`) %>%
  rename(YearsExp = `How many years driving experience do you have, either from when you passed your driving test or when you started driving regularly? (years / months)`) %>%
  rename(UKYearsExp = `How many years driving experience do you have in the UK (years, months)`) %>%
   rename(GlasgowYearsExp = `How many years driving experience do you have driving around the West End of Glasgow? (years, months)`) %>%
  
  rename(VideoGamesTime = `Approximately how many hours do you play video games for in an average week?`) %>% 
  rename(MotionSickness = `Do you have any history of motion sickness? - Selected Choice`) %>% 
  rename(MotionSicknessText = `Do you have any history of motion sickness? - Other (Please describe) - Text`) 

```


```{r}
DemogDataOrg$Age = as.numeric(DemogDataOrg$Age)
DemogDataOrg$VideoGamesTime = as.numeric(DemogDataOrg$VideoGamesTime)

DemogDataOrg$YearsExp = as.numeric(DemogDataOrg$YearsExp)

DemogDataOrg$UKYearsExp = as.numeric(DemogDataOrg$UKYearsExp)
DemogDataOrg$GlasgowYearsExp = as.numeric(DemogDataOrg$GlasgowYearsExp)

DemogDataOrg$Gender[DemogDataOrg$Gender == 'Woman'] <- 'Female'
DemogDataOrg$Gender[DemogDataOrg$Gender == 'Female '] <- 'Female'
DemogDataOrg$Gender[DemogDataOrg$Gender == 'Male '] <- 'Male'

DemogDataOrg <- DemogDataOrg %>%
  subset(participant != "P01") %>%
  subset(participant != "P02") %>%
  subset(participant != "P03") %>% 
  subset(participant != "P04") %>%
  subset(participant != "P05") %>%
  subset(participant != "P06") %>%
  subset(participant != "P13") %>%
  subset(participant != "P21") 

DemogDataOrg <- DemogDataOrg[!is.na(DemogDataOrg$Age),]

table(DemogDataOrg$`How familiar are you with augmented reality (AR) prior to this experiment?`)

table(DemogDataOrg$`How familiar are you with virtual reality (VR) prior to this experiment?`)



```

```{r}
DemogSummaryTotal <- DemogDataOrg %>% 
  
  summarise(
  n = n(),
  AgeMean = mean(Age, na.rm = T),
  AgeSD = sd(Age, na.rm = T),
  Male = sum(Gender == 'Male'),
  Female = sum(Gender == "Female"),
  UKLicense = sum(UKLicense == 'Yes'),
  UKExp = mean(UKYearsExp, na.rm = T),
  UKExpmin = min(UKYearsExp, na.rm = T),
  UKExpmax = max(UKYearsExp, na.rm = T),
  
  UKEXPsd = sd(UKYearsExp, na.rm = T),
  GlasgowExp = mean(GlasgowYearsExp, na.rm = T),
  GlasgowExpmin = min(GlasgowYearsExp, na.rm = T),
  GlasgowExpmax = max(GlasgowYearsExp, na.rm = T),
  GlasgowExpsd = sd(GlasgowYearsExp, na.rm = T),
  meanVG = mean(VideoGamesTime, na.rm = T),
  meanExp = mean(YearsExp, na.rm = T),
  minExp = min(YearsExp, na.rm = T),
  maxExp = max(YearsExp, na.rm = T),
  sdExp = sd(YearsExp, na.rm = T)

  )   
```



```{r}
DBQ <- DemogDataOrg %>% 
  select(11: 37)

library(dplyr)
DBQ <- DBQ %>% mutate_all(list(~substr(., 1, 1))) 

IDs <- as.data.frame(WHNDataset$participant)

IDs <- IDs[!duplicated(IDs), ]
  
```

```{r}
DBQItems <- cols <- names(DBQ)

DBQ[DBQItems] <- lapply(DBQ[DBQItems], as.numeric)

DBQ$Errors <- 0
DBQ$Lapses <- 0
DBQ$Violations <- 0

DBQ$participant <- IDs

Errors <- DBQ %>% 
  select('participant', starts_with('E')) 
Errors$meanErrors = rowMeans(Errors[2:9])

Errors <- Errors %>% 
  select('participant', 'meanErrors')

Violations <- DBQ %>% 
  select('participant', starts_with('V')) 
Violations$meanViolations = rowMeans(Violations[2:9])

Violations <- Violations %>% 
  select('participant', 'meanViolations')



Lapses <- DBQ %>% 
  select('participant', starts_with('L')) 
Lapses$meanLapses = rowMeans(Lapses[2:9])

Lapses <- Lapses %>% 
  select('participant', 'meanLapses')
```
```{r}
DBQ <- left_join(DBQ, Errors, by = 'participant')

DBQ <- left_join(DBQ, Lapses, by = 'participant')

DBQ <- left_join(DBQ, Violations, by = 'participant')
```


```{r}
PptDBQ <- DBQ %>% 
  select(31,34)


```

