---
title: "HPEyeTracking"
author: "TGoodge"
date: '2023-01-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(stringr)
library(tidyr)
library(dplyr)
```


```{r}
#set the working directory to the ARETT package
#setwd("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R/ARETT-R-Package-master/R")

#source all the ARETT functions from the R folder
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/calculate_velocity.R")
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/classify_iaoi.R")
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/classify_idt.R")
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/classify_ivt.R")
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/discard_short_fixations.R")
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/gap_fill.R")
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/merge_fixations_iaoi.R")
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/merge_fixations_idt.R")
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/merge_fixations_ivt.R")
source("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/ARETT-R-Package-master/R/noise_reduction.R")
```


```{r}
#read in the data
dataFolder = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 4/data/EyeTracking"

#setwd = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study3/data/EyeTracking"
#list.files(path = dataFolder)

#Create a list of all the datafiles in the folder, and then convert to a list object - needs full names for the file path
file_list <- list.files(path = dataFolder, pattern = ".csv$", all.files = TRUE, full.names = TRUE, recursive = TRUE)

rawETdata = data.frame()


#Loop through the datafiles in file_list, assign them a name and then read them in
for(i in 1:length(file_list))
{
  filename <- file_list[i]
  print(filename)
  tempData <- read.csv(filename)
  pptInfo <- strsplit(filename, split = '-', fixed = TRUE)
  tempData$Participant <- pptInfo[[1]][4]
  tempData$Condition <- pptInfo[[1]][5]
  tempData$Date <- pptInfo[[1]][2]
  tempData$Time <- pptInfo[[1]][3]
 #assign(paste(substr(file_list[i],24,27)), read.csv(paste0(file_list[i])))

  rawETdata <- rbind(rawETdata, tempData)
}


rawETdata$Condition <- gsub(pattern = ".csv", replacement = "", x = rawETdata$Condition)
rawETdata$Condition <- str_sub(rawETdata$Condition, 4,-1)



#data = read.csv(file_list[1])

#data = read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study2ETData/P01/2022_11_08-16_09_35-P01-P01Control.csv", header = T)

```

```{r}
ordETdata <- rawETdata %>% 
  subset(Participant != "P01") %>%
  subset(Participant != "P02") %>%
  subset(Participant != "P03") %>% 
  subset(Participant != "P04") %>%
  subset(Participant != "P05") %>%
  subset(Participant != "P06") %>%
  subset(Participant != "P13") %>%
  subset(Participant != "P21") 

ordETdata$PIDCond <- paste(ordETdata$Participant, ordETdata$Condition, sep = "_")
ordETdata$Sort <- gsub(pattern = "_", replacement = " ", x = ordETdata$PIDCond)



#ordETdata <- ordETdata %>% 
 # drop_na(gazePoint_target_name)

# ordETdata <-  ordETdata %>% 
#   subset(gazePoint_target_name == "Wall")
# 

```

```{r}

timeETData <- ordETdata %>% 
  select(Participant, Condition, Date, Time, )

#timeETData$Condition <- gsub(pattern = ".csv", replacement = "", x = timeETData$Condition)
timeETData$Date <-    str_sub(timeETData$Date,-5,-1)
timeETData$Date <- gsub(pattern = "_", replacement = "/", x = timeETData$Date)
timeETData$Time <- gsub(pattern = "_", replacement = ":", x = timeETData$Time)

timeETData <- timeETData[!duplicated(timeETData), ]


timeETData$Sort <- paste(timeETData$Participant, timeETData$Condition)


```


```{r}
WHNdataFolder = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 4/data/WHN/"

file_list <- list.files(path = WHNdataFolder, pattern = "..csv$", all.files = TRUE, full.names = TRUE, recursive = TRUE) 
```

```{r read in raw data}
RawWHNDataset <- data.frame()
#loop through all the fills, create a temporary container, remove the first, second and last rows and then add 1 to the trials counter. Then bind it to the dataset
for (file in file_list){
  tempData <- read.csv(file, header = T)  
    
  RawWHNDataset <- bind_rows(RawWHNDataset, tempData)
}

```


```{r}
SortedWHNDataset <- RawWHNDataset  %>% 
  subset(participant != "P01") %>%
  subset(participant != "P02") %>%
  subset(participant != "P03") %>% 
  subset(participant != "P04") %>%
  subset(participant != "P05") %>%
  subset(participant != "P06") %>%
  subset(participant != "P13") %>%
  subset(participant != "P21") 

SortedWHNDataset <- SortedWHNDataset %>% 
  select(participant, image_file, trials_3.thisTrialN, hazard_video.started, trialResp.started, trialResp.corr, trialResp.rt, break_text.started, date)


```

```{r}
Counterbalancing <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 4/Study4Counterbalancing.csv", header = T)


Counterbalancing <- na.omit(Counterbalancing)

Counterbalancing$participant <- Counterbalancing$ï..PID

Counterbalancing <- Counterbalancing %>% 
  select(-ï..PID)


```


```{r}
OrderWHNDataset <- left_join(SortedWHNDataset, Counterbalancing, by = 'participant') 
OrderWHNDataset$Block <- 'Control' 


OrderWHNDataset$Block <-  if_else(OrderWHNDataset$trials_3.thisTrialN >= 30,OrderWHNDataset$Fourth,
                                  if_else(OrderWHNDataset$trials_3.thisTrialN >= 20,OrderWHNDataset$Third,
                                                  if_else(OrderWHNDataset$trials_3.thisTrialN >= 10,OrderWHNDataset$Second, 
                                                          OrderWHNDataset$First)))

OrderWHNDataset$trialResp.rt <-stringr::str_remove_all(OrderWHNDataset$trialResp.rt,"[\\[\\]]")
OrderWHNDataset$trialResp.rt <- as.numeric(OrderWHNDataset$trialResp.rt)
```



```{r}
timeWHNData <- OrderWHNDataset
timeWHNData <- rename(timeWHNData,trialNumber = trials_3.thisTrialN) 
timeWHNData <- rename(timeWHNData,DateFull = date)
timeWHNData <- rename(timeWHNData,ClipStart = hazard_video.started) 
timeWHNData <- rename(timeWHNData,ClipStop = trialResp.started)

timeWHNData[c('DateWHN', 'TimeWHN')] <- str_split_fixed(timeWHNData$Date, '_', 2)

#timeWHNData <- timeWHNData %>% 
 # select(participant, trialNumber, ClipStart, ClipStop, Block, DateWHN, TimeWHN)

timeWHNData$TimeWHN <- gsub(pattern = "h", replacement = ":", x = timeWHNData$TimeWHN)

timeWHNData$TimeWHN <- gsub(pattern = "\\.", replacement = ":", x = timeWHNData$TimeWHN)


timeWHNData$Sort <- paste(timeWHNData$participant, timeWHNData$Block)



```

```{r}
timeData <- left_join(timeWHNData, timeETData, by = "Sort")

timeData$TimeWHN <-  str_sub(timeData$TimeWHN, end = -5)


timeData$TimeWHNFormat <- strptime(timeData$TimeWHN,format="%H:%M:%S")
timeData$TimeFormat <- strptime(timeData$Time,format="%H:%M:%S")
timeData$RecordingStart <- as.numeric(difftime(timeData$TimeFormat,timeData$TimeWHNFormat, units = "secs"))

timeData$ETClipStart = timeData$ClipStart - timeData$RecordingStart
timeData$ETClipStop = timeData$ClipStop - timeData$RecordingStart
timeData$Participant <- timeData$participant

table(timeData$participant)

```


```{r}
timeDataExport <- timeData %>% 
  select(Participant, trialNumber, image_file, Sort, Condition, ClipStart, ClipStop, RecordingStart, ETClipStart, ETClipStop, )
  


timeDataExport$RecordingStart <- as.numeric(timeDataExport$RecordingStart)

timeDataExport$ETClipStart <- as.numeric(timeDataExport$ETClipStart)

timeDataExport$ETClipStop <- as.numeric(timeDataExport$ETClipStop)

colnames(timeDataExport)
```


```{r}
ClipTimes <- timeDataExport %>% 
  select(Participant, Sort, image_file, trialNumber, Condition, ETClipStart, ETClipStop)


ClipTimes <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/ClipTimes.csv", header = T)

ClipTimes <- ClipTimes %>% 
  subset(Participant != "P07")

#write.csv(ClipTimes, "ClipTimes.csv")

# 
# P07Time <- ClipTimes %>% 
#   subset(Participant == "P07")
# 
# P07Time$ETClipStop <- P07Time$ETClipStop - 30300
# 
# P07Time$ETClipStart <- P07Time$ETClipStart - 30300
# 
# ClipTimes <- rbind(ClipTimes, P07Time)

# 
# 
# ControlClipTimes <- ClipTimes %>% 
#   subset(Condition == "Control")
# 
# HUDClipTimes <- ClipTimes %>% 
#   subset(Condition == "HUD")
# 
# CueClipTimes <- ClipTimes %>% 
#   subset(Condition == "Cue")
# 
# HDDClipTimes <- ClipTimes %>% 
#   subset(Condition == "HDD")

```


```{r}
# timeData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study3Analysis/timeDataExport2.csv", stringsAsFactors = FALSE, encoding = "UTF-8") %>% 

timeDataExport <- timeDataExport %>% 
  subset(Participant != "P01") %>%
  subset(Participant != "P02") %>%
  subset(Participant != "P03") %>% 
  subset(Participant != "P04") %>%
  subset(Participant != "P05") %>%
  subset(Participant != "P06") %>%
  subset(Participant != "P13") %>%
  subset(Participant != "P21") 
  


ControlTimedata <- timeDataExport %>% 
  subset(Condition == "Control")

HUDTimedata <- timeDataExport %>% 
  subset(Condition == "HUD")

CueTimedata <- timeDataExport %>% 
  subset(Condition == "Cue")

HDDTimedata <- timeDataExport %>% 
   subset(Condition == "HDD")

```


```{r}
ETdata <- left_join(ordETdata, timeDataExport, by = "Sort")

# ETdata$StartTime <- ETdata$ClipStart * 1000
# ETdata$StopTime <- ETdata$ClipStop * 1000
ETdata$duration <- ETdata$ClipStart - ETdata$ClipStop

ETdata <- ETdata %>% 
  select(-Condition.x)


colnames(ETdata)[colnames(ETdata) == 'Sort.y'] <- 'PIDCond'

colnames(ETdata)[colnames(ETdata) == 'Condition.y'] <- 'Condition'

#write.csv(ETdata, "FullETdata.csv")


rm(rawETdata)
rm(ordETdata)
```


```{r}
ETdata <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/FullETdata.csv", header = T)

```


```{r}
ControlETdata <- ETdata %>% 
  subset(Condition == "Control")

HUDETdata <- ETdata %>% 
  subset(Condition == "HUD")

CueETdata <- ETdata %>% 
  subset(Condition == "Cue")

HDDETdata <- ETdata %>% 
  subset(Condition == "HDD")

```

#classify AOI

```{r}
#ControlETdata <- ControlETdata


  
#listControldata <- split(ControlETdata, f = ControlETdata$PIDCond)

#dataset <- listControldata[1]

#AOIControlETData <- data.frame()


for(dataset in listControldata) {
  data <- as.data.frame(dataset)
  #adjust column names
  cols <-colnames(data)
  cols<- gsub(".*\\.", "", cols)   
  colnames(data) <- cols
  
  
  print(data$PIDCond[1])
  print(Sys.time())
  startTime = data$eyeDataRelativeTimestamp[1]
  data$TimeStamp <- data$eyeDataRelativeTimestamp - startTime

  #convert the HasValue column to boolean for gap_fill function to work
  data$gazeHasValue <- as.logical(data$gazeHasValue)

  data_GF <- gap_fill(data, max_gap_length = 75)
  rm(data)
  
  data_NR <- noise_reduction(data_GF, method = median, window_size = 3)
  rm(data_GF)
  
  data_aoi <- classify_iaoi(data_NR, min_fixation_duration = 100)
  rm(data_NR)
  
  data_aoi_merge <- merge_fixations_iaoi(data_aoi)
  rm(data_aoi)
 
  
  AOIControlETData <- rbind(AOIControlETData, data_aoi_merge)

 
}
write.csv(AOIControlETData, "AOIControlETData.csv")
rm(data_aoi_merge)

```

```{r}
AOIControlETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/AOIControlETData.csv", header = T)

write.csv(AOIControlETData, "AOIControlETData.csv")

ShortAOIControlETData <- AOIControlETData %>% 
  select(PIDCond, TimeStamp, modified, eventIndex, eventType, eventDuration, fixation_x, fixation_y, fixation_z,gazePointAOI_name, gazePoint_target_name)

ShortAOIControlETData <- ShortAOIControlETData[!duplicated(ShortAOIControlETData$TimeStamp), ]

write.csv(ShortAOIControlETData, "ShortAOIControlETData.csv")

FixShortAOIControlETData <- ShortAOIControlETData %>% 
  subset(eventType == "fixation")

#FixShortAOIControlETData <- FixShortAOIControlETData[!duplicated(FixShortAOIControlETData$eventIndex),]
FixShortAOIControlETData$PIDCond <- gsub(pattern = "_", replacement = " ", x = FixShortAOIControlETData$PIDCond)


FixShortAOIControlETData <- FixShortAOIControlETData %>% 
  subset( PIDCond != "P07 Control")

write.csv(FixShortAOIControlETData, "FixShortAOIControlETData.csv")
```


```{r}

FixShortAOIControlETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/FixShortAOIControlETData.csv", header = T)

# take PPt ID and find it in ClipTimes table



FixShortAOIControlETData$Valid <- FALSE
test$Valid <- FALSE

test <- FixShortAOIControlETData %>% 
  subset(PIDCond == "P08 Control")


ClipFixShortAOIControlETData <- data.frame()


```

```{r}
check_time <- function(row) {
  pid_cond <- row$PIDCond
  time_stamp <- row$TimeStamp
  clip_rows <- ClipTimes[ClipTimes$Sort == pid_cond, ]
  
  for (i in 1:nrow(clip_rows)) {
    clip_row <- clip_rows[i, ]
    if (clip_row$ETClipStart <= time_stamp && time_stamp <= clip_row$ETClipStop) {
      return(TRUE)
    }
  }
  
  return(FALSE)
}


FixShortAOIControlETData$Valid <- sapply(1:nrow(FixShortAOIControlETData), function(i) check_time(FixShortAOIControlETData[i, ]))

```

```{r}
ValidAOIControlETData <- FixShortAOIControlETData %>% 
  subset(Valid != "FALSE")

```


```{r}
# AOIControlETData <- AOIControlETData %>% 
#   subset(eventType == "fixation")
# 
# AOIControlETData <- AOIControlETData[!duplicated(AOIControlETData[ , c("eventIndex")]),]
#                                                     

```

```{r}




```

```{r HUD Data}

#listHUDdata <- split(HUDETdata, f = HUDETdata$PIDCond)

#dataset <- listControldata[1]
#AOIHUDETData <- data.frame()


for(dataset in listHUDdata) {
  data <- as.data.frame(dataset)
  #adjust column names
  cols <-colnames(data)
  cols<- gsub(".*\\.", "", cols)   
  colnames(data) <- cols
  
  
  print(data$PIDCond[1])
  print(Sys.time())
  startTime = data$eyeDataRelativeTimestamp[1]
  data$TimeStamp <- data$eyeDataRelativeTimestamp - startTime

  #convert the HasValue column to boolean for gap_fill function to work
  data$gazeHasValue <- as.logical(data$gazeHasValue)

  data_GF <- gap_fill(data, max_gap_length = 75)
  rm(data)
  
  data_NR <- noise_reduction(data_GF, method = median, window_size = 3)
  rm(data_GF)
  
  data_aoi <- classify_iaoi(data_NR, min_fixation_duration = 100)
  rm(data_NR)
  
  data_aoi_merge <- merge_fixations_iaoi(data_aoi)
  rm(data_aoi)

 
  
  AOIHUDETData <- rbind(AOIHUDETData, data_aoi_merge)

 
}
write.csv(AOIHUDETData, "AOIHUDETData.csv")



```


```{r}
AOIHUDETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/AOIHUDETData.csv", header = T)

write.csv(AOIHUDETData, "AOIHUDETData.csv")

ShortAOIHUDETData <- AOIHUDETData %>% 
  select(PIDCond, TimeStamp, modified, eventIndex, eventType, eventDuration, fixation_x, fixation_y, fixation_z, gazePointAOI_name, gazePoint_target_name)

#ShortAOIHUDETData <- ShortAOIHUDETData[!duplicated(ShortAOIHUDETData[ , c("eventIndex")]),]

ShortAOIHUDETData <- ShortAOIHUDETData[!duplicated(ShortAOIHUDETData$TimeStamp), ]

write.csv(ShortAOIHUDETData, "ShortAOIHUDETData.csv")

FixShortAOIHUDETData <- ShortAOIHUDETData %>% 
  subset(eventType == "fixation")

write.csv(FixShortAOIHUDETData, "FixShortAOIHUDETData.csv")


#FixShortAOIHUDETData <- FixShortAOIHUDETData[!duplicated(FixShortAOIHUDETData$eventIndex), ]


```


```{r}

FixShortAOIHUDETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/FixShortAOIHUDETData.csv", header = T)

FixShortAOIHUDETData$PIDCond <- gsub(pattern = "_", replacement = " ", x = FixShortAOIHUDETData$PIDCond)

#FixShortAOIHUDETData$Valid <- FALSE

FixShortAOIHUDETData <- FixShortAOIHUDETData %>% 
  subset(PIDCond != "P07 HUD")

write.csv(FixShortAOIHUDETData, "FixShortAOIHUDETData.csv")


# AOIHUDETData <- AOIHUDETData %>% 
#   subset(eventType == "fixation")
# 
# 
# AOIHUDETData <- AOIHUDETData[!duplicated(AOIHUDETData[ , c("eventIndex")]),]
#                                                     

```

```{r}
FixShortAOIHUDETData$Valid <- sapply(1:nrow(FixShortAOIHUDETData), function(i) check_time(FixShortAOIHUDETData[i, ]))

```

```{r}
ValidAOIHUDETData <- FixShortAOIHUDETData %>% 
  subset(Valid != "FALSE")

```

```{r}

#listCuedata <- split(CueETdata, f = CueETdata$PIDCond)

#dataset <- listControldata[1]
#AOICueETData <- data.frame()


for(dataset in listCuedata) {
  data <- as.data.frame(dataset)
  #adjust column names
  cols <-colnames(data)
  cols<- gsub(".*\\.", "", cols)   
  colnames(data) <- cols
  
  
  print(data$PIDCond[1])
  print(Sys.time())
  startTime = data$eyeDataRelativeTimestamp[1]
  data$TimeStamp <- data$eyeDataRelativeTimestamp - startTime

  #convert the HasValue column to boolean for gap_fill function to work
  data$gazeHasValue <- as.logical(data$gazeHasValue)

  data_GF <- gap_fill(data, max_gap_length = 75)
  rm(data)
  
  data_NR <- noise_reduction(data_GF, method = median, window_size = 3)
  rm(data_GF)
  
  data_aoi <- classify_iaoi(data_NR, min_fixation_duration = 100)
  rm(data_NR)
  
  data_aoi_merge <- merge_fixations_iaoi(data_aoi)
  rm(data_aoi)

 
  
  AOICueETData <- rbind(AOICueETData, data_aoi_merge)

 
}
write.csv(AOICueETData, "AOICueETData.csv")


```

```{r}
AOICueETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/AOICueETData.csv", header = T)

#AOICueETData$TimeStamp <- AOICueETData$TimeStamp / 100

#write.csv(AOICueETData, "AOICueETData.csv")

ShortAOICueETData <- AOICueETData %>% 
  select(PIDCond, TimeStamp, modified, eventIndex, eventType, eventDuration, fixation_x, fixation_y, fixation_z, gazePointAOI_name, gazePoint_target_name)


ShortAOICueETData <- ShortAOICueETData[!duplicated(ShortAOICueETData$TimeStamp), ]

write.csv(ShortAOICueETData, "ShortAOICueETData.csv")

ShortAOICueETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/ShortAOICueETData.csv", header = T)

FixShortAOICueETData$PIDCond <- gsub(pattern = "_", replacement = " ", x = FixShortAOICueETData$PIDCond)

FixShortAOICueETData <- ShortAOICueETData %>% 
  subset(eventType == "fixation")

FixShortAOICueETData <- FixShortAOICueETData %>% 
  subset(PIDCond != "P07 Cue")

#FixShortAOICueETData <- FixShortAOICueETData[!duplicated(FixShortAOICueETData$eventIndex), ]

FixShortAOICueETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/FixShortAOICueETData.csv", header = T)

write.csv(FixShortAOICueETData, "FixShortAOICueETData.csv")



```

```{r}
FixShortAOICueETData$Valid <- sapply(1:nrow(FixShortAOICueETData), function(i) check_time(FixShortAOICueETData[i, ]))

```

```{r}
ValidAOICueETData <- FixShortAOICueETData %>% 
  subset(Valid != "FALSE")

```

```{r}
#listHDDdata <- split(HDDETdata, f = HDDETdata$PIDCond)

#dataset <- listControldata[1]
#AOIHDDETData <- data.frame()


for(dataset in listHDDdata) {
  data <- as.data.frame(dataset)
  #adjust column names
  cols <-colnames(data)
  cols<- gsub(".*\\.", "", cols)   
  colnames(data) <- cols
  
  
  print(data$PIDCond[1])
  print(Sys.time())
  startTime = data$eyeDataRelativeTimestamp[1]
  data$TimeStamp <- data$eyeDataRelativeTimestamp - startTime

  #convert the HasValue column to boolean for gap_fill function to work
  data$gazeHasValue <- as.logical(data$gazeHasValue)

  data_GF <- gap_fill(data, max_gap_length = 75)
  rm(data)
  
  data_NR <- noise_reduction(data_GF, method = median, window_size = 3)
  rm(data_GF)
  
  data_aoi <- classify_iaoi(data_NR, min_fixation_duration = 100)
  rm(data_NR)
  
  data_aoi_merge <- merge_fixations_iaoi(data_aoi)
  rm(data_aoi)

 
  
  AOIHDDETData <- rbind(AOIHDDETData, data_aoi_merge)

 
}
write.csv(AOIHDDETData, "AOIHDDETData.csv")
rm(data_aoi_merge)




```


```{r}

AOIHDDETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/AOIHDDETData.csv", header = T)

AOIHDDETData$TimeStamp <- AOIHDDETData$TimeStamp / 100

write.csv(AOIHDDETData, "AOIHDDETData.csv")

ShortAOIHDDETData <- AOIHDDETData %>% 
  select(PIDCond, TimeStamp, modified, eventIndex, eventType, eventDuration, fixation_x, fixation_y, fixation_z, gazePointAOI_name, gazePoint_target_name)

ShortAOIHDDETData <- ShortAOIHDDETData[!duplicated(ShortAOIHDDETData$TimeStamp), ]

write.csv(ShortAOIHDDETData, "ShortAOIHDDETData.csv")


ShortAOIHDDETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/ShortAOIHDDETData.csv", header = T)



FixShortAOIHDDETData <- ShortAOIHDDETData %>% 
  subset(eventType == "fixation")

FixShortAOIHDDETData$PIDCond <- gsub(pattern = "_", replacement = " ", x = FixShortAOIHDDETData$PIDCond)


FixShortAOIHDDETData <- FixShortAOIHDDETData %>% 
  subset(PIDCond != "P07 HDD")

#FixShortAOIHDDETData <- FixShortAOIHDDETData[!duplicated(FixShortAOIHDDETData$eventIndex),]


write.csv(FixShortAOIHDDETData, "FixShortAOIHDDETData.csv")

FixShortAOIHDDETData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Documents/R_Scripts/Study4Analysis/FixShortAOIHDDETData.csv", header = T)


# AOIHUDETData <- AOIHUDETData %>% 
#   subset(eventType == "fixation")
# 
# 
# AOIHUDETData <- AOIHUDETData[!duplicated(AOIHUDETData[ , c("eventIndex")]),]
#                                                     

```

```{r}
FixShortAOIHDDETData$Valid <- sapply(1:nrow(FixShortAOIHDDETData), function(i) check_time(FixShortAOIHDDETData[i, ]))

```

```{r}
ValidAOIHDDETData <- FixShortAOIHDDETData %>% 
  subset(Valid != "FALSE")

```

```{r}

ValidAOICueETData <- ValidAOIControlETData %>% 
  select(-c(X.1, X))

ValidAOICueETData <- ValidAOICueETData %>% 
  select(-c(X))

ValidAOIHUDETData <- ValidAOIHUDETData %>% 
  select(-c(X))

ValidAOIHDDETData <- ValidAOIHDDETData %>% 
  select(-c(X.1, X))



ValidAOIETData <- rbind(ValidAOIControlETData, ValidAOICueETData, ValidAOIHUDETData, ValidAOIHDDETData)

ValidAOIControlETData <- ValidAOIControlETData %>% 
  separate(PIDCond,)

write.csv(ValidAOIETData, "ValidAOIETData.csv")

```

```{r}
ValidAOIETData[c('ID', 'Condition')] <- str_split_fixed(ValidAOIETData$PIDCond, ' ', 2)

ScreenData <- ValidAOIETData %>% 
  subset(gazePoint_target_name == "Wall")



```


```{r}
SummaryAOI <- ValidAOIETData %>% 
  group_by(Condition) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration),
            sdDuration = sd(eventDuration),
            fixationCount = sum(eventType == "fixation")
            )

TargetSummary <- ScreenData %>% 
  group_by(Condition, gazePointAOI_name) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration),
            sdDuration = sd(eventDuration),
            fixationX = mean(fixation_x, na.rm = T),
            fixation_y = mean(fixation_y, na.rm = T))

```
```{r}
ggplot(data=TargetSummary, aes(x= Condition, y=n, fill = gazePointAOI_name )) +
  # geom_point()+
  # geom_bin2d()+sd
  geom_col()+
  labs(title= "Control")
```



```{r}

listControldata <- split(ControlETdata, f = ControlETdata$PIDCond)

dataset <- listControldata[1]

fixationControlETData <- data.frame()


for(dataset in listControldata) {
  data <- as.data.frame(dataset)
  #adjust column names
  cols <-colnames(data)
  cols<- gsub(".*\\.", "", cols)   
  colnames(data) <- cols
  
  
  print(data$PIDCond[1])
  startTime = data$eyeDataRelativeTimestamp[1]
  data$TimeStamp <- data$eyeDataRelativeTimestamp - startTime

  #convert the HasValue column to boolean for gap_fill function to work
  data$gazeHasValue <- as.logical(data$gazeHasValue)

  data_GF <- gap_fill(data, max_gap_length = 75)
  
  
  data_NR <- noise_reduction(data_GF, method = median, window_size = 3)
 
  data_idt <- classify_idt(data = data_NR, dispersion_threshold = 1.6, time_window = 250)

  data_mergeIDT <- merge_fixations_idt(data_idt, max_time = 75, dispersion_threshold = 1.6)
  
  data_proc <- data_mergeIDT%>% 
    select(PIDCond, gazePoint_target_name, gazePointAOI_name, gazePointAOIHit, gazePoint_x, gazePoint_y, gazePoint_z, eventIndex, eventType, eventDuration, fixation_x, fixation_y, fixation_z, TimeStamp)
  
  fixationControlETData <- rbind(fixationControlETData, data_proc)
 
}

fixationControlETData$Condition <- "Control"

FullfixationControlETData <- fixationControlETData[!duplicated(fixationControlETData[c(1,8)]),]
FullfixationControlETData <- rename(FullfixationControlETData, Sort = PIDCond)
FullfixationControlETData$Sort <- gsub(pattern = "_", replacement = " ", x = FullfixationControlETData$Sort)


```




```{r}
ggplot(data=FixShortAOIControlETData, aes(x=fixation_x, y=fixation_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 70)+
    xlim(-0.35, 0.35)+
  ylim(-0.15, 0.35)+
    scale_fill_continuous(type = "viridis") +
  labs(title= "Control")

ggplot(data=AOIHUDETData, aes(x=fixation_x, y=fixation_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 100)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title = "HUD")

ggplot(data=AOICueETData, aes(x=fixation_x, y=fixation_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 100)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title = "Cue")

ggplot(data=AOIHDDETData, aes(x=fixation_x, y=fixation_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 100)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title = "HDD")

```
```{r}

ggplot(data=AOIControlETData, aes(x=gazePoint_x, y=gazePoint_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 150)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title= "Control")

ggplot(data=AOIHUDETData, aes(x=gazePoint_x, y=gazePoint_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 150)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title = "HUD")

ggplot(data=AOICueETData, aes(x=gazePoint_x, y=gazePoint_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 150)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title = "Cue")

ggplot(data=AOIHDDETData, aes(x=gazePoint_x, y=gazePoint_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 150)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title = "HDD")

```

```{r}

ggplot(data=AOIControlETData, aes(x=gazeDirection_x, y=gazeDirection_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 150)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title= "Control")

ggplot(data=AOIHUDETData, aes(x=gazeDirection_x, y=gazeDirection_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 150)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title = "HUD")

ggplot(data=AOICueETData, aes(x=gazeDirection_x, y=gazeDirection_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 150)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title = "GemsCued")

ggplot(data=AOIHDDETData, aes(x=gazeDirection_x, y=gazeDirection_y)) +
  # geom_point()+
  # geom_bin2d()+
  stat_bin_2d(bins = 150)+
    xlim(-0.5, 0.5)+
  ylim(-0.5, 0.5)+
    scale_fill_continuous(type = "viridis") +
  labs(title = "GemsTablet")

```
```{r}
AOIControlETData$TimeStamp <- AOIControlETData$TimeStamp / 100
AOIControlETData$DuringClip <- FALSE

AOIControlETData$DuringClip <- if_else(AOIControlETData$TimeStamp >= AOIControlETData$ETClipStart && AOIControlETData$TimeStamp <= AOIControlETData$ETClipStop, TRUE, FALSE)

AOIControlETData<- AOIControlETData %>% 
  select(-(AOIControlETData$DuringClip == TRUE))

AOIControlETDataClips <- subset(AOIControlETData, DuringClip)


```

```{r}


ClipTimes <- AOIControlETData %>% 
  select(PIDCond, image_file, ClipStart, ClipStop, ETClipStart,ETClipStop)

ClipTimes <- ClipTimes[!duplicated(ClipTimes$ClipStart), ]


```


```{r}
#FixationCount <- rbind(AOIControlETData, AOICueETData, AOIHDDETData, AOIHUDETData) 


ControlFixationCountSummary <- AOIControlETData %>% 
  group_by(Condition, gazePoint_target_name, gazePointAOI_name) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration, na.rm = T),
            sdDuration = sd(eventDuration, na.rm = T),
            minDuration = min(eventDuration, na.rm = T),
            maxDuration = max(eventDuration, na.rm = T))


CueFixationCountSummary <- AOICueETData %>% 
  group_by(Condition, gazePoint_target_name,gazePointAOI_name) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration, na.rm = T),
            sdDuration = sd(eventDuration, na.rm = T),
            minDuration = min(eventDuration, na.rm = T),
            maxDuration = max(eventDuration, na.rm = T))


HUDFixationCountSummary <- AOIHUDETData %>% 
  group_by(Condition, gazePoint_target_name,gazePointAOI_name) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration, na.rm = T),
            sdDuration = sd(eventDuration, na.rm = T),
            minDuration = min(eventDuration, na.rm = T),
            maxDuration = max(eventDuration, na.rm = T))

HDDFixationCountSummary <- AOIHDDETData %>% 
  group_by(Condition, gazePoint_target_name,gazePointAOI_name) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration, na.rm = T),
            sdDuration = sd(eventDuration, na.rm = T),
            minDuration = min(eventDuration, na.rm = T),
            maxDuration = max(eventDuration, na.rm = T))

```


```{r}
#FixationDuration <- rbind(AOIControlETData, AOICueETData, AOIHDDETData, AOIHUDETData) 
ControlFixationDurationSummary <- AOIControlETData %>% 
  group_by(Condition, gazePoint_target_name, gazePointAOI_name) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration, na.rm = T),
            sdDuration = sd(eventDuration, na.rm = T),
            minDuration = min(eventDuration, na.rm = T),
            maxDuration = max(eventDuration, na.rm = T))

CueFixationDurationSummary <- AOICueETData %>% 
  group_by(Condition, gazePoint_target_name, gazePointAOI_name) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration, na.rm = T),
            sdDuration = sd(eventDuration, na.rm = T),
            minDuration = min(eventDuration, na.rm = T),
            maxDuration = max(eventDuration, na.rm = T))



HUDFixationDurationSummary <- AOIHUDETData %>% 
  group_by(Condition, gazePoint_target_name, gazePointAOI_name) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration, na.rm = T),
            sdDuration = sd(eventDuration, na.rm = T),
            minDuration = min(eventDuration, na.rm = T),
            maxDuration = max(eventDuration, na.rm = T))

HDDFixationDurationSummary <- AOIHDDETData %>% 
  group_by(Condition, gazePoint_target_name, gazePointAOI_name) %>% 
  summarise(n = n(),
            meanDuration = mean(eventDuration, na.rm = T),
            sdDuration = sd(eventDuration, na.rm = T),
            minDuration = min(eventDuration, na.rm = T),
            maxDuration = max(eventDuration, na.rm = T))




```
