---
title: "Study5&6Comparison"
author: "TGoodge"
date: "2024-04-30"
output: html_document
---

```{r setup, include=FALSE}

library(pwr)
library(tidyverse)
library(splitstackshape)
library(stringr)
library(data.table)
library(dplyr)
library(tidyr)
library(gridExtra)
library(lme4)
library(lmerTest)
library(afex)
library(effects)
library(ggplot2)
library(ggthemes)
library(ggpubr)
library(report)
library(janitor)
library(stringr)
library(rstatix)
```

```{r}
Study5WHN <-  read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 5/data/S5WHN.csv")

Study5WHN$Study <-5

Study5WHN$Study <-as.factor(Study5WHN$Study)

Study6WHN <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 6/Study6data/S6WHN.csv")

Study6WHN$Study <-6
Study6WHN$Study <-as.factor(Study6WHN$Study)

Study6WHN$Block[Study6WHN$Block == "Control"] <- "Control - 2"

Study6WHN$Block[Study6WHN$Block == "Social"] <- "Social Cue"

Study6WHN$Block[Study6WHN$Block == "Visual"] <- "Visual Cue"

Study6WHN$Block[Study6WHN$Block == "Avatar"] <- "Avatar Cue"



FullWHN <- rbind(Study5WHN, Study6WHN)

FullWHN$participant <- as.factor(FullWHN$participant)
FullWHN$image_file <- as.factor(FullWHN$image_file)


FullWHN$Block <- as.factor(FullWHN$Block)

FullWHN$Block <- factor(FullWHN$Block, levels = c("Control","Control - 2", "Visual", "Visual Cue", "Avatar","Avatar Cue", "Social Cue", "NDRT"))


FullWHNPptDataset <- FullWHN %>% 
  group_by(participant, Block) %>% 
  summarise(sumWHN = sum(trialResp.corr),
            Study = Study,
            RTmean = mean(trialResp.rt))


ControlData <- FullWHN %>% 
  subset(Block == "Control" | Block == "Control - 2")

PptControlData <- ControlData %>% 
  group_by(participant, Study, Block) %>% 
  summarise(n = n(),
            score = sum(trialResp.corr),
            RT = mean(trialResp.rt)
            
            )

VisualData <- FullWHN %>% 
  subset(Block == "Visual" | Block == "Visual Cue")

PptVisualData <- VisualData %>% 
  group_by(participant, Study, Block) %>% 
  summarise(n = n(),
            score = sum(trialResp.corr),
            RT = mean(trialResp.rt)
            
            )
AvatarData <- FullWHN %>% 
  subset(Block == "Avatar"| Block == "Avatar Cue")

PptAvatarData <- AvatarData %>% 
  group_by(participant, Study, Block) %>% 
  summarise(n = n(),
            score = sum(trialResp.corr),
            RT = mean(trialResp.rt)
            
            )

SocialData <- FullWHN %>% 
  subset(Block == "Avatar"| Block == "Social Cue")
PptSocialData <- SocialData %>% 
  group_by(participant, Study, Block) %>% 
  summarise(n = n(),
            score = sum(trialResp.corr),
            RT = mean(trialResp.rt)
            )

NDRTVisualData <- FullWHN %>% 
  subset(Block == "NDRT" | Block == "Visual Cue")

PptNDRTVisualData <- NDRTVisualData %>% 
  group_by(participant, Study, Block) %>% 
  summarise(n = n(),
            score = sum(trialResp.corr),
            RT = mean(trialResp.rt)
            
            )

NDRTAvatarData <- FullWHN %>% 
  subset(Block == "NDRT"| Block == "Avatar Cue")

PptNDRTAvatarData <- NDRTAvatarData %>% 
  group_by(participant, Study, Block) %>% 
  summarise(n = n(),
            score = sum(trialResp.corr),
            RT = mean(trialResp.rt)
            
            )

NDRTSocialData <- FullWHN %>% 
  subset(Block == "NDRT"| Block == "Social Cue")

PptNDRTSocialData <- NDRTSocialData %>% 
  group_by(participant, Study, Block) %>% 
  summarise(n = n(),
            score = sum(trialResp.corr),
            RT = mean(trialResp.rt)
            
            )



```
#Hazard Prediction
```{r}

FullWHNSummary <- FullWHN %>% 
  group_by(Block, Study) %>% 
  summarise(WHN = sum(trialResp.corr / 24) ,
            WHNMean = mean(trialResp.corr),
            WHNPercent = sum((trialResp.corr / 24) /10) * 100,
            sdWHN = sd(trialResp.corr),
            seWHN = (sd(trialResp.corr))/ sqrt(24),
            meanConf = mean(conf_slider.response, na.rm = T),
            sdConf = sd(conf_slider.response),
            seConf = (sd(conf_slider.response))/ sqrt(24),
            meanAttention = mean(Attention_slider.response, na.rm = T),
            sdAttention = sd(Attention_slider.response, na.rm=T),
            seAttention = (sd(Attention_slider.response, na.rm=T))/ sqrt(24),
            trialRespmean = mean(trialResp.rt, na.rm=T),
            trialRespSD = sd(trialResp.rt, na.rm=T)
            )


FullWHNPptSummary <- FullWHNPptDataset %>% 
  group_by(Block) %>% 
  summarise(WHN = mean(sumWHN),
            propWHN = (mean(sumWHN) / 10) * 100)


ControlSummary <- ControlData %>% 
  group_by(Block, Study) %>% 
  summarise(WHN = sum(trialResp.corr / 24) ,
            WHNPercent = sum((trialResp.corr / 24) /10) * 100,
            sdWHN = sd(trialResp.corr),
            seWHN = (sd(trialResp.corr))/ sqrt(24),
            meanConf = mean(conf_slider.response, na.rm = T),
            sdConf = sd(conf_slider.response),
            seConf = (sd(conf_slider.response))/ sqrt(24),
            meanAttention = mean(Attention_slider.response, na.rm = T),
            sdAttention = sd(Attention_slider.response, na.rm=T),
            seAttention = (sd(Attention_slider.response, na.rm=T))/ sqrt(24),
            trialRespmean = mean(trialResp.rt, na.rm=T),
            trialRespSD = sd(trialResp.rt, na.rm=T)
            )

VisualSummary <- VisualData %>% 
  group_by(Block, Study) %>% 
  summarise(WHN = sum(trialResp.corr / 24) ,
            WHNPercent = sum((trialResp.corr / 24) /10) * 100,
            sdWHN = sd(trialResp.corr),
            seWHN = (sd(trialResp.corr))/ sqrt(24),
            meanConf = mean(conf_slider.response, na.rm = T),
            sdConf = sd(conf_slider.response),
            seConf = (sd(conf_slider.response))/ sqrt(24),
            meanAttention = mean(Attention_slider.response, na.rm = T),
            sdAttention = sd(Attention_slider.response, na.rm=T),
            seAttention = (sd(Attention_slider.response, na.rm=T))/ sqrt(24),
            trialRespmean = mean(trialResp.rt, na.rm=T),
            trialRespSD = sd(trialResp.rt, na.rm=T)
            )

AvatarSummary <- AvatarData %>% 
  group_by(Block, Study) %>% 
  summarise(WHN = sum(trialResp.corr / 24) ,
            WHNPercent = sum((trialResp.corr / 24) /10) * 100,
            sdWHN = sd(trialResp.corr),
            seWHN = (sd(trialResp.corr))/ sqrt(24),
            meanConf = mean(conf_slider.response, na.rm = T),
            sdConf = sd(conf_slider.response),
            seConf = (sd(conf_slider.response))/ sqrt(24),
            meanAttention = mean(Attention_slider.response, na.rm = T),
            sdAttention = sd(Attention_slider.response, na.rm=T),
            seAttention = (sd(Attention_slider.response, na.rm=T))/ sqrt(24),
            trialRespmean = mean(trialResp.rt, na.rm=T),
            trialRespSD = sd(trialResp.rt, na.rm=T)
            )

SocialSummary <- SocialData %>% 
  group_by(Block, Study) %>% 
  summarise(WHN = sum(trialResp.corr / 24) ,
            WHNPercent = sum((trialResp.corr / 24) /10) * 100,
            sdWHN = sd(trialResp.corr),
            seWHN = (sd(trialResp.corr))/ sqrt(24),
            meanConf = mean(conf_slider.response, na.rm = T),
            sdConf = sd(conf_slider.response),
            seConf = (sd(conf_slider.response))/ sqrt(24),
            meanAttention = mean(Attention_slider.response, na.rm = T),
            sdAttention = sd(Attention_slider.response, na.rm=T),
            seAttention = (sd(Attention_slider.response, na.rm=T))/ sqrt(24),
            trialRespmean = mean(trialResp.rt, na.rm=T),
            trialRespSD = sd(trialResp.rt, na.rm=T)
            )
```

#Define palettes
```{r}
library(RColorBrewer)

base_palette <- brewer.pal(n = 12, name = "Paired")
custom_palette <- c(
  base_palette[3], base_palette[4],   # Group 2: 2 similar colors
    base_palette[1], base_palette[2],   # Group 1: 2 similar colors

  "#F45B5B", base_palette[6], "#A50F15",  # Group 3: 3 similar colors
  base_palette[8]                     # Group 4: 1 color
)


S5_palette <- c(base_palette[3],base_palette[1],base_palette[8])
S6_palette <- c(base_palette[4], base_palette[2],base_palette[6], "#A50F15")

#  scale_fill_manual(values = custom_palette) +


# Print the custom palette to verify
print(custom_palette)

```

```{r}

#"#A6CEE3" "#1F78B4" "#B2DF8A" "#33A02C" "#FB9A99" "#E31A1C" "#FDBF6F" "#FF7F00" "#F45B5B"

```

```{r}
PlotData <- FullWHN %>% 
  select(participant, trialResp.corr, trials_3.thisTrialN, Block, Study) %>%   group_by(participant, Block, Study) %>% 
  summarise(participant = participant,
            score = sum(trialResp.corr),
            Block = Block)


WHNPlot2 <- ggplot(data = PlotData, aes(x = Block, y = score, fill = Block))+
  geom_violin(alpha = 0.5)+
  geom_boxplot(width = 0.15)+
  ylim(0,10)+
  scale_fill_manual(values = custom_palette) +
  theme_classic()+
theme(legend.position="none") +theme(text=element_text(size = 20)) +

  theme(axis.text=element_text(size=12))+
  labs(title = "Hazard Prediction Score", x = "NDRT Presentation Condition", y = "Average correct responses")+
    theme(plot.title=element_text(vjust=7))+

  theme(plot.margin =unit(c(1.5,0,0,0),"cm"))

WHNPlot2
```

```{r}
ConfPlot2 <- ggplot(data = FullWHN, aes(x = Block, y = conf_slider.response, fill = Block))+
  geom_violin(alpha = 0.5) + geom_boxplot(width = 0.2)+
  labs(title = "Average Confidence Score", y = "Mean Confidence Rating", x = "", key= FALSE)+
  ylim(0,1.0)+
  scale_fill_manual(values = custom_palette) +
  theme_classic()+
  theme(legend.position="none")+
  theme(text=element_text(size = 15)) +
  theme(axis.text=element_text(size=10))+
  theme(plot.title=element_text(vjust=10))+

  theme(plot.margin =unit(c(1.5,0,0,0),"cm"))


ConfPlot2

AttPlot2 <- ggplot(data = FullWHN, aes(x = Block, y = Attention_slider.response, fill = Block))+
  geom_violin(alpha = 0.5)+geom_boxplot( width = 0.1)+
 
  labs(title = "Subjective Attention Rating", y = "Mean Attention Rating", x = "NDRT Presentation Condition")+
  scale_fill_manual(values = custom_palette) +
  ylim(0,1.0)+
    theme_classic()+
theme(legend.position="none")+
  theme(text=element_text(size = 15))+
 theme(plot.title=element_text(vjust=10))+
  theme(axis.text=element_text(size=10))+
  theme(plot.margin =unit(c(1.5,0,0,0),"cm"))

  AttPlot2
  
```

#FullPlot
```{r group all graphs together}
library(cowplot)

subPlot<- plot_grid(ConfPlot2, AttPlot2, labels = c('b)','c)'),ncol = 1)

subPlot


legend_b <- get_legend(
  WHNPlot2 + 
    guides(color = guide_legend(nrow = 1)) +
   theme(legend.position = "bottom")
)

FullPlot <- plot_grid(WHNPlot2, subPlot, labels = ('a)'))

FullPlot2 <- plot_grid(WHNPlot2, ConfPlot2, labels = ('a)'))
FullPlot2

FinalPlot <- plot_grid(FullPlot, legend_b, ncol = 1, rel_heights = c(1, .1))

FinalPlot

FinalPlot2 <- plot_grid(FullPlot2, legend_b, ncol = 1, rel_heights = c(1, .1))
FinalPlot2

file1 <- tempfile("file1", fileext = ".png")

width = 1920

ggsave(filename = "WHNConfRoboFullPlot.png",
       plot = FinalPlot,
       scale = 3,
       device = png,
       width = 3840,
       units = "px",
       dpi = 700)

ggsave(filename = "WHNConfRoboFullPlot2.png",
       plot = FinalPlot2,
       scale = 3,
       device = png,
       width = 3840,
       units = "px",
       dpi = 700)

```

```{r}

FullWHNAOV <- aov(data = FullWHN, trialResp.corr ~ Study * Block)
summary(FullWHNAOV)
TukeyHSD(FullWHNAOV)


# PptWHNAOV <- aov(data = FullWHNPptDataset, sumWHN ~ Study * Block + Error(participant/Block))
# summary(PptWHNAOV)
# TukeyHSD(PptWHNAOV)

# model.tables(PptWHNAOV, "means")
```


```{r}
print("Control")
ControlANOVA <- aov(data = ControlData, formula = trialResp.corr ~ Study)
summary(ControlANOVA)

print("Visual")
VisualANOVA <- aov(data = VisualData, formula = trialResp.corr ~ Study)
summary(VisualANOVA)

print("Avatar")
AvatarANOVA <- aov(data = AvatarData, formula = trialResp.corr ~ Study)
summary(AvatarANOVA)

print("Social")
SocialANOVA <- aov(data = SocialData, formula = trialResp.corr ~ Study)
summary(SocialANOVA)

print("NDRTVisual")
NDRTVisualANOVA <- aov(data = NDRTVisualData, formula = trialResp.corr ~ Study)
summary(NDRTVisualANOVA)

print("NDRTAvatar")
NDRTAvatarANOVA <- aov(data = NDRTAvatarData, formula = trialResp.corr ~ Study)
summary(NDRTAvatarANOVA)

print("NDRTSocial")
NDRTSocialANOVA <- aov(data = NDRTSocialData, formula = trialResp.corr ~ Study)
summary(NDRTSocialANOVA)
```


```{r}
bxp <- ggboxplot(
  FullWHNPptDataset, x = "Block", y = "sumWHN",
  color = "Block", palette = "jco"
  )

bxp
```

```{r}

bxp <- ggpaired(
  FullWHNPptDataset, x = "Block", y = "sumWHN",  color = "Block", palette = "jco",id = "participant",
  line.color = "gray", linetype = "dashed"
  )

bxp
```

```{r}
FullWHNPptDataset %>%
  group_by(Study,Block) %>%
  identify_outliers(sumWHN)


FullWHNPptDataset %>%
  group_by(Study,Block) %>%
  shapiro_test(sumWHN)
```



```{r}
tukey.plot.aov<-aov(data = FullWHN, trialResp.corr ~ Block * Study)
tukey.plot.test<-TukeyHSD(tukey.plot.aov)
plot(tukey.plot.test, las = 1)
```
#z score WHN
```{r}

df <- data.frame(FullWHNPptDataset$sumWHN)
z_scores <- as.data.frame(sapply(df, function(df) (abs(df-mean(df))/sd(df))))

z_scores$ZScores <- z_scores$FullWHNPptDataset.sumWHN
z_scores <- z_scores %>% 
  select(-1)

FullWHNPptDataset$WHNZScore <- z_scores$ZScores

FullWHNPptDataset <- FullWHNPptDataset %>% 
  subset(z_scores <= 3)


```
#power
```{r}

WHNClassData <- FullWHN %>% 
  select(participant, trialResp.corr, image_file, Block) %>% 
  pivot_wider(id_cols = "participant", names_from = "image_file" ,values_from = trialResp.corr )

Group <- FullWHN %>% 
  select(participant,Block) 

Group <- Group[!duplicated(Group$participant), ]


df <- left_join(WHNClassData, Group, by = "participant")
```

#WHN MIXED ANOVA
```{r}
library(afex)

#Perform the ANOVA
model_FullWHN <- aov_car(score ~ (Block*Study) + Error(participant/Block),
                    data = PlotData)


#Get the output
summary(model_anx)

a <- aov(data = FullWHN, formula = trialResp.corr ~ Block * Study)
summary(a)

TukeyHSD(a)

```
#WHN GLMER
```{r}
FullWHN$Block <- relevel(FullWHN$Block, ref = "NDRT")
FullWHN$trials_3.thisTrialN <- as.factor(FullWHN$trials_3.thisTrialN)

WHNModel1 <- glmer(data = FullWHN, formula = trialResp.corr ~  Block * Study + (1 |participant)  , family = binomial, glmerControl( optimizer = "bobyqa"))
summary(WHNModel1)

WHNModel2 <- glmer(data = FullWHN, formula = trialResp.corr ~  Block * Study + (1 |participant) +   , family = binomial, glmerControl( optimizer = "bobyqa"))
summary(WHNModel2)

WHNModelBasic <- glmer(data = FullWHN, formula = trialResp.corr ~  Block * Study + (1 |participant) + (1|image_file) , family = binomial, glmerControl( optimizer = "bobyqa"))
summary(WHNModelBasic)

anova(WHNModel1,WHNModelBasic,WHNModel2)


fix.fit <- lm(WHNModelBasic, data.df, method = "qr", singular.ok = TRUE)
p <- length(fix.fit$coef)
coef <- fix.fit$coef
no.NA <- sum(is.na(coef))
rank <- fix.fit$rank


# library(effects)
# 
# ef <- as.data.frame(effect("Block", WHNModelBasic))
# head(ef)

library(report)
WHNResults <- report(WHNModelBasic, CI = 95)

summary(WHNResults)
```

```{r}
FullWHNPptDataset$Block <- relevel(FullWHNPptDataset$Block, ref = "NDRT")

WHNModelPptBasic <- glmer(data = FullWHNPptDataset, formula = sumWHN ~  Block * Study + (1 |participant) , family = poisson, glmerControl( optimizer = "bobyqa"))

summary(WHNModelPptBasic)
# library(effects)
# 
# ef <- as.data.frame(effect("Block", WHNModelBasic))
# head(ef)

library(report)
WHNResults <- report(WHNModelPptBasic, CI = 95)

summary(WHNResults)
```

#Individual GLMs

```{r} 


print("***************Control - Control 2***************")
ControlGLM <- glm(data = ControlData, trialResp.corr ~ Study, family = "binomial")
summary(ControlGLM)

print("***************Avatar - Avatar Cue***************")
AvatarGLM <- glm(data = AvatarData, trialResp.corr ~ Study, family = "binomial")
summary(AvatarGLM)

print("***************Visual - Visual Cue***************")
VisualGLM <- glm(data = VisualData, trialResp.corr ~ Study, family = "binomial")
summary(VisualGLM)

print("***************Avatar - Social Cue***************")
SocialGLM <- glm(data = SocialData, trialResp.corr ~ Study, family = "binomial")
summary(SocialGLM)


print("***************NDRT - Visual Cue***************")
NDRTVisualGLM <-  glm(data = NDRTVisualData, trialResp.corr ~ Study, family = "binomial")
summary(NDRTVisualGLM)
print("***************NDRT - Avatar Cue***************")
NDRTAvatarGLM <-  glm(data = NDRTAvatarData, trialResp.corr ~ Study, family = "binomial")
summary(NDRTAvatarGLM)
print("***************NDRT - Social Cue***************")
NDRTSocialGLM <-  glm(data = NDRTSocialData, trialResp.corr ~ Study, family = "binomial")
summary(NDRTSocialGLM)

```


```{r}
AvatarGLM <- glm(data = AvatarData, trialResp.corr ~ Study, family = "binomial")
summary(AvatarGLM)


predict(AvatarGLM, newdata = data.frame(Study = c("5","6")))
1-pchisq(deviance(AvatarGLM), df.residual(AvatarGLM)) 

AvatarGLM2 <- glm(data = AvatarData, trialResp.corr ~ Study * trials_3.thisTrialN, family = "binomial")
summary(AvatarGLM2)

AvatarGLM3 <- glm(data = AvatarData, trialResp.corr ~ Study * image_file, family = "binomial")
summary(AvatarGLM3)

AIC(AvatarGLM, AvatarGLM2,AvatarGLM3)

```

```{r}
NDRTAvatarGLM <- glm(data = NDRTAvatarData, trialResp.corr ~ Study, family = "binomial")
summary(NDRTAvatarGLM)

table(NDRTAvatarData$trials_3.thisTrialN)


predict(NDRTAvatarGLM, newdata = data.frame(Study = c("5","6")))
1-pchisq(deviance(NDRTAvatarGLM), df.residual(NDRTAvatarGLM)) 

NDRTAvatarGLM2 <- glm(data = AvatarData, trialResp.corr ~ Study * trials_3.thisTrialN, family = "binomial")
summary(AvatarGLM2)

AIC(NDRTAvatarGLM, NDRTAvatarGLM2)

```




#Confidence

```{r}
FullConfAOV <- aov(data = FullWHN, conf_slider.response ~ Block * Study)

summary(FullConfAOV)

FullConfAOV2 <- aov(data = FullWHN, conf_slider.response ~ Study * Block)
summary(FullConfAOV2)

TukeyHSD(FullConfAOV)


ConfLM<- lm(data = FullWHN, formula = conf_slider.response~ Study*Block)
summary(ConfLM)

```


```{r}
print("Control")

ControlANOVAConf <- aov(data = ControlData, formula = conf_slider.response ~ Study)
summary(ControlANOVAConf)

print("Visual")

VisualANOVAConf <- aov(data = VisualData, formula = conf_slider.response ~ Study)
summary(VisualANOVAConf)
print("Avatar")

AvatarANOVAConf <- aov(data = AvatarData, formula = conf_slider.response ~ Study)
summary(AvatarANOVAConf)
print("Social")

SocialANOVAConf <- aov(data = SocialData, formula = conf_slider.response ~ Study)
summary(SocialANOVAConf)

print("NDRTVisual")
NDRTVisualANOVAConf <- aov(data = NDRTVisualData, formula = conf_slider.response ~ Study)
summary(NDRTVisualANOVAConf)
print("NDRTAvatar")

NDRTAvatarANOVAConf <- aov(data = NDRTAvatarData, formula = conf_slider.response ~ Study)
summary(NDRTAvatarANOVAConf)
print("NDRTSocial")

NDRTSocialANOVAConf <- aov(data = NDRTSocialData, formula = conf_slider.response ~ Study)
summary(NDRTSocialANOVAConf)
```
#Conf GLMS
```{r}

print("***************Control - Control 2***************")
ControlConfGLM <- lmer(data = ControlData, conf_slider.response ~ Study + (1|participant))
ControlConfGLM2 <- lmer(data = ControlData, conf_slider.response ~ Study + (1|participant) + (1|image_file))
summary(ControlConfGLM2)

anova(ControlConfGLM, ControlConfGLM2)


print("***************Avatar - Avatar Cue***************")
AvatarConfGLM <- lm(data = AvatarData, conf_slider.response ~ Study, family = "poisson")
summary(AvatarConfGLM)

print("***************Visual - Visual Cue***************")
VisualConfGLM <- lm(data = VisualData, conf_slider.response ~ Study, family = "poisson")
summary(VisualConfGLM)

viscondresults <- report(VisualConfGLM)
summary(viscondresults)


print("***************Avatar - Social Cue***************")
SocialConfGLM <- lm(data = SocialData, conf_slider.response ~ Study, family = "poisson")
summary(SocialConfGLM)


print("***************NDRT - Visual Cue***************")
NDRTVisualConfGLM <-  lm(data = NDRTVisualData, conf_slider.response ~ Study, family = "poisson")
summary(NDRTVisualConfGLM)

visndrtcondresults <- report(NDRTVisualConfGLM)
summary(visndrtcondresults)


print("***************NDRT - Avatar Cue***************")
NDRTAvatarConfGLM <-  lm(data = NDRTAvatarData, conf_slider.response ~ Study, family = "poisson")
summary(NDRTAvatarConfGLM)
print("***************NDRT - Social Cue***************")
NDRTSocialConfGLM <-  lm(data = NDRTSocialData, conf_slider.response ~ Study, family = "poisson")
summary(NDRTSocialConfGLM)


```

#Conf GLMER
```{r}


FullWHN$Block <- relevel(FullWHN$Block, ref = "Control - 2")

FullWHN$ConfPercent <- FullWHN$conf_slider.response * 100


ConfModel1 <- glmer(data = FullWHN, formula = conf_slider.response ~  Block  + (1 |participant),  family = binomial, glmerControl( optimizer = "bobyqa"))
summary(ConfModel1)

fixef(ConfModel1)
ranef(ConfModelBasic)

ConfModelBasic <- glmer(data = FullWHN, formula = conf_slider.response ~  Block * Study + (1 |participant) + (1|image_file) , family = binomial, glmerControl( optimizer = "bobyqa"))
summary(ConfModelBasic)



ConfResults <- report(ConfModelBasic, CI = 95)

summary(ConfResults)








```


#Subjective Attention

```{r}

AttentionDataset <- FullWHN %>% 
  subset(!is.na(Attention_slider.response))


AttAOV <- aov(data = AttentionDataset,formula =  Attention_slider.response ~ Block * Study)
summary(AttAOV)
TukeyHSD(AttAOV)

```




```{r}
print("Control")

ControlANOVAAtt <- aov(data = ControlData, formula = Attention_slider.response ~ Study)
summary(ControlANOVAAtt)

print("Visual")

VisualANOVAAtt <- aov(data = VisualData, formula = Attention_slider.response ~ Study)
summary(VisualANOVAAtt)
print("Avatar")

AvatarANOVAAtt <- aov(data = AvatarData, formula = Attention_slider.response ~ Study)
summary(AvatarANOVAAtt)
print("Social")

SocialANOVAAtt <- aov(data = SocialData, formula = Attention_slider.response ~ Study)
summary(SocialANOVAAtt)

print("NDRTVisual")
NDRTVisualANOVAAtt <- aov(data = NDRTVisualData, formula = Attention_slider.response ~ Study)
summary(NDRTVisualANOVAAtt)
print("NDRTAvatar")

NDRTAvatarANOVAAtt <- aov(data = NDRTAvatarData, formula = Attention_slider.response ~ Study)
summary(NDRTAvatarANOVAAtt)
print("NDRTSocial")

NDRTSocialANOVAAtt <- aov(data = NDRTSocialData, formula = Attention_slider.response ~ Study)
summary(NDRTSocialANOVAAtt)
```

#NASATLX
```{r}
Study5TLX <-  read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 5/Study5Data/S5TLX.csv")
Study5TLX$Study <- 5


Study6TLX<-  read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 6/Study6Data/S6TLX.csv")
Study6TLX$Study <- 6

FullTLXData<- rbind(Study5TLX, Study6TLX)

FullTLXData$Block <- as.factor(FullTLXData$Block)
FullTLXData$Study <- as.factor(FullTLXData$Study)
FullTLXData$participant <- as.factor(FullTLXData$participant)




```

```{r}
#detach(package:plyr)
TLXdataTotalSum <- FullTLXData %>% 
  group_by(Block) %>% 
  summarise(
    n = n(),
    mean = mean(Total, na.rm = T),
    sd = sd(Total)
  )
```


```{r}
TLXdataSumm <- FullTLXData %>% 
  
  group_by(Block) %>% 
  summarise(
    n = n(),
    Total_mean = mean(Total),
    Total_sd = sd(Total),
    Mental_mean = mean(MentalDemand, na.rm = T),
    Mental_sd = sd(MentalDemand, na.rm = T),
    Physical_mean = mean(Frustration, na.rm = T),
    Physical_sd = sd(Frustration, na.rm = T),
    Temporal_mean = mean(TemporalDemand, na.rm = T),
    Temporal_sd = sd(TemporalDemand, na.rm = T),
    Performance_mean = mean(Performance, na.rm = T),
    Performance_sd = sd(Performance, na.rm = T),
    Frustration_mean = mean(Frustration, na.rm = T),
    Frustration_sd = sd(Frustration, na.rm = T),
    Effort_mean = mean(Effort, na.rm = T),
    Effort_sd = sd(Effort, na.rm = T)
    
  )


FullTLX <- ggplot(FullTLXData, aes(Block, Total, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  labs(title = "Total NASA TLX scores")+

  theme_classic()+
        theme(plot.title=element_text(vjust=7))+
  theme(text=element_text(size = 25))+

    theme(plot.margin =unit(c(1.5,0,0,0),"cm"))
FullTLX

ggplot(data = FullTLXData, aes(x = Block, y = Total, fill = Block))+
  stat_summary()
  
```


```{r}
ggplot(FullTLXData, aes(Block, MentalDemand, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim(0,100)+
  labs(title = "Mental Demand")

ggplot(FullTLXData, aes(Block, PhysicalDemand, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim(0,100)+
    labs(title = "Physical Demand")

ggplot(FullTLXData, aes(Block, TemporalDemand, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim(0,100)+
    labs(title = "Temporal Demand")

ggplot(FullTLXData, aes(Block,OverallPerformance, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim (0,100)+
    labs(title = "Overall Performance")

ggplot(FullTLXData, aes(Block, Effort, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim (0,100)+
    labs(title = "Effort")
  
ggplot(FullTLXData, aes(Block, Frustration, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim (0,100)+
    labs(title = "Frustration")


```


```{r With ANOVA total}
library(rstatix)
  TLX.aov <- anova_test(data = FullTLXData, dv = Total, wid = participant, between = Study)

get_anova_table(TLX.aov)

TLXpwc <- FullTLXData %>% 
  pairwise_t_test(Total ~ Block, paired = TRUE,
                  p.adjust.method = "bonferroni")

TLXpwc <- TLXpwc %>%  add_xy_position(x = "Block")
TLXpwc


TLXbxp <- ggboxplot(FullTLXData, x = "Block", y = "Total", add = "point")

TLXbxp + 
  stat_pvalue_manual(TLXpwc) +
  labs(
    subtitle = get_test_label(TLX.aov, detailed = TRUE),
    caption = get_pwc_label(TLXpwc)
  )

```
#RoSAS
```{r}
Study5RoSAS <-  read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 6/ComparisonData/S5RoSAS.csv")
Study5RoSAS$Study <- 5


Study6RoSAS <-  read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 6/ComparisonData/S6RoSAS.csv")
Study6RoSAS$Study <- 6


FullRoSAS <- rbind(Study5RoSAS, Study6RoSAS)
```

```{r}



RoSASShortSummary <- FullRoSAS %>% 
  group_by(Block) %>% 
  summarise(n = n(),
            Warmth = mean(Warmth),
            Competence = mean(Competence),
            Discomfort = mean(Discomfort))


RosasFullSummary <- FullRoSAS %>% 
  group_by(Block) %>% 
  summarise(n = n(),
            Happy = mean(Happy),
            Feeling = mean(Feeling),
            Social = mean(Social),
            Organic = mean(Organic),
            Compassionate = mean(Compassionate),
            Emotional = mean(Emotional),
            Capable = mean(Capable),
            Responsive = mean(Responsive),
            Interactive = mean(Interactive),
            Reliable = mean(Reliable),
            Competent = mean(Competent),
            Knowledgeable = mean(Knowledgeable),
            Scary = mean(Scary),
            Strange = mean(Strange),
            Awkward = mean(Awkward),
            Dangerous = mean(Dangerous),
            Awful = mean(Awful),
            Aggressive = mean(Aggressive))


```

`
```{r}

RoSASANOVA <- aov(data = FullRoSAS, formula = Happy ~  Block)
summary(RoSASANOVA)
TukeyHSD(RoSASANOVA)

```


```{r}


#library(ggpubfigs)
ggplot(FullRoSAS, aes(Block, Warmth, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  labs(title = "Warmth")+
#    scale_fill_manual(values = friendly_pal("ito_seven"))
        theme_classic()

ggplot(FullRoSAS, aes(Block, Competence, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  labs(title = "Competence")+
#    scale_fill_manual(values = friendly_pal("ito_seven"))
        theme_classic()

ggplot(FullRoSAS, aes(Block, Discomfort, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  labs(title = "Discomfort")+
#    scale_fill_manual(values = friendly_pal("ito_seven"))
        theme_classic()


```

#NDRT Performance

```{r}
Study5NDRT <-  read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 6/ComparisonData/S5NDRT.csv")
Study5NDRT$Study <- 5


Study6NDRT <-  read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 6/ComparisonData/S6NDRT.csv")
Study6NDRT$Study <- 6

FullNDRT <- rbind(Study5NDRT, Study6NDRT)

```

```{r}

FullNDRTSummary <- FullNDRT %>% 
    group_by(Condition, Study) %>% 
  summarise(mean = mean(AverageProportion, na.rm = T),
            sd = sd(AverageProportion, na.rm = T),
            meanDiamond = mean(Diamond, na.rm = T),
            sdDiamond = sd(Diamond, na.rm=T),
            meanEmerald = mean(Emerald,na.rm=T),
            sdEmerald = sd(Emerald, na.rm = T))


```
```{r}
ggplot(FullNDRTSummary, aes(x = Condition, y = mean, fill = Condition))+
  geom_col()+
  geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, 
                position = position_dodge(0.9))
```
```{r}
scoreAnova <- aov(AverageProportion ~ Condition, data = FullNDRT)
summary(scoreAnova)

diaAnova <- aov(Diamond ~ Condition, data = FullNDRT)
summary(diaAnova)
TukeyHSD(diaAnova)

emeAnova <- aov(Emerald ~ Condition, data = FullNDRT)
summary(emeAnova)
TukeyHSD(emeAnova)

```

