---
title: "EyeTrackingTimeStudy3"
author: "TGoodge"
date: '2023-07-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(stringr)
library(tidyr)
library(dplyr)
library(stringr)
```

```{r}
#read in the data
dataFolder = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 3/data/EyeTracking"

setwd = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study3/data/EyeTracking"
#list.files(path = dataFolder)

#Create a list of all the datafiles in the folder, and then convert to a list object - needs full names for the file path
file_list <- list.files(path = dataFolder, pattern = ".csv$", all.files = TRUE, full.names = TRUE, recursive = TRUE)

rawETdata = data.frame()


#Loop through the datafiles in file_list, assign them a name and then read them in
for(i in 1:length(file_list))
{
  filename <- file_list[i]
  #print(filename)
  tempData <- read.csv(filename)
  pptInfo <- strsplit(filename, split = '-', fixed = TRUE)
  tempData$Participant <- pptInfo[[1]][4]
  tempData$Condition <- pptInfo[[1]][5]
  tempData$Date <- pptInfo[[1]][2]
  tempData$Time <- pptInfo[[1]][3]
 #assign(paste(substr(file_list[i],24,27)), read.csv(paste0(file_list[i])))

  rawETdata <- rbind(rawETdata, tempData)
}
```


```{r}

timeData <- rawETdata %>% 
  select(Participant, Condition, Date, Time)

timeData$Condition <- gsub(pattern = ".csv", replacement = "", x = timeData$Condition)
timeData$Condition <- str_sub(timeData$Condition, 4,-1)
timeData$Date <-    str_sub(timeData$Date,-5,-1)
timeData$Date <- gsub(pattern = "_", replacement = "/", x = timeData$Date)
timeData$Time <- gsub(pattern = "_", replacement = ":", x = timeData$Time)

timeETData <- timeData[!duplicated(timeData), ]
timeETData$Condition[timeETData$Condition == "Control"] <- "Baseline"

timeETData$Sort <- paste(timeETData$Participant, timeETData$Condition)


```

```{r}
dataFolder = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 3/data/Psychopy"

file_list <- list.files(path = dataFolder, pattern = "..csv$", all.files = TRUE, full.names = TRUE, recursive = TRUE) 
```

```{r}
RawWHNDataset <- data.frame()
#loop through all the fills, create a temporary container, remove the first, second and last rows and then add 1 to the trials counter. Then bind it to the dataset
for (file in file_list){
  tempData <- read.csv(file, header = T)  
    
  RawWHNDataset <- bind_rows(RawWHNDataset, tempData)
}
```


```{r}
SortedWHNDataset <- RawWHNDataset %>% 
  select(participant, trials_3.thisTrialN, date, hazard_video.started, trialResp.started)


```

```{r}
Counterbalancing <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 3/Study3Counterbalancing.csv", header = T)

Counterbalancing <- Counterbalancing%>%  select(participant, Second, Third, Fourth, Fifth)

Counterbalancing <- na.omit(Counterbalancing)
```


```{r}

OrderWHNDataset <- left_join(SortedWHNDataset, Counterbalancing, by = 'participant') 
OrderWHNDataset$Block <- 'Baseline' 


OrderWHNDataset$Block <-  if_else(OrderWHNDataset$trials_3.thisTrialN >= 32, OrderWHNDataset$Fifth, 
                                  if_else(OrderWHNDataset$trials_3.thisTrialN >= 24, OrderWHNDataset$Fourth,
                                          if_else(OrderWHNDataset$trials_3.thisTrialN >= 16, OrderWHNDataset$Third,
                                                  if_else(OrderWHNDataset$trials_3.thisTrialN >= 8, OrderWHNDataset$Second, 
                                                          'Baseline'))))
```



```{r}
timeWHNData <- OrderWHNDataset
timeWHNData <-  rename(timeWHNData,trialNumber = trials_3.thisTrialN) 
timeWHNData <-  rename(timeWHNData,DateFull = date)
timeWHNData <-  rename(timeWHNData,ClipStart = hazard_video.started) 
timeWHNData <-  rename(timeWHNData,ClipStop = trialResp.started)

timeWHNData[c('DateWHN', 'TimeWHN')] <- str_split_fixed(timeWHNData$Date, '_', 2)

timeWHNData <- timeWHNData %>% 
  select(participant, trialNumber, ClipStart, ClipStop, Block, DateWHN, TimeWHN)

timeWHNData$TimeWHN <- gsub(pattern = "h", replacement = ":", x = timeWHNData$TimeWHN)

timeWHNData$TimeWHN <- gsub(pattern = "\\.", replacement = ":", x = timeWHNData$TimeWHN)


timeWHNData$Sort <- paste(timeWHNData$participant, timeWHNData$Block)

```

```{r}
timeData <- left_join(timeWHNData, timeETData, by = "Sort")

timeData$TimeWHN <-  str_sub(timeData$TimeWHN, end = -5)


timeData$TimeWHNFormat <- strptime(timeData$TimeWHN,format="%H:%M:%S")
timeData$TimeFormat <- strptime(timeData$Time,format="%H:%M:%S")
timeData$RecordingStart <- as.numeric(difftime(timeData$TimeFormat,timeData$TimeWHNFormat, units = "secs"))

timeData$ETClipStart = timeData$ClipStart - timeData$RecordingStart
timeData$ETClipStop = timeData$ClipStop - timeData$RecordingStart


```


```{r}
timeDataExport <- timeData %>% 
  select(Participant, trialNumber, Sort, Condition, ClipStart, ClipStop, RecordingStart, ETClipStart, ETClipStop)


timeDataExport$RecordingStart <- as.numeric(timeDataExport$RecordingStart)

timeDataExport$ETClipStart <- as.numeric(timeDataExport$ETClipStart)

timeDataExport$ETClipStop <- as.numeric(timeDataExport$ETClipStop)
```


```{r}

write.csv(timeDataExport, "timeDataExport2.csv")
```


