---
title: "Study3WHNAnalysis"
author: "TGoodge"
date: '2023-03-24'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(splitstackshape)
library(stringr)
library(data.table)
library(dplyr)
library(tidyr)
library(gridExtra)
library(lme4)
library(lmerTest)
library(afex)
library(effects)
library(ggplot2)
library(ggthemes)
library(report)
library(janitor)

library(RColorBrewer)
#library(ggpubfigs)

```

####Data Wrangling

```{r read in datafiles}
dataFolder = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 3/data/Psychopy"

file_list <- list.files(path = dataFolder, pattern = "..csv$", all.files = TRUE, full.names = TRUE, recursive = TRUE) 
```

```{r bind data files together}
RawWHNDataset <- data.frame()
#loop through all the fills, create a temporary container, remove the first, second and last rows and then add 1 to the trials counter. Then bind it to the dataset
for (file in file_list){
  tempData <- read.csv(file, header = T)  
    
  RawWHNDataset <- bind_rows(RawWHNDataset, tempData)
}

```

```{r sort dataset}
SortedWHNDataset <- RawWHNDataset %>% 
  select(participant,image_file,Correct,trials_3.thisTrialN, conf_slider.response, conf_slider.rt, MiseryScale.response, Attention_slider.response, trialResp.keys, trialResp.corr, trialResp.rt)

SortedWHNDataset$Attention_slider.response <- as.numeric(SortedWHNDataset$Attention_slider.response)

SortedWHNDataset$trialResp.rt <-stringr::str_remove_all(SortedWHNDataset$trialResp.rt,"[\\[\\]]")

SortedWHNDataset$trialResp.rt <- as.numeric(SortedWHNDataset$trialResp.rt)
```

```{r read in counterbalancing info }
Counterbalancing <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 3/Study3Counterbalancing.csv", header = T)

Counterbalancing <- Counterbalancing%>%  select(participant, Second, Third, Fourth, Fifth)

Counterbalancing <- na.omit(Counterbalancing)
```


```{r read in and organise demographic information}
DemogDataRaw <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 3/data/Qualtrics/Demogs/Study3Demogs.csv") %>%  
    select(starts_with('Q')) 

#Change the first row into column headers
DemogDataOrg <- row_to_names(DemogDataRaw, row_number = 1)
#Remove consent form columns
DemogDataOrg <- DemogDataOrg[-1,-c(1:7)]
DemogDataOrg <- DemogDataOrg[1:9]

DemogDataOrg <- DemogDataOrg %>% 
  rename(participant = `Enter your Participant ID:`) %>% 
  rename(Age = `What is your age?`) %>% 
  rename(Gender = `Which gender do you identify with?`) %>% 
  rename(UKLicense = `Do you have a UK driving license?`) %>%
  rename(CountryLicense = `Which country did you get your driving license in?`) %>%
  rename(YearsExp = `How many years driving experience do you have, either from when you passed your driving test or when you started driving regularly? - (years/months)`) %>%
  rename(UKYearsExp = `How many years driving experience do you have driving in the UK? (years, months)`) %>%
   rename(GlasgowYearsExp = `How many years driving experience do you have driving around the West End of Glasgow? (years, months)`) 


DemogDataOrg$Age = as.numeric(DemogDataOrg$Age)

DemogDataOrg$YearsExp = as.numeric(DemogDataOrg$YearsExp)

DemogDataOrg$UKYearsExp = as.numeric(DemogDataOrg$UKYearsExp)
DemogDataOrg$GlasgowYearsExp = as.numeric(DemogDataOrg$GlasgowYearsExp)

DemogDataOrg$Gender[DemogDataOrg$Gender == 'Woman'] <- 'Female'
DemogDataOrg$Gender[DemogDataOrg$Gender == 'Female '] <- 'Female'
DemogDataOrg$Gender[DemogDataOrg$Gender == 'Male '] <- 'Male'
```



```{r remove extra participants from demogs}
DemogDataOrg <- DemogDataOrg %>%
#subset(image_file != "Slide24") %>%
  subset(participant != "P03") %>%
  subset(participant != "P04") %>%
  subset(participant != "P15") %>%
  subset(participant != "P16") %>%
  subset(participant != "P24") %>%
   subset(participant != "P01") %>%
   subset(participant != "P02")# %>%
#   #  subset(participant != "P30") %>% 
#   # subset(participant != "P31")



```

```{r demographic summary}
DemogSummaryTotal <- DemogDataOrg %>% 
  
  summarise(
  n = n(),
  AgeMean = mean(Age),
  AgeSD = sd(Age),
  Male = sum(Gender == 'Male'),
  Female = sum(Gender == "Female"),
  UKLicense = sum(UKLicense == "Yes"),
  YearsExp = mean(YearsExp),
  sdYearsExp = sd(DemogDataOrg$YearsExp, na.rm = T),
  UKExp = mean(UKYearsExp, na.rm = T),
  sdUKExp = sd(DemogDataOrg$UKYearsExp, na.rm = T),
  GlasgowDriving = sum(GlasgowYearsExp != 0.00),
  GlasgowExp = mean(GlasgowYearsExp),
  sdGlasgowExp = sd(DemogDataOrg$GlasgowYearsExp, na.rm = T)

  

  )  
```


```{r}
#Remove extra participants
# WHN1stDataset <- WHNDataset %>% 
#   subset(participant != "P25") %>% 
#   subset(participant != "P31") 

```

```{r join counterbalancing information into main dataframe}
OrderWHNDataset <- left_join(SortedWHNDataset, Counterbalancing, by = 'participant') 
OrderWHNDataset$Block <- 'Baseline' 


OrderWHNDataset$Block <-  if_else(OrderWHNDataset$trials_3.thisTrialN >= 32, OrderWHNDataset$Fifth, 
                                  if_else(OrderWHNDataset$trials_3.thisTrialN >= 24, OrderWHNDataset$Fourth,
                                          if_else(OrderWHNDataset$trials_3.thisTrialN >= 16, OrderWHNDataset$Third,
                                                  if_else(OrderWHNDataset$trials_3.thisTrialN >= 8, OrderWHNDataset$Second, 
                                                          'Baseline'))))
```


```{r remove NA and join demographic information. Create main dataset}
WHNDataset <- OrderWHNDataset
WHNDataset <- WHNDataset[!is.na(WHNDataset$Correct),]

WHNDataset <- left_join(WHNDataset, DemogDataOrg, by = "participant")
```


```{r rename values and make Block a factor}
WHNDataset$participant <- as.factor(WHNDataset$participant)

WHNDataset$image_file[WHNDataset$image_file == "Slide1"] <- "Slide01"
WHNDataset$image_file[WHNDataset$image_file == "Slide2"] <- "Slide02"
WHNDataset$image_file[WHNDataset$image_file == "Slide3"] <- "Slide03"
WHNDataset$image_file[WHNDataset$image_file == "Slide4"] <- "Slide04"
WHNDataset$image_file[WHNDataset$image_file == "Slide5"] <- "Slide05"
WHNDataset$image_file[WHNDataset$image_file == "Slide6"] <- "Slide06"
WHNDataset$image_file[WHNDataset$image_file == "Slide7"] <- "Slide07"
WHNDataset$image_file[WHNDataset$image_file == "Slide8"] <- "Slide08"
WHNDataset$image_file[WHNDataset$image_file == "Slide9"] <- "Slide09"

WHNDataset$Block[WHNDataset$Block == "GemsBasic"] <- "HUD - AR"
WHNDataset$Block[WHNDataset$Block == "GemsCued"] <- "HUD - Cued AR"
WHNDataset$Block[WHNDataset$Block == "GemsTablet"] <- "HDD - AR"
WHNDataset$Block[WHNDataset$Block == "Tablet"] <- "HDD - Tablet"


WHNDataset$Block <- factor(WHNDataset$Block, levels = c("Baseline", "HUD - AR","HUD - Cued AR", "HDD - AR", "HDD - Tablet"))
```

```{r change UK license answer and factorise}
WHNDataset$UKLicense[WHNDataset$UKLicense == "I have a license from another country"] <- "No"
WHNDataset$UKLicense <- as.factor(WHNDataset$UKLicense)
```

```{r remove bad participants from main dataset}

WHNDataset <- WHNDataset %>%
#subset(image_file != "Slide24") %>%
 subset(participant != "P01") %>%
 subset(participant != "P02") %>%
  subset(participant != "P03") %>%
  subset(participant != "P04") %>%
  subset(participant != "P15") %>%
  subset(participant != "P16") %>%
  subset(participant != "P24") #%>%
#   #subset(participant != "P30") %>% 
#  # subset(participant != "P31")



FullNoPpts <- n_distinct(WHNDataset$participant)

```

```{r}
#Remove extra participants
# WHN1stDataset <- WHNDataset %>% 
#   subset(participant != "P25") %>% 
#   subset(participant != "P31") 
# 
# WHN2ndDataset <- WHNDataset %>% 
#   subset(participant != "P01") %>% 
#   subset(participant != "P02")

NoPpts <- n_distinct(WHNDataset$participant)

```

```{r summarise main WHN dataset}
WHNSummary <- WHNDataset %>% 
  group_by(Block) %>% 
  summarise(n = n()/FullNoPpts,
            WHN = sum(trialResp.corr) / FullNoPpts,
            WHNPercent = sum((trialResp.corr / FullNoPpts) /8) * 100,
            sdWHN = sd(trialResp.corr),
            sdWHNPercent =  ((sdWHN/FullNoPpts)/8) * 100,
            seWHN = (sd(trialResp.corr))/ sqrt(FullNoPpts),
            meanConf = mean(conf_slider.response),
            sdConf = sd(conf_slider.response),
            seConf = (sd(conf_slider.response))/ sqrt(FullNoPpts),
            meanMISC = mean(MiseryScale.response),
            sdMISC = sd(MiseryScale.response),
            seMISC = (sd(MiseryScale.response))/ sqrt(FullNoPpts),
            meanAttention = mean(Attention_slider.response, na.rm = T),
            sdAttention = sd(Attention_slider.response, na.rm=T),
            seAttention = (sd(Attention_slider.response, na.rm=T))/ sqrt(FullNoPpts),
            trialRespmean = mean(trialResp.rt, na.rm=T),
            trialRespSD = sd(trialResp.rt, na.rm=T)
            )

CorrConfSummary <- WHNDataset %>% 
  group_by(Block, trialResp.corr) %>% 
  summarise(n = n(),
            conf = mean(conf_slider.response),
                        WHNPercent = sum((trialResp.corr / NoPpts) /10) * 100,
)

```

```{r Create dataset with Cue as intercept}
WHNCuedDataset <- WHNDataset# %>% 
 # subset(Block != "Baseline")


WHNCuedDataset$Block <- factor(WHNCuedDataset$Block, levels = c("HUD - Cued AR","Baseline", "HUD - AR", "HDD - AR", "HDD - Tablet"))

```

```{r Create dataset with HUD as intercept}
WHNHUDDataset <- WHNDataset# %>% 
 # subset(Block != "Baseline")


WHNHUDDataset$Block <- factor(WHNHUDDataset$Block, levels = c("HUD - AR","Baseline", "HUD - Cued AR", "HDD - AR", "HDD - Tablet"))

```

```{r Create dataset with HDD as intercept}
WHNHDDDataset <- WHNDataset# %>% 
 # subset(Block != "Baseline")


WHNHDDDataset$Block <- factor(WHNHUDDataset$Block, levels = c("HDD - AR", "HUD - AR","Baseline", "HUD - Cued AR",  "HDD - Tablet"))

```

```{r Create dataset with Tablet as Intercept}
WHNTabletDataset <- WHNDataset# %>% 
 # subset(Block != "Baseline")


WHNTabletDataset$Block <- factor(WHNHUDDataset$Block, levels = c("HDD - Tablet","HDD - AR", "HUD - AR","Baseline", "HUD - Cued AR"))
```

```{r summarise responses to each of the clips, and each clip by block}

ClipSummary <- WHNDataset %>% 
  group_by(image_file) %>% 
  summarise(n = n(),
            WHN = sum(trialResp.corr),
            sdWHN = sd(trialResp.corr))


ClipBlockSummary <- WHNDataset %>% 
  group_by(image_file, Block) %>% 
  summarise(n = n(),
            WHNCorr = sum(trialResp.corr),
            WHNIncorr = n() - sum(trialResp.corr),
            RatioCorr = WHNCorr / n() * 100,
            sdWHN = sd(trialResp.corr))

ClipConfSummary <- WHNDataset %>% 
  subset(Block == "Baseline") %>% 
  group_by(image_file) %>% 
  summarise(n = n(),
            WHNCorr = sum(trialResp.corr),
            WHNIncorr = n() - sum(trialResp.corr),
            RatioCorr = WHNCorr / n() * 100,
            conf = mean(conf_slider.response),
            sdWHN = sd(trialResp.corr))




```

```{r plot responses to each clip}
ggplot(data = ClipSummary, aes(x = image_file, y = WHN, fill = image_file))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 90))+
  labs(xlim(0,NoPpts))+
  geom_hline(yintercept = NoPpts)+
    geom_hline(yintercept = NoPpts / 4)

ggplot(data = WHNDataset, aes(x = image_file, y = conf_slider.response, fill = image_file))+
  geom_boxplot()+
  theme(axis.text.x = element_text(angle = 90))+
  labs(xlim(0,1))


WHNBaselineDataset <- WHNDataset %>% 
  subset((Block == "Baseline")) 

ggplot(data = WHNBaselineDataset)+
  geom_col(aes(x = image_file, y = trialResp.corr, fill = image_file))+
  #geom_boxplot(aes(x = image_file, y = conf_slider.response * 100, fill = image_file))+
  theme(axis.text.x = element_text(angle = 90))
```

```{r plot confidence responses}
#Confidence graph
ggplot(data = WHNBaselineDataset)+
  geom_boxplot(aes(x = image_file, y = conf_slider.response, fill = image_file))+
  #geom_boxplot(aes(x = image_file, y = conf_slider.response * 100, fill = image_file))+
  theme(axis.text.x = element_text(angle = 90))+
  geom_hline(yintercept = 0.9, linetype = "dashed", colour = "blue")+
  geom_hline(yintercept = 0.25, linetype = "dashed", colour = "red")
```

```{r}
ggplot(data = ClipBlockSummary, aes(x = image_file, y = WHNCorr, fill = Block))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 90))+
  labs(xlim(0,NoPpts))+
  geom_hline(yintercept = NoPpts, colour = 'blue')+
  geom_hline(yintercept = NoPpts / 4, colour = 'red', linetype = 'dashed')

```

```{r plot correct answers for each clip per block}
ggplot(data = ClipBlockSummary, aes(x = image_file, y = WHNIncorr, fill = Block))+
  geom_col()+
  theme(axis.text.x = element_text(angle = 90))+
  labs(xlim(0,NoPpts))+
  geom_hline(yintercept = NoPpts, colour = 'blue')+
  geom_hline(yintercept = NoPpts / 4, colour = 'red', linetype = 'dashed')

```

```{r}
# Slide20 <- WHNDataset %>% 
#   subset (image_file == "Slide20")
```

```{r summarise attention data}
AttSum <- WHNDataset %>% 
  group_by(Block) %>% 
  summarise(n = NoPpts,
            mean = mean(Attention_slider.response, na.rm = T),
            sd = sd(Attention_slider.response, na.rm = T))
```

```{r}
write.csv(WHNDataset, "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 4/data/S3WHN.csv", row.names=FALSE)

```

###End of Data Wrangling####
###############WHN Scores##################

```{r }

#split into uk & non-UK drivers

WHNBaseline <- as.numeric(WHNSummary[1,3])

#ggplot(data = WHNDataset, aes(x = Block, y = trialResp.corr, fill = Block))+
#   geom_boxplot(trialResp.corr ~ Block)+
#   #geom_hline(yintercept = 8, linetype = "solid", size = 1.0)+
#   #geom_hline(yintercept = 2, linetype = "dotted", size = 1.0)+
#   labs(title = "Average Hazard Prediction Score", x = "NDRT Presentation Condition", y = "Average number of correct responses")+
#   ylim(0,100)+
#   scale_fill_hue(l = 40)
# 
# 
# boxplot(trialResp.corr ~Block, WHNDataset)
# 
# 
# barplot(table(WHNDataset$trialResp.corr))

```
```{r Main Plot of WHN Scores}
WHNBaseline <- as.numeric(WHNSummary[1,3])

WHNPlot <- ggplot(data = WHNSummary, aes(x = Block, y = WHN, fill = Block))+
  geom_col(colour = "black")+
  geom_errorbar(aes(ymin = WHN - sdWHN, ymax = WHN + sdWHN),
                width = 0.2, 
                position = position_dodge(0.9))+
  geom_hline(yintercept = WHNBaseline, linetype = "dashed", size = 0.5)+
  #geom_hline(yintercept = 8, linetype = "solid", size = 1.0)+
  #geom_hline(yintercept = 2, linetype = "dotted", size = 1.0)+
  labs(title = "Average Hazard Prediction Score", x = "NDRT Presentation Condition", y = "Average number of correct responses")+
  ylim(0,8)#+
 #   scale_fill_manual(values = friendly_pal("ito_seven"))+

              
  theme(legend.position="none")



WHNPlot

```

```{r}
ggplot(data = WHNDataset, aes(x = Block, y = trialResp.corr, fill = Block))+
  stat_summary()
```

```{r}
PlotData <- WHNDataset %>% 
  select(participant, trialResp.corr, trials_3.thisTrialN, Block) %>%   group_by(participant, Block) %>% 
  summarise(participant = participant,
            score = sum(trialResp.corr),
            Block = Block)


PlotData <- PlotData[!duplicated(PlotData),]

Plot1 <- ggplot(data = PlotData, aes(x = Block, y = score, fill = Block))+
  geom_violin(alpha = 0.8)+
  geom_boxplot(alpha = 0, width = 0.2)+
  scale_fill_manual(values = friendly_pal("ito_seven"))+
    theme_classic()+
theme(legend.position="none") +theme(text=element_text(size = 20)) +

  theme(axis.text=element_text(size=15))+
  labs(title = "Hazard Prediction Score", x = "NDRT Presentation Condition", y = "Average correct responses")+
    theme(plot.title=element_text(vjust=11.5))+

  theme(plot.margin =unit(c(2,0,0,0),"cm"))



Plot1

  
```
```{r}
ggplot(data = PlotData, aes(x = Block, y = score, fill = Block))+
  geom_violin(alpha = 0.8)+
  geom_boxplot(alpha = 0, width = 0.2)+
    theme_classic()+
  xlab("NDRT Presentation Condition")+
  ylab("Average Study 3 WHN Score")
```


```{r WHN ANOVA}
WHNANOVA <- aov(trialResp.corr ~ Block , data = WHNDataset)

summary(WHNANOVA)

TukeyHSD(WHNANOVA)

library(emmeans)

e1_anova <- aov_ez(
  id = "participant", 
  dv = "trialResp.corr", 
  data = WHNDataset,
  within = "Block"
)

e1_anova
emmeans(e1_anova, "Block")


```

#######CONFIDENCE SCORES##############
```{r Main COnf Plot}
ConfBaseline <- as.numeric(WHNSummary[1,7])


ConfPlot <- ggplot(data = WHNDataset, aes(x = Block, y = conf_slider.response, fill = Block))+
  geom_violin(alpha = 0.8) + geom_boxplot(alpha=0.2, width = 0.2)+
  labs(title = "Average Confidence Score", y = "Mean Confidence Rating", x = "", key= FALSE)+
  ylim(0,1.0)+
   # scale_fill_manual(values = friendly_pal("ito_seven"))+
  theme_classic()+
  theme(legend.position="none")+
  theme(text=element_text(size = 15)) +
  theme(axis.text=element_text(size=10))+
  theme(plot.title=element_text(vjust=14))+

  theme(plot.margin =unit(c(2,0,0,0),"cm"))


ConfPlot

```

```{r Conf ANOVA}
ConfANOVA <- aov(conf_slider.rt ~ Block , data = WHNDataset)

summary(ConfANOVA)

TukeyHSD(ConfANOVA)
```



###########MISC SCORES###########

```{r separate MISC data and plot}
MISCDataset <- WHNDataset %>%
  group_by(trials_3.thisTrialN, Block) %>%
  summarise(mean = mean(MiseryScale.response),
            sd = sd(MiseryScale.response)) 


ggplot(data = MISCDataset, aes(x = trials_3.thisTrialN, y = mean))+
  geom_line(aes(colour  = factor(Block)))+
  geom_point(aes(colour = Block))+
  geom_ribbon(aes(ymin =MISCDataset$mean - MISCDataset$sd, ymax = MISCDataset$mean + MISCDataset$sd, fill = Block),alpha= 0.0) +  
  labs(title = "MISC Score")
```


```{r create different  dataframes for each condition for MISC}
MISCARDataset <- MISCDataset %>% 
  subset(Block != "HUD - Cued AR") %>% 
  subset(Block != "HDD - Tablet") %>% 
  subset(Block != "HDD - AR") 

MISCCueDataset <- MISCDataset %>% 
  subset(Block != "HUD - AR") %>% 
  subset(Block != "HDD - Tablet") %>% 
  subset(Block != "HDD - AR") 

MISCTabDataset <- MISCDataset %>% 
  subset(Block != "HUD - AR") %>% 
  subset(Block != "HUD - Cued AR") %>% 
  subset(Block != "HDD - AR") 

MISCGemTabDataset <- MISCDataset %>% 
  subset(Block != "HUD - AR") %>% 
  subset(Block != "HDD - Tablet") %>% 
  subset(Block != "HUD - Cued AR")
```


```{r plot each condition's MISC scores}
ggplot(data = MISCARDataset, aes(x = trials_3.thisTrialN, y = mean))+
  geom_line(aes(colour  = factor(Block)))+
  geom_point(aes(colour = Block))+
  geom_ribbon(aes(ymin =MISCARDataset$mean - MISCARDataset$sd, ymax = MISCARDataset$mean + MISCARDataset$sd, fill = Block),alpha= 0.2) +  
  geom_vline(xintercept = 8)+
  geom_vline(xintercept = 16)+
  geom_vline(xintercept = 24)+
  geom_vline(xintercept = 32)+
  labs(title = "MISC Score - AR HUD")+
  scale_x_continuous(breaks = seq(0, 40, 8))

ggplot(data = MISCCueDataset, aes(x = trials_3.thisTrialN, y = mean))+
  geom_line(aes(colour  = factor(Block)))+
  geom_point(aes(colour = Block))+
  geom_ribbon(aes(ymin =MISCCueDataset$mean - MISCCueDataset$sd, ymax = MISCCueDataset$mean + MISCCueDataset$sd, fill = Block),alpha= 0.2) +  
    geom_vline(xintercept = 8)+
  geom_vline(xintercept = 16)+
  geom_vline(xintercept = 24)+
  geom_vline(xintercept = 32)+
  labs(title = "MISC Score - Cued AR HUD")+
  scale_x_continuous(breaks = seq(0, 40, 8))


ggplot(data = MISCTabDataset, aes(x = trials_3.thisTrialN, y = mean))+
  geom_line(aes(colour  = factor(Block)))+
  geom_point(aes(colour = Block))+
  geom_ribbon(aes(ymin =MISCTabDataset$mean - MISCTabDataset$sd, ymax = MISCTabDataset$mean + MISCTabDataset$sd, fill = Block),alpha= 0.2) +  
    geom_vline(xintercept = 8)+
  geom_vline(xintercept = 16)+
  geom_vline(xintercept = 24)+
  geom_vline(xintercept = 32)+
  labs(title = "MISC Score - HDD - Tablet")+
  scale_x_continuous(breaks = seq(0, 40, 8))


ggplot(data = MISCGemTabDataset, aes(x = trials_3.thisTrialN, y = mean))+
  geom_line(aes(colour  = factor(Block)))+
  geom_point(aes(colour = Block))+
  geom_ribbon(aes(ymin =MISCGemTabDataset$mean - MISCGemTabDataset$sd, ymax = MISCGemTabDataset$mean + MISCGemTabDataset$sd, fill = Block),alpha= 0.2) +  
    geom_vline(xintercept = 8)+
  geom_vline(xintercept = 16)+
  geom_vline(xintercept = 24)+
  geom_vline(xintercept = 32)+
  labs(title = "MISC Score - HDD - AR")+
  scale_x_continuous(breaks = seq(0, 40, 8))

```

```{r MISC ANOVA}
MISCANOVA <- aov(MiseryScale.response ~ Block , data = WHNDataset)

summary(MISCANOVA)


TukeyHSD(MISCANOVA)

```

```{r plot main Attention data}
AttBaseline <- as.double(AttSum[1,3])

AttPlot <- ggplot(data = WHNDataset, aes(x = Block, y = Attention_slider.response, fill = Block))+
  geom_violin(alpha = 0.8)+
  geom_boxplot(alpha = 0.2, width = 0.2)+
 
  labs(title = "Subjective Attention Rating", y = "Mean Attention Rating", x = "NDRT Presentation Condition")+
   # scale_fill_manual(values = friendly_pal("ito_seven"))+
    theme_classic()+
  theme(legend.position="none")+
  theme(text=element_text(size = 15))+
  theme(plot.title=element_text(vjust=14))+
  theme(axis.text=element_text(size=10))+
  theme(plot.margin =unit(c(2,0,0,0),"cm"))

  AttPlot
  


```
```{r ATT ANOVA}
AttANOVA <- aov(Attention_slider.response ~ Block , data = WHNDataset)

summary(AttANOVA)

TukeyHSD(AttANOVA)
```


```{r group all graphs together}
library(cowplot)

subPlot<- plot_grid(ConfPlot, AttPlot, labels = c('b)','c)'),ncol = 1)

subPlot


legend_b <- get_legend(
  WHNPlot + 
    guides(color = guide_legend(nrow = 1)) +
   theme(legend.position = "bottom")
)

FullPlot <- plot_grid(Plot1, subPlot, labels = ('a)'))

FinalPlot <- plot_grid(FullPlot, legend_b, ncol = 1, rel_heights = c(1, .1))

FinalPlot

file1 <- tempfile("file1", fileext = ".png")

width = 1920

ggsave(filename = "FullPlot.png",
       plot = FinalPlot,
       scale = 3,
       device = png,
       width = 3840,
       units = "px",
       dpi = 700)

```


#################LMERs################

```{r Null WHN GLMER}
#Need to user glmer() as correct response is binomial

WHNNullModel0 <- glmer(data = WHNDataset, formula = trialResp.corr ~ 1 + (1|participant) + (1|image_file) , family = binomial, glmerControl( optimizer = "bobyqa"))

summary(WHNNullModel0)

deviance(WHNNullModel0)

```
#MAIN WHN GLMER
```{r Main WHN GLMER} 
# WHNModel0 <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1|participant) + (1|image_file) + (1|YearsExp) , family = binomial, glmerControl( optimizer = "bobyqa"))
# # 
# summary(WHNModel0)

WHNModelBasic <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1 |participant) + (1|image_file) , family = binomial, glmerControl(optimizer = "bobyqa"))

WHNModelPP <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1 |participant)  , family = binomial, glmerControl(optimizer = "bobyqa"))

WHNModel <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1|image_file) , family = binomial, glmerControl(optimizer = "bobyqa"), nAGQ = 15)

summary(WHNModel)

summary(WHNModelBasic)

anova(WHNModel, WHNModelBasic)

r.squaredGLMM(WHNModel, WHNNullModel0)


#WHNModelCorr <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1 |participant) + (1|image_file) + Block * conf_slider.response , family = binomial, glmerControl(optimizer = "bobyqa"))

#https://journals.sagepub.com/doi/full/10.1177/2515245920960351

WHNModel1 <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1 + Block|participant) + (1| image_file) , family = binomial, glmerControl( optimizer = "bobyqa"))

#WHNModel2 <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1 + Block|participant) + (1 + Block| image_file) , family = binomial, glmerControl( optimizer = "bobyqa"))

summary(WHNModel1)
summary(WHNModel2)

summary(WHNModelBasic)

#summary(WHNModelBy)

ranef((WHNModelBasic))

deviance(WHNModelBasic)

#anova(WHNModelBasic, WHNModelBy)

print(report(WHNModelCorr, CI = 95))

#anova(WHNModelBasic, WHNModel1)

print(report(WHNModelBasic, CI = 95))

#WHNModel2 <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1|participant) + (1 + Block|participant) + (1 + Block|image_file) , family = binomial, glmerControl( optimizer = "bobyqa"))
#summary(WHNModel2)

#WHNModel3 <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1|participant) + (1|image_file) + (1 + Block|participant) + (1 + Block|image_file) , family = binomial, glmerControl( optimizer = "bobyqa"))
#summary(WHNModel3)


#WHNModel4 <- glmer(data = WHNDataset, formula = trialResp.corr ~  Block + (1|participant) + (1|image_file) + (1 + Block|participant) + (1 + Block|image_file) + (1|YearsExp), family = binomial, glmerControl( optimizer = "bobyqa"))

#summary(WHNModel4)




anova(WHNModel1, WHNModel, WHNModelBasic, WHNModel2)


#https://link.springer.com/article/10.3758/s13428-016-0809-y


```

```{r calculate  r2} 

library(MuMIn)
r.squaredGLMM(WHNModel1, WHNNullModel0)

```

```{r afex WHN GLMER}

e1_mixed_v1 <- mixed(
  trialResp.corr ~ Block + (1|participant) + (1|image_file),
  data = WHNDataset,
  method = "LRT",
  family = binomial
)


```

```{r plot WHN GLMER model}
cc <- coef(summary(WHNModel))
cc <- cbind(cc,adjust.p=p.adjust(cc[,"Pr(>|z|)"],"holm"))
plot(WHNModelBasic, type=c("p","smooth"))

```

```{r DHARMa}
library(DHARMa)


testDispersion(WHNModel)

simulationOutput <- simulateResiduals(fittedModel = WHNModel, plot = F)

residuals(simulationOutput,quantileFunction = qnorm, outlierValues = c(-7,7))

plot(simulationOutput)

```

```{r}
#https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.12504
# library(simr)
# power<- powerSim(WHNModel1, nsim = 10)
# power
# 
# fixef(WHNModel1)
# 
# pc2 <- powerCurve(WHNModel1)
# 
# print(pc2)
# 

#sim2 <- powerSim(WHNModel1, fixed("Block"), seed = 2, nsim = 2, alpha = .05)
```


```{r}
#Compare the first and last two participants datasets to decide who to remove
# WHNModel1st = glmer(data = WHN1stDataset, formula = trialResp.corr ~ Block +  (1|participant) + (1|image_file) ,family = binomial)
# summary(WHNModel1st)
# 
# WHNModel2nd = glmer(data = WHN2ndDataset, formula = trialResp.corr ~ Block +  (1|participant) + (1|image_file) ,family = binomial)
# summary(WHNModel2nd)


#anova(WHNModel1st, WHNModel2nd)
```

```{r}
#Model including Main effect of UK driver license

# WHNModelYears = glmer(data = WHNDataset, formula = trialResp.corr ~ Block + YearsExp +(1|participant) + (1|image_file) ,  family = binomial)
# summary(WHNModelYears)
# 
# 
# WHNModelUK = glmer(data = WHNDataset, formula = trialResp.corr ~ Block + UKLicense +(1|participant) + (1|image_file) ,  family = binomial)
# summary(WHNModelUK)
# 
# WHNModelUKYears = glmer(data = WHNDataset, formula = trialResp.corr ~ Block + UKYearsExp +(1|participant) + (1|image_file) ,  family = binomial)
# summary(WHNModelUKYears)
# 
# WHNModelGlas = glmer(data = WHNDataset, formula = trialResp.corr ~ Block + GlasgowYearsExp +(1|participant) + (1|image_file) ,  family = binomial)
# summary(WHNModelGlas)
# 
# 
# 
# WHNModelClip = glmer(data = WHNDataset, formula = trialResp.corr ~ Block + (1|Block:image_file) +(1|participant),  family = binomial, glmerControl(optimizer = "bobyqa"))
# summary(WHNModelClip)
# 
# 
# WHNModelID = glmer(data = WHNDataset, formula = trialResp.corr ~ Block   +(1+ Block|participant),  family = binomial, glmerControl(optimizer = "bobyqa"))
# summary(WHNModelID)

```


```{r get main effects of WHN GLMER}
ef <- as.data.frame(effect("Block", WHNModelBasic))

head(ef)


ggplot(ef, aes(Block, fit, color=fit)) + 
  geom_pointrange(aes(ymax=upper, ymin=lower), position=position_dodge(width = 0.2))+
  theme_classic() # just for a change :)
```
```{r}
mixed(trialResp.corr ~ Block  +(1|participant) + (1|image_file), family=binomial, data=WHNDataset, method = "PB")
```

```{r}
#mixed function used when have multiple fixed effects
#mixed(data = WHNDataset, formula = trialResp.corr ~ Block + (1+ Block |participant) + (1 + Block|image_file), method = 'LRT')
```


```{r plot distributions of data}

#runs al control parameters 
#all_fit(WHNModelBasic)


ggplot(WHNDataset, aes(x=conf_slider.response)) +
    geom_histogram(binwidth=0.01, colour="black", fill="white")


ggplot(WHNDataset, aes(x=Attention_slider.response)) +
    geom_histogram(binwidth=0.01, colour="black", fill="white")


ggplot(WHNDataset, aes(x=MiseryScale.response)) +
    geom_histogram(binwidth=0.01, colour="black", fill="white")

```


```{r compare WHN Model and report}
anova(WHNNullModel0, WHNModel)


WHNresults <- report(WHNModel, CI = 95)

fixef(WHNModel)

summary(WHNModel)
print(WHNresults)


```
#CUE WHN GLMER
```{r Cued WHN GLMERS}

CueWHNModelNull = glmer(data = WHNCuedDataset, formula = trialResp.corr ~ 1  +  + (1|participant) + (1|image_file),family = binomial,glmerControl(optimizer = "bobyqa"))
#summary(CueWHNModelNull)

CueWHNModel = glmer(data = WHNCuedDataset, formula = trialResp.corr ~ Block  + (1|image_file),family = binomial,glmerControl(optimizer = "bobyqa"))

CueWHNModel1 = glmer(data = WHNCuedDataset, formula = trialResp.corr ~ Block + (1|participant) + (1|image_file),family = binomial,glmerControl(optimizer = "bobyqa"))
#summary(CueWHNModel1)

#CueWHNModel2 = glmer(data = WHNCuedDataset, formula = trialResp.corr ~ Block + (1|participant) + (1|image_file) + (Block|image_file),family = binomial, control = glmerControl(optimizer="bobyqa"))
#summary(CueWHNModel2)

anova(CueWHNModel1, CueWHNModel)#, CueWHNModel2)
summary(CueWHNModel)

CueResults <- report(CueWHNModel1, CI = (95))
ef <- as.data.frame(effect("Block", CueWHNModel1))

head(ef)
summary(CueResults)

r.squaredGLMM(CueWHNModel1, CueWHNModelNull)

```

#HUD WHN GLMER
```{r HUD WHN GLMERS}

HUDWHNModelNull = glmer(data = WHNHUDDataset, formula = trialResp.corr ~ 1 + (1|participant) + (1|image_file),family = binomial,glmerControl(optimizer = "bobyqa"))
#summary(HUDWHNModelNull)

HUDWHNModel1 = glmer(data = WHNHUDDataset, formula = trialResp.corr ~ Block + (1|participant) + (1|image_file),family = binomial,glmerControl(optimizer = "bobyqa"))
#summary(HUDWHNModel1)

anova(HUDWHNModelNull,HUDWHNModel1)

summary(HUDWHNModel1)

HUDResults <- report(HUDWHNModel1, CI = 95)

print(HUDResults)


```
#HDD WHN GLMER
```{r HDD WHN GLMER}


HDDWHNModelNull = glmer(data = WHNHDDDataset, formula = trialResp.corr ~ 1 + (1|participant) + (1|image_file),family = binomial, glmerControl(optimizer = "bobyqa"))
#summary(HUDWHNModelNull)

HDDWHNModel1 = glmer(data = WHNHDDDataset, formula = trialResp.corr ~ Block + (1|participant) + (1|image_file),family = binomial, glmerControl(optimizer = "bobyqa"))

HDDWHNModel = glmer(data = WHNHDDDataset, formula = trialResp.corr ~ Block  + (1|image_file),family = binomial, glmerControl(optimizer = "bobyqa"))

summary(HDDWHNModel1)

anova(HDDWHNModelNull,HDDWHNModel, HDDWHNModel1)

HDDResults <- report(HDDWHNModel, CI = 95)

print(HDDResults)



```
#Tablet WHN GLMER
```{r Tablet WHN GLMER}


TabWHNModelNull = glmer(data = WHNTabletDataset, formula = trialResp.corr ~ 1 + (1|participant) + (1|image_file),family = binomial, glmerControl(optimizer = "bobyqa"))
#summary(HUDWHNModelNull)

TabWHNModel1 = glmer(data = WHNTabletDataset, formula = trialResp.corr ~ Block + (1|participant) + (1|image_file),family = binomial, glmerControl(optimizer = "bobyqa"))
summary(TabWHNModel1)

TabWHNModel = glmer(data = WHNTabletDataset, formula = trialResp.corr ~ Block + (1|image_file),family = binomial, glmerControl(optimizer = "bobyqa"))
summary(TabWHNModel)

anova(TabWHNModel1,TabWHNModelNull)

TabResults <- report(TabWHNModel1, CI = 95)

print(TabResults)
library(emmeans)
emmeans(TabWHNModel1, ~ Block )



```

```{r get main effects of WHN GLMER}
ef <- as.data.frame(effect("Block", WHNModelBasic))

head(ef)


ggplot(ef, aes(Block, fit, color=fit)) + 
  geom_pointrange(aes(ymax=upper, ymin=lower), position=position_dodge(width = 0.2))+
  theme_classic() # just for a change :)
```

#Confidence analysis
```{r}
ConfNullModel <- glmer(data = WHNDataset, formula = conf_slider.response ~  (1|participant) + (1|image_file), family = binomial)

summary(ConfNullModel)
```

```{r}

ConfModel = glmer(data = WHNDataset, formula = conf_slider.response ~ Block + (1|participant) + (1|image_file),  family = binomial, glmerControl(optimizer = "bobyqa"))
summary(ConfModel)

ConfModel1 = glmer(data = WHNDataset, formula = conf_slider.response ~ Block + (1|participant) + (1|image_file),  family = binomial, glmerControl(optimizer = "bobyqa"))
summary(ConfModel1)

ConfModel2 = glmer(data = WHNDataset, formula = conf_slider.response ~ Block + (1|participant) + (1 + Block|image_file), family = binomial, glmerControl(optimizer = "bobyqa"))

ConfModel3 = glmer(data = WHNDataset, formula = conf_slider.response ~ Block + (1 + Block|participant) + (1 + Block|image_file),family = binomial, glmerControl(optimizer = "bobyqa"))

summary(ConfModel1)

anova(ConfModel1, ConfModel2, ConfModel3)

r.squaredGLMM(ConfModel1, ConfNullModel)
```

  
```{r Conf GLMER Summary}

Confresults <- report(ConfModel1, CI = 95)

summary(ConfModel1)

fixef(ConfModel1)

print(Confresults)
#anova(Model1)

efconf <- as.data.frame(effect("Block", ConfModel1))

head(efconf)



```

```{r}
ConfCueModel1 = glmer(data = WHNCuedDataset, formula = conf_slider.response ~ Block + (1|participant) + (1|image_file), family = binomial, glmerControl(optimizer = "bobyqa"))

summary(ConfCueModel1)

ConfCueresults <- report(ConfCueModel1, CI = 95)

print(ConfCueresults)
#anova(Model1)

```

```{r}


ConfHUDModel1 = glmer(data = WHNHUDDataset, formula = conf_slider.response ~ Block + (1|participant) + (1|image_file), family = binomial, glmerControl(optimizer = "bobyqa"))

summary(ConfHUDModel1)

fixef(ConfHUDModel1)


ConfHUDresults <- report(ConfHUDModel1, CI = 95)

print(ConfHUDresults)
#anova(Model1)

```

```{r}

ConfHDDModel1 = glmer(data = WHNHDDDataset, formula = conf_slider.response ~ Block + (1|participant) + (1|image_file), family = binomial, glmerControl(optimizer = "bobyqa"))

summary(ConfHDDModel1)

fixef(ConfHDDModel1)


ConfHDDresults <- report(ConfHDDModel1, CI = 95)

print(ConfHDDresults)
#anova(Model1)

```

```{r}

ConfTabModel1 = glmer(data = WHNTabletDataset, formula = conf_slider.response ~ Block + (1|participant) + (1|image_file), family = binomial,  glmerControl(optimizer = "bobyqa"))

summary(ConfTabModel1)

fixef(ConfTabModel1)



ConfTabresults <- report(ConfTabModel1, CI = 95)

print(ConfTabresults)
#anova(Model1)

```



```{r}

MISCNullModel <- glmer(data = WHNDataset, formula = MiseryScale.response ~ 1 + (1|participant), family = poisson)

summary(MISCNullModel)

```

```{r}
MISCModel1 = glmer(data = WHNDataset, formula = MiseryScale.response ~ Block + (1|participant) , family = poisson)

summary(MISCModel1)
```


```{r}
MISCresults <- report(MISCModel1, CI = 95)

print(MISCresults)

```


```{r}
AttentionDataset <- WHNDataset %>% 
  subset(!is.na(Attention_slider.response))




AttAOV <- aov(data = AttentionDataset,formula =  Attention_slider.response ~ Block)

TukeyHSD(AttAOV)
```

```{r}
AttentionSummary <- AttentionDataset %>% 
  group_by(Block) %>% 
summarise(n = n(),
          mean = mean(Attention_slider.response),
          sd = sd(Attention_slider.response))
```

```{r}

library(rstatix)
AttentionDataset %>% 
  group_by(Block) %>% 
  identify_outliers(Attention_slider.response)

AttentionDataset %>% 
  group_by(Block) %>% 
  shapiro_test(Attention_slider.response)

library(ggpubr)

ggqqplot(AttentionDataset, "Attention_slider.response", facet.by = "Block")
```

```{r}
Att.aov <- anova_test(data = AttentionDataset, dv = Attention_slider.response, wid = participant, within = Block)

get_anova_table(Att.aov)

pwc <- AttentionDataset %>% 
  pairwise_t_test(Attention_slider.response ~ Block, paired = TRUE,
                  p.adjust.method = "bonferroni")

pwc <- pwc %>%  add_xy_position(x = "Block")
pwc


bxp <- ggboxplot(AttentionDataset, x = "Block", y = "Attention_slider.response", add = "point")

bxp + 
  #stat_pvalue_manual(pwc) +
  labs(
    subtitle = get_test_label(Att.aov, detailed = TRUE),
    caption = get_pwc_label(pwc)
  )


```


```{r}
AttentionDataset$trials_3.thisTrialN <- as.factor(AttentionDataset$trials_3.thisTrialN)


AttModel1 <- glmer(family = binomial, data = AttentionDataset, formula = Attention_slider.response ~ Block + (1|participant), glmerControl(optimizer = "bobyqa"))

summary(AttModel1)

AttResults <- report(AttModel1, CI = 95)

print(AttResults)
```



```{r}
AttentionCuedDataset <- AttentionDataset# %>% 
 # subset(Block != "Baseline")


AttentionCuedDataset$Block <- factor(AttentionCuedDataset$Block, levels = c("HUD - Cued AR","Baseline", "HUD - AR", "HDD - AR", "HDD - Tablet"))

AttentionHUDDataset <- AttentionDataset# %>% 
 # subset(Block != "Baseline")


AttentionHUDDataset$Block <- factor(AttentionHUDDataset$Block, levels = c("HUD - AR","Baseline", "HUD - Cued AR", "HDD - AR", "HDD - Tablet"))

AttentionHDDDataset <- AttentionDataset# %>% 
 # subset(Block != "Baseline")


AttentionHDDDataset$Block <- factor(AttentionHDDDataset$Block, levels = c("HDD - AR", "HUD - AR","Baseline", "HUD - Cued AR",  "HDD - Tablet"))


AttentionTabletDataset <- AttentionDataset# %>% 
 # subset(Block != "Baseline")


AttentionTabletDataset$Block <- factor(AttentionTabletDataset$Block, levels = c("HDD - Tablet","HDD - AR", "HUD - AR","Baseline", "HUD - Cued AR"))
```
```{r}
AttAOV <- glm(family = binomial, data = AttentionDataset, formula = Attention_slider.response ~ Block)

summary(AttAOV)

```

```{r}

AttCueAOV <- glm(family = binomial, data = AttentionCuedDataset, Attention_slider.response ~ Block )
summary(AttCueAOV)

AttHUDAOV <- glm(family = binomial, data = AttentionHUDDataset, Attention_slider.response ~ Block )

summary(AttHUDAOV)

AttHDDAOV <- glm(family = binomial, data = AttentionHDDDataset, Attention_slider.response ~ Block )

summary(AttHDDAOV)

AttTabAOV <- glm(family = binomial, data = AttentionTabletDataset, Attention_slider.response ~ Block )

summary(AttTabAOV)



```


```{r}


AttHDDAOV <- glm(family = binomial, data = AttentionHDDDataset, Attention_slider.response ~ Block )

summary(AttHDDAOV)


```

```{r}


AttTabAOV <- glm(family = binomial, data = AttentionTabletDataset, Attention_slider.response ~ Block )

summary(AttTabAOV)


```


```{r}
ggplot(WHNDataset, aes(x = Block, y = Attention_slider.response, color=Block)) + 
  stat_summary(fun=mean, geom="point", size=3) + 
  stat_summary(fun.data=mean_se, geom="errorbar", width=0.2) + 
  stat_summary(aes(y=fitted(WHNModelBasic)), fun=mean, geom="line") +
  labs(x="QType", y="SCORE", 
       color="Exposure\n(Tertiles)") + 
  theme_bw()
```

```{r}
anova(AttModel1, AttNullModel)

Attresults <- report(AttModel1, CI = 95)

print(Attresults)
```

```{r}
TabletScores = read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 3/data/Score/TabletScore.csv") %>% 
#subset(image_file != "Slide24") %>%
  subset(ID != "P03") %>%
  subset(ID != "P04") %>%
  subset(ID != "P15") %>% 
  subset(ID != "P16") %>%
  subset(ID != "P24") %>%
  subset(ID != "P01") %>% 
  subset(ID != "P02")
  
```


```{r}
# 
# scoreDataset <- scoreDataset %>%
# #subset(image_file != "Slide24") %>%
#   subset(ID != "P03") %>%
#   subset(ID != "P04") %>%
#   subset(ID != "P15") %>% 
#   subset(ID != "P16") %>%
#   subset(ID != "P24") %>%
#   subset(ID != "P01") %>% 
#   subset(ID != "P02")
```
  
  
```{r}
TabletScoresSummary <- TabletScores %>% 
  summarise(n = n(),
            meanLevel = mean(Level),
            meanScore = mean(Score))
```




