---
title: "Study1_Demogs"
output: html_document
date: '2022-04-24'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
  library(tidyverse)
  library(readr)
  library(janitor)
  library(stringr)

```

```{r}
  list.files()
  #Read in the data
  DemogDataRaw <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study3/data/Qualtrics/Demogs/Study3Demogs.csv") %>%  
    select(starts_with('Q')) 
```
```{r}
#Change the first row into column headers
DemogDataOrg <- row_to_names(DemogDataRaw, row_number = 1)
#Remove consent form columns
DemogDataOrg <- DemogDataOrg[-1,-c(1:7)]

DemogDataOrg <- DemogDataOrg %>% 
  rename(Age = `What is your age?`) %>% 
  rename(Gender = `Which gender do you identify with?`) %>% 
  rename(UKLicense = `Do you have a UK driving license?`) %>%
  rename(CountryLicense = `Which country did you get your driving license in?`) %>%
  rename(YearsExp = `How many years driving experience do you have, either from when you passed your driving test or when you started driving regularly? - (years/months)`) %>%
  rename(UKYearsExp = `How many years driving experience do you have driving in the UK? (years, months)`) %>%
   rename(GlasgowYearsExp = `How many years driving experience do you have driving around the West End of Glasgow? (years, months)`) %>%
  rename(HazPerTest = `Did you take a Hazard Perception test as part of getting your driver's license?(Or another video-based hazard awareness assessment tool?)`) %>%
  rename(VideoGamesTime = `Roughly how many hours do you play video games for in an average week?`) %>% 
  rename(MotionSickness = `Do you have any history of motion sickness? - Selected Choice`) %>% 
  rename(MotionSicknessText = `Do you have any history of motion sickness? - Other (Please describe) - Text`) 

```


```{r}
DemogDataOrg$Age = as.numeric(DemogDataOrg$Age)
DemogDataOrg$VideoGamesTime = as.numeric(DemogDataOrg$VideoGamesTime)

DemogDataOrg$YearsExp = as.numeric(DemogDataOrg$YearsExp)

DemogDataOrg$UKYearsExp = as.numeric(DemogDataOrg$UKYearsExp)
DemogDataOrg$GlasgowYearsExp = as.numeric(DemogDataOrg$GlasgowYearsExp)

DemogDataOrg$Gender[DemogDataOrg$Gender == 'Woman'] <- 'Female'
DemogDataOrg$Gender[DemogDataOrg$Gender == 'Female '] <- 'Female'
DemogDataOrg$Gender[DemogDataOrg$Gender == 'Male '] <- 'Male'


```

```{r}
DemogSummaryTotal <- DemogDataOrg %>% 
  
  summarise(
  n = n(),
  AgeMean = mean(Age),
  AgeSD = sd(Age),
  Male = sum(Gender == 'Male'),
  Female = sum(Gender == "Female"),
  UKLicense = sum(UKLicense == 'Yes'),
  UKExp = mean(UKYearsExp, na.rm = T),
  UKEXPsd = sd(UKYearsExp, na.rm = T),
  GlasgowExp = mean(GlasgowYearsExp, na.rm = T),
  GlasgowExpsd = sd(GlasgowYearsExp, na.rm = T),
  meanVG = mean(VideoGamesTime, na.rm = T),
  meanExp = mean(YearsExp, na.rm = T),
  sdExp = sd(YearsExp, na.rm = T)

  )   
```



