---
title: "NASATLX_Qualtrics"
output: html_document
date: '2022-03-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(janitor)
library(car)
library(emmeans)
```


```{r}
#Read in the data
TLXdataRaw <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study3/data/Qualtrics/TLX/Study3TLX.csv") %>% 

# Tidy the data - select scores,
  select(starts_with('Q'))
  TLXdataOrg <- TLXdataRaw[-c(1:2),]
  colnames(TLXdataOrg) <- c('Ppt_ID','Block', 'Mental Demand', 'Physical Demand', 'Temporal Demand', 'Overall Performance', 'Effort', 'Frustration')
  #Convert columns with ratings in to numeric
  TLXdataOrg[3:8] = lapply(TLXdataOrg[3:8], FUN = function(y){as.numeric(y)})
  
  TLXdataOrg$Block <- str_sub(TLXdataOrg$Block, 1,7)
  
  TLXdataOrg$Block[TLXdataOrg$Block == "Level 1"] <- "HUD - AR"
  TLXdataOrg$Block[TLXdataOrg$Block == "Level 2"] <- "HUD - AR Cued"
  TLXdataOrg$Block[TLXdataOrg$Block == "Level 3"] <- "HDD - Tablet"
  TLXdataOrg$Block[TLXdataOrg$Block == "Level 4"] <- "HDD - AR"
  
  
TLXdataOrg$Block <- factor(TLXdataOrg$Block, levels = c("Control", "HUD - AR","HUD - AR Cued", "HDD - AR", "HDD - Tablet"))


```


```{r}
#Convert to wrangled dataset
TLXdata <- TLXdataOrg 

TLXdata$Performance <- TLXdata$`Overall Performance` 

TLXdata <- TLXdata %>%  select(-`Overall Performance`)

TLXdata$Total = rowSums(TLXdata[,c(3,8)], na.rm = T)


```


```{r}
TLXdataTotalSum <- TLXdata %>% 
  group_by(Block) %>% 
  summarise(
    n = n(),
    mean = mean(Total),
    sd = sd(Total)
  )
```


```{r}
TLXdataSumm <- TLXdata %>% 
  
  group_by(Block) %>% 
  summarise(
    n = n(),
    Mental_mean = mean(`Mental Demand`),
    Mental_sd = sd(`Mental Demand`),
    Physical_mean = mean(`Physical Demand`),
    Physical_sd = sd(`Physical Demand`),
    Temporal_mean = mean(`Temporal Demand`),
    Temporal_sd = sd(`Temporal Demand`),
    Performance_mean = mean(Performance),
    Performance_sd = sd(Performance),
    Frustration_mean = mean(Frustration),
    Frustration_sd = sd(Frustration),
    Effort_mean = mean(Effort),
    Effort_sd = sd(Effort)
    
  )


```

```{r}
ggplot(TLXdata, aes(Block, Total, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  labs(title = "Total")
```


```{r}
ggplot(TLXdata, aes(Block, `Mental Demand`, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim(0,100)+
  labs(title = "Mental Demand")

ggplot(TLXdata, aes(Block, `Physical Demand`, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim(0,100)+
    labs(title = "Physical Demand")

ggplot(TLXdata, aes(Block, `Temporal Demand`, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim(0,100)+
    labs(title = "Temporal Demand")

ggplot(TLXdata, aes(Block,Performance, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim (0,100)+
    labs(title = "Overall Performance")

ggplot(TLXdata, aes(Block, Effort, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim (0,100)+
    labs(title = "Effort")
  
ggplot(TLXdata, aes(Block, Frustration, fill = Block ))+
  geom_boxplot(width = 0.3)+
  geom_violin(alpha = 0.5)+
  ylim (0,100)+
    labs(title = "Frustration")


```



```{r}
Total_Aov = lm(Total ~ Block, data = TLXdata) 
print("Total")

Anova(Total_Aov,
      type = "II")

```



```{r}

MD_Aov = lm(`Mental Demand` ~ Block , data = TLXdata) 
print("Mental Demand")

Anova(MD_Aov,
      type = "II")

print("Physical Demand")
PD_Aov = lm(`Physical Demand` ~ Block , data = TLXdata) 

Anova(PD_Aov,
      type = "II")

TD_Aov = lm(`Temporal Demand` ~ Block , data = TLXdata) 
print("Temporal Demand")

Anova(TD_Aov,
      type = "II")

OP_Aov = lm(Performance ~ Block , data = TLXdata) 
print("Overall Performance")

Anova(OP_Aov,
      type = "II")

EF_Aov = lm(Effort ~ Block , data = TLXdata) 
print("Effort")

Anova(EF_Aov,
      type = "II")

FR_Aov = lm(Frustration ~ Block , data = TLXdata)
print("Frustration")

Anova(FR_Aov,
      type = "II")
```


```{r}
MDmarginal = emmeans(MD_Aov, ~Block)
pairs(MDmarginal, adjust="tukey")
```


```{r}
PDmarginal = emmeans(PD_Aov, ~Block)
pairs(PDmarginal, adjust="tukey")

```


```{r}
TDmarginal = emmeans(TD_Aov, ~Block)
pairs(TDmarginal, adjust="tukey")

```

```{r}
OPmarginal = emmeans(OP_Aov, ~Block)
pairs(OPmarginal, adjust="tukey")

```

```{r}
EFmarginal = emmeans(EF_Aov, ~Block)
pairs(EFmarginal, adjust="tukey")

```

```{r}
FRmarginal = emmeans(FR_Aov, ~Block)
pairs(FRmarginal, adjust="tukey")

```


```{r}
TLXTotalNullmodel <- lmer(data = TLXdata, Total ~ (1|Ppt_ID))
TLXTotalmodel1 <- lmer(data = TLXdata, Total ~Block + (1|Ppt_ID))

anova(TLXTotalNullmodel,TLXTotalmodel1)

summary(TLXTotalmodel1)
```


```{r}
Totalresults <- report(TLXTotalmodel1, CI = 95)

print(Totalresults)
```

```{r}

TLXMentalNullmodel <- lmer(data = TLXdata, `Mental Demand` ~ (1|Ppt_ID))

TLXMentalmodel2 <- lmer(data = TLXdata, `Mental Demand` ~Block + (1|Ppt_ID))

anova(TLXMentalNullmodel, TLXMentalmodel2)

summary(TLXMentalmodel2)

Mentalresults <- report(TLXMentalmodel2, CI = 95)

print(Mentalresults)
```
```{r}
TLXPhysNullmodel <- lmer(data = TLXdata, `Physical Demand` ~ (1|Ppt_ID))


TLXPhysmodel2 <- lmer(data = TLXdata, `Physical Demand` ~Block + (1|Ppt_ID))


summary(TLXPhysmodel2)

anova (TLXPhysNullmodel, TLXPhysmodel2)


Physresults <- report(TLXPhysmodel2, CI = 95)

print(Physresults)
```
```{r}
TLXTempNullmodel <- lmer(data = TLXdata, `Temporal Demand` ~ (1|Ppt_ID))


TLXTempmodel2 <- lmer(data = TLXdata, `Temporal Demand` ~Block + (1|Ppt_ID))


anova(TLXTempNullmodel, TLXTempmodel2)

summary(TLXTempmodel2)

Tempresults <- report(TLXTempmodel2, CI = 95)

print(Tempresults)
```

```{r}
TLXEffortNullmodel <- lmer(data = TLXdata, Effort ~ (1|Ppt_ID))
TLXEffortmodel2 <- lmer(data = TLXdata, Effort ~Block + (1|Ppt_ID))

anova(TLXEffortNullmodel, TLXEffortmodel2)

summary(TLXEffortmodel2)
Effortresults <- report(TLXEffortmodel2, CI = 95)

print(Effortresults)
```

```{r}
TLXFrusNullmodel <- lmer(data = TLXdata, Frustration ~ (1|Ppt_ID))

TLXFrusmodel <- lmer(data = TLXdata, Frustration ~ Block + (1|Ppt_ID))

anova(TLXFrusNullmodel, TLXFrusmodel)
summary(TLXFrusmodel)

Frusresults <- report(TLXFrusmodel, CI = 95)

print(Frusresults)
```

```{r}
TLXPerfNullmodel <- lmer(data = TLXdata, Performance ~ (1|Ppt_ID))


TLXPerfmodel <- lmer(data = TLXdata, Performance ~Block + (1|Ppt_ID))

anova(TLXPerfNullmodel, TLXPerfmodel)

summary(TLXPerfmodel)

Perfresults <- report(TLXPerfmodel, CI = 95)

print(Perfresults)
```