---
title: "CSQ_Qualtrics"
output:
  pdf_document: default
  html_document: default
date: '2022-03-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, include=FALSE}
  library(tidyverse)
  library(readr)
  library(janitor)
  library(emmeans)
  library(car)
  library(dplyr)
  library(tidyr)
  library(stringr)
  library(lme4)

```


```{r, include=FALSE}
#Set the working directory of the data ***HARD CODED ***
 #setwd("D:/Study2Data/qualtrics_data/CSQ")
dataFolder = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 2/Study2Data/hp_data"
```

```{r, include=FALSE}

  list.files()
  #Read in the data
  CSQdataRaw <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 2/Study2Data/qualtrics_data/CSQ/EXP2CSQ.csv") %>%  
    select(starts_with('Q')) 
  
  #Format the column names by removing excess characters
  
CSQdataRaw[1,] <- sub(".*- ", "", CSQdataRaw[1,])
    
#change the row names to the column headers
CSQdataOrg <- row_to_names(CSQdataRaw, row_number = 1)
   
#remove pilot and test data  ***HARD-CODED***
CSQdataOrg <- CSQdataOrg[-c(1:18),]

  
```


```{r,include=FALSE}
#Reorganise the columns and separate out the Condition
CSQdataOrg<- CSQdataOrg %>%
  mutate(ID = substr(`Participant ID:`,
                     start = 1,
                     stop = 3)) %>%
  mutate(Condition = substr(`Participant ID:`,
                            start = 4,
                           stop  = 5))

#Rearrange the columns and remove extra ID column
CSQdataOrg <- CSQdataOrg[,-1] %>%
  select(c(ID, Condition, 1:19))

#Change the conditions to upper case and remove whitespace
CSQdataOrg[,2] = toupper(CSQdataOrg[,2]) %>% 
  trimws(which = c("both"))

```


```{r,include=FALSE}

#Recode Values so they are computable
CSQdata <- CSQdataOrg %>% 
  rename(Timepoint = `Which timepoint is this?`)
CSQdata[CSQdata== '0 - None at all'] <- '0'
CSQdata[CSQdata== '1 - Mild'] <- '1'
CSQdata[CSQdata== '2 - Moderate'] <- '2'
CSQdata[CSQdata== '3 - Severe'] <- '3'

CSQdata[CSQdata== 'Pre-Experiment'] <- '1'
CSQdata[CSQdata== 'End of Control'] <- '2'
CSQdata[CSQdata== 'End of Experiment'] <- '3'

CSQdata[CSQdata== "G"] <- "Global"
CSQdata[CSQdata== "L"] <- "Local"

#Convert columns with ratings in to numeric
CSQdata[4:19] = lapply(CSQdata[4:19], FUN = function(y){as.numeric(y)})

```


```{r}
#Calculate the CSQ score weightings according to Kennedy et al 1993
CSQConversion <- CSQdata 

CSQConversion <- CSQConversion %>% 
  mutate(NauseaSum = 
           (CSQConversion$`General Discomfort` + 
            CSQConversion$`Increased Salivation` + 
            CSQConversion$Sweating + 
            CSQConversion$Nausea + 
            CSQConversion$`Difficulty Concentrating`+
            CSQConversion$`Stomach Awareness` +
            CSQConversion$Burping)) %>% 
  mutate(OculomotorSum = 
           (CSQConversion$`General Discomfort` +
            CSQConversion$Fatigue +
            CSQConversion$Headache +
            CSQConversion$`Eye Strain` +
            CSQConversion$`Difficulty Focusing` +
            CSQConversion$`Difficulty Concentrating`+
            CSQConversion$`Blurred Vision`)) %>% 
  mutate(DisorientationSum =
           (CSQConversion$`Difficulty Focusing` +
            CSQConversion$Nausea +
            CSQConversion$`Fullness of Head` +
            CSQConversion$`Blurred Vision` +
            CSQConversion$`Dizzy (Eyes Open)` +
            CSQConversion$`Dizzy ( Eyes Closed)`+
            CSQConversion$Vertigo)) 

#Calculate the final weighted CSQ scores

  CSQConversion <- CSQConversion %>% 
      mutate(NauseaWeight = (CSQConversion$NauseaSum * 9.54)) %>% 
      mutate(OculomotorWeight = (CSQConversion$OculomotorSum*7.58)) %>% 
      mutate(DisorientationWeight = (CSQConversion$DisorientationSum *13.92)) %>% 
      mutate(TotalCSQScore = 
               (CSQConversion$NauseaSum +
               CSQConversion$OculomotorSum +
               CSQConversion$DisorientationSum)*
               3.74)
  
 # write.csv(CSQConversion,"D:/Qualtrics_Data/Study1/CSQ/EXP1CSQSort.csv", row.names = FALSE)
  
```

```{r}
#Summarise the descriptives for the converted scores
CSQConversionSummary <- CSQConversion %>% 
  
  group_by(Condition, Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(TotalCSQScore),
  sd = sd(TotalCSQScore),
  min = min(TotalCSQScore),
  max = max(TotalCSQScore))   
#Summarise the descriptives for the converted  Nausea scores
CSQNauseaSummary <- CSQConversion %>% 
  
  group_by(Condition, Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(NauseaWeight),
  sd = sd(NauseaWeight),
  min = min(NauseaWeight),
  max = max(NauseaWeight))   
#Summarise the descriptives for the converted Oculomotor scores
CSQOculoSummary <- CSQConversion %>% 
  
  group_by(Condition, Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(OculomotorWeight),
  sd = sd(OculomotorWeight),
  min = min(OculomotorWeight),
  max = max(OculomotorWeight))  
#Summarise the descriptives for the converted Disorientation scores
CSQDisoriSummary <- CSQConversion %>% 
  
  group_by(Condition, Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(DisorientationWeight),
  sd = sd(DisorientationWeight),
  min = min(DisorientationWeight),
  max = max(DisorientationWeight)) 
```
```{r}
CSQConversion$Condition <- CSQConversion$ID

CSQConversion$Condition[as.numeric(str_sub(CSQConversion$Condition, -1))%%2 == 0] <- "Wider"

CSQConversion$Condition[as.numeric(str_sub(CSQConversion$Condition, -1))%%2 == 1] <- "Focused"
```



```{r}
  ########################END OF DATA WRANGLING########################
  #####################################################################
```

        
```{r}
#Visualise the spread of the data
ggplot(CSQConversion, aes(x = TotalCSQScore, fill = Timepoint))+
  geom_histogram(binwidth = 5)

```
           
```{r}
#Create violin plots for each of the Weighted totals to show the spread of the data
ggplot(CSQConversion, aes(Condition, TotalCSQScore, fill = Timepoint ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Total CSQ Score")
ggplot(CSQConversion, aes(Condition, OculomotorWeight, fill = Timepoint ))+
  geom_violin(alpha = 0.5) +
  labs(title = "Oculomotor Score")
ggplot(CSQConversion, aes(Condition, NauseaWeight, fill = Timepoint ))+
  geom_violin(alpha = 0.5) +
  labs(title = "Nausea score")
ggplot(CSQConversion, aes(Condition, DisorientationWeight, fill = Timepoint ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Disorientation Score")
```
```{r}
#Create interaction plots for the mean of each condition at each of the 3 timepoints
#**pch = type of shape on the point graph
interaction.plot(x.factor =  CSQConversion$Timepoint,
                 trace.factor = CSQConversion$Condition,
                 response = CSQConversion$TotalCSQScore,
                 fun = mean,
                 ylim = (c(0,20)),
                 xlab = "Timepoint",
                 ylab = "Total CSQ Score",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Total CSQ Score",
                 fixed=T,
                 leg.bty ="o")
interaction.plot(x.factor =  CSQConversion$Timepoint,
                 trace.factor = CSQConversion$Condition,
                 response = CSQConversion$NauseaWeight,
                 fun = mean,
                 ylim = (c(0,20)),
                 xlab = "Timepoint",
                 ylab = "Nausea subscale",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Nausea",
                 fixed=T,
                 leg.bty ="o")
interaction.plot(x.factor =  CSQConversion$Timepoint,
                 trace.factor = CSQConversion$Condition,
                 response = CSQConversion$OculomotorWeight,
                 fun = mean,
                 ylim = (c(0,20)),
                 xlab = "Timepoint",
                 ylab = "Oculomotor subscale",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Oculomotor",
                 fixed=T,
                 leg.bty ="o")
interaction.plot(x.factor =  CSQConversion$Timepoint,
                 trace.factor = CSQConversion$Condition,
                 response = CSQConversion$DisorientationWeight,
                 fun = mean,
                 ylim = (c(0,20)),
                 xlab = "Timepoint",
                 ylab = "Disorientation subscale",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Disorientation",
                 fixed=T,
                 leg.bty ="o")
```

```{r}
# Generate linear modals for each of the weighted scores
CSQModel = lm(TotalCSQScore ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQConversion)


test = aov(TotalCSQScore ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQConversion)

summary(test)

Anova(CSQModel,
      type = "II")

```
```{r}
#Calculate comparison means for Overall scores
CSQmarginal = emmeans(CSQModel, ~Condition:Timepoint)
pairs(CSQmarginal, adjust="tukey")

```
 
```{r}
# Generate linear modals for Oculomotor subscale

OcuModel = lm(OculomotorWeight ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQConversion)

Anova(OcuModel,
      type = "II")

```

```{r}
#Calculate comparison means for Oculomotor subscale

Ocumarginal = emmeans(OcuModel, ~Condition:Timepoint)
pairs(Ocumarginal, adjust="tukey")

```
 
```{r}
# Generate linear modals for Nausea subscale
NauModel = lm(NauseaWeight ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQConversion)

Anova(NauModel,
      type = "II")
```

```{r}
#Calculate comparison means for Nausea subscale

Naumarginal = emmeans(NauModel, ~Condition:Timepoint)
pairs(Naumarginal, adjust="tukey")

#Significatn effect of conidtion, but is meaningless in the comparisons

```
 
```{r}
#Generate linear modals for Disorientation  subscale
DisModel = lm(DisorientationWeight ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQConversion)

Anova(DisModel,
      type = "II")
```

```{r}
#Calculate comparison means for Disorientation subscale

Dismarginal = emmeans(DisModel, ~Condition:Timepoint)
pairs(Dismarginal, adjust="tukey")

```

```{r}
  ######################## REMOVING OUTLIERS #########################
  ####################################################################
```
       
```{r}
CSQExtremeRM <- CSQConversion %>% 
  
  subset(ID !="P25") %>% 
  subset(ID !="P18") 


CSQExtremeRM$Condition <- gsub("Global", "Wider", CSQExtremeRM$Condition)
CSQExtremeRM$Condition <- gsub("Local", "Focused", CSQExtremeRM$Condition)



CSQExtremeRMSummary <- CSQExtremeRM %>% 
  
  group_by(Condition, Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(TotalCSQScore),
  sd = sd(TotalCSQScore),
  min = min(TotalCSQScore),
  max = max(TotalCSQScore))  
 

```  
```{r}
#Visualise the spread of the data
ggplot(CSQExtremeRM, aes(x = TotalCSQScore, fill = Timepoint))+
  geom_histogram(binwidth = 4.5)

```

```{r}
#Create violin plots for each of the Weighted totals to show the spread of the data
ggplot(CSQExtremeRM, aes(Condition, TotalCSQScore, fill = Timepoint ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Total CSQ Score")
ggplot(CSQExtremeRM, aes(Condition, OculomotorWeight, fill = Timepoint ))+
  geom_violin(alpha = 0.5) +
  labs(title = "Oculomotor Score")
ggplot(CSQExtremeRM, aes(Condition, NauseaWeight, fill = Timepoint ))+
  geom_violin(alpha = 0.5) +
  labs(title = "Nausea score")
ggplot(CSQExtremeRM, aes(Condition, DisorientationWeight, fill = Timepoint ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Disorientation Score")
```
 
```{r}
#Create interaction plots for the mean of each condition at each of the 3 timepoints
#**pch = type of shape on the point graph
interaction.plot(x.factor =  CSQExtremeRM$Timepoint,
                 trace.factor = CSQExtremeRM$Condition,
                 response = CSQExtremeRM$TotalCSQScore,
                 fun = mean,
                 ylim = (c(0,15)),
                 xlab = "Timepoint",
                 ylab = "Total SSQ Score",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Condition",
                 fixed=T,
                 leg.bty ="o")
interaction.plot(x.factor =  CSQExtremeRM$Timepoint,
                 trace.factor = CSQExtremeRM$Condition,
                 response = CSQExtremeRM$NauseaWeight,
                 fun = mean,
                 ylim = (c(0,15)),
                 xlab = "Timepoint",
                 ylab = "Nausea subscale",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Condition",
                 fixed=T,
                 leg.bty ="o")
interaction.plot(x.factor =  CSQExtremeRM$Timepoint,
                 trace.factor = CSQExtremeRM$Condition,
                 response = CSQExtremeRM$OculomotorWeight,
                 fun = mean,
                 ylim = (c(0,15)),
                 xlab = "Timepoint",
                 ylab = "Oculomotor subscale",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Condition`",
                 fixed=T,
                 leg.bty ="o")
interaction.plot(x.factor =  CSQExtremeRM$Timepoint,
                 trace.factor = CSQExtremeRM$Condition,
                 response = CSQExtremeRM$DisorientationWeight,
                 fun = mean,
                 ylim = (c(0,15)),
                 xlab = "Timepoint",
                 ylab = "Disorientation subscale",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Condition",
                 fixed=T,
                 leg.bty ="o")

```

```{r}
#Generate linear modals for each of the weighted scores
CSQERMModel = lm(TotalCSQScore ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQExtremeRM)

NauseaERMModel = lm(NauseaWeight ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQExtremeRM)

OculoERMModel = lm(OculomotorWeight ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQExtremeRM)

DisoriERMModel = lm(DisorientationWeight ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQExtremeRM)

Anova(CSQModel,
      type = "II")
Anova(NauseaERMModel,
      type = "II")
Anova(OculoERMModel,
      type = "II")
Anova(DisoriERMModel,
      type = "II")

```

```{r}
CSQERMMar = emmeans(CSQERMModel, ~Condition:Timepoint)
pairs(CSQERMMar, adjust="tukey")

NauseaERMModel

```

```{r}
##################  CONVERT DATA TO LOOK AT DIFFERENCES OVER TIME ###########
#############################################################################
```

```{r}
#Convert the dataset to look out differences over time

CSQKPConversion <- CSQConversion %>% 
  
  pivot_wider(names_from = Timepoint, values_from = 4:26)
CSQKPConversionTotal <- CSQKPConversion %>% 
  
  mutate(TotalCSQ_Base = 
            (0)) %>% 

   mutate(TotalCSQ_Con = 
            (CSQKPConversion$TotalCSQScore_2 -
             CSQKPConversion$TotalCSQScore_1)) %>% 
  
   mutate(TotalCSQ_Exp = 
            (CSQKPConversion$TotalCSQScore_3 -
             CSQKPConversion$TotalCSQScore_2)) %>%
  
   mutate(Oculo_Base = 
            (0)) %>% 
 
   mutate(Oculo_Con = 
            (CSQKPConversion$OculomotorWeight_2 -
             CSQKPConversion$OculomotorWeight_1)) %>% 
   mutate(Oculo_Exp = 
            (CSQKPConversion$OculomotorWeight_3 -
             CSQKPConversion$OculomotorWeight_2)) %>% 
  
    mutate(Nausea_Base = 
            (0)) %>% 

   mutate(Nausea_Con = 
            (CSQKPConversion$NauseaWeight_2 -
             CSQKPConversion$NauseaWeight_1)) %>% 
   mutate(Nausea_Exp = 
            (CSQKPConversion$NauseaWeight_3 -
             CSQKPConversion$NauseaWeight_2)) %>% 
  
    mutate(Disori_Base = 
            (0)) %>% 

   mutate(Disori_Con = 
            (CSQKPConversion$DisorientationWeight_2 -
             CSQKPConversion$DisorientationWeight_1)) %>% 
   mutate(Disori_Exp = 
            (CSQKPConversion$DisorientationWeight_3 -
             CSQKPConversion$DisorientationWeight_2)) %>% 
  
  select(ID, Condition, 72:83) 

```

```{r}
## Reformat data and wrtie csv file to to be read in JASP  

CSQKPConversionTotalCSQ <- pivot_longer(data = CSQKPConversionTotal,
                          cols = c(3:5)) %>% 
  select(c(1,2,12,13))

colnames(CSQKPConversionTotalCSQ)[colnames(CSQKPConversionTotalCSQ) %in% c("name", "value")] <- c("Timepoint", "Value") 
  
CSQKPConversionTotalCSQ[c('Measure', "Timepoint")] <- str_split_fixed(CSQKPConversionTotalCSQ$Timepoint, "_", 2)

CSQKPConversionTotalCSQ[CSQKPConversionTotalCSQ== 'Base'] <- 'Baseline'
CSQKPConversionTotalCSQ[CSQKPConversionTotalCSQ== 'Con'] <- 'Hazard Perception'
CSQKPConversionTotalCSQ[CSQKPConversionTotalCSQ== 'Exp'] <- 'Hazard Perception + AR'

  #write.csv(CSQKPConversionTotalCSQ,"D:/Qualtrics_Data/Study1/CSQ/EXP1CSQSortKP.csv", row.names = FALSE)


```


```{r}
##Create summary tables for the Total SSQ 
#'
CSQKPConversionTotalCSQSummary <- CSQKPConversionTotalCSQ %>% 
  
  group_by(Condition, Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(Value, na.rm = T),
  sd = sd(Value, na.rm = T)
  )   


CSQKPConversionTotalCSQSummary2 <- CSQKPConversionTotalCSQ %>% 
  
  group_by(Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(Value, na.rm = T),
  sd = sd(Value, na.rm = T)
  )   

```

```{r}
ggplot(CSQKPConversionTotalCSQ, aes(Condition, Value, fill = Timepoint ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Total CSQ Score")

interaction.plot(x.factor =  CSQKPConversionTotalCSQSummary$Timepoint,
                 trace.factor = CSQKPConversionTotalCSQSummary$Condition,
                 response = CSQKPConversionTotalCSQSummary$mean,
                 fun = mean,
                 ylim = c(-4, 10),
                 xlab = "Timepoint",
                 ylab = "Change in Total CSQ Score",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Total CSQ Score",
                 fixed=F,
                 leg.bty ="o")
```
```{r}
ggplot(CSQKPConversionTotalCSQSummary2,  aes(x = Timepoint, y = mean, colour = Timepoint, group = 2))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_line(colour = "black", alpha = 0.5) +
  geom_point (size = 3.5, shape = 13) +
  labs(x = "Block",
      y = "Chnage in Total CSQ Score",
      title = "Total CSQ Score",
      tag = "")+  
  ylim(0,10) +

  theme_bw()
```


```{r}
ggplot(CSQKPConversionTotalCSQSummary2,  aes(x = Timepoint, y = mean, colour = Timepoint, group = 1))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_line(colour = "black", alpha = 0.5) +
  geom_point (size = 3.5, shape = 13) +
  labs(x = "Block",
      y = "Change in Total CSQ Score",
      title = "Total CSQ Score",
      tag = "")+  
  ylim(0,10) +

  theme_bw()
```

```{r}

KPCSQModelBet = aov(Value ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQKPConversionTotalCSQ)

Anova(KPCSQModelBet,
      type = "II")

KPCSQModelWith = aov(Value ~ Timepoint,
              data = CSQKPConversionTotalCSQ)

Anova(KPCSQModelWith,
      type = "II")
```

```{r}
KPCSQModelWith = emmeans(KPCSQModelWith, ~Timepoint)
pairs(KPCSQModelWith, adjust="tukey")

KPCSQModelBet = emmeans(KPCSQModelBet, ~Condition:Timepoint)
pairs(KPCSQModelBet, adjust="tukey")
```


```{r}
TotalCSQmodel <- lmer(data = CSQKPConversionTotalCSQ, Value ~Timepoint+Condition + (1|ID))
TotalCSQmodel2 <- lmer(data = CSQKPConversionTotalCSQ, Value ~Timepoint*Condition + (1|ID))

anova(TotalCSQmodel, TotalCSQmodel2)

summary(TotalCSQmodel)

```
```{r}
library(report)
TotalCSQresults <- report(TotalCSQmodel, CI = 95)

print(TotalCSQresults)


```



```{r}
#############################################################################
```

```{r}
CSQKPConversionOculo <- pivot_longer(data = CSQKPConversionTotal,
                          cols = c(6:8)) %>% 
  select(c(1,2,12,13))

colnames(CSQKPConversionOculo)[colnames(CSQKPConversionOculo) %in% c("name", "value")] <- c("Timepoint", "Value") 
  
CSQKPConversionOculo[c('Measure', "Timepoint")] <- str_split_fixed(CSQKPConversionOculo$Timepoint, "_", 2)

  #write.csv(CSQKPConversionOculo,"D:/Qualtrics_Data/Study2/CSQ/EXP1CSQSortKPOculo.csv", row.names = FALSE)

```

```{r}
CSQKPConversionOculoSummary <- CSQKPConversionOculo %>% 
  
  group_by(Condition, Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(Value, na.rm = T),
  sd = sd(Value, na.rm = T)
  )   

CSQKPConversionOculoSummary2 <- CSQKPConversionOculo %>% 
  
  group_by(Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(Value, na.rm = T),
  sd = sd(Value, na.rm = T)
  )   


```

```{r}
ggplot(CSQKPConversionOculo, aes(Condition, Value, fill = Timepoint ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Total CSQ Score")

interaction.plot(x.factor =  CSQKPConversionOculoSummary$Timepoint,
                 trace.factor = CSQKPConversionOculoSummary$Condition,
                 response = CSQKPConversionOculoSummary$mean,
                 fun = mean,
                 ylim = c(0, 10),
                 xlab = "Timepoint",
                 ylab = "Change in Oculomotor subscore",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Oculomotor",
                 fixed=F,
                 leg.bty ="o")

```
```{r}
ggplot(CSQKPConversionOculoSummary2,  aes(x = Timepoint, y = mean, colour = Timepoint, group = 1))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_line(colour = "black", alpha = 0.5) +
  geom_point (size = 3.5, shape = 13) +
  labs(x = "Block",
      y = "Chnage in Oculomotor subscale",
      title = "Oculomotor",
      tag = "")+  
  ylim(0,10) +

  theme_bw()
```

```{r}
KPCSQModelOculoBet = lm(Value ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQKPConversionOculo)

Anova(KPCSQModelOculoBet,
      type = "II")

KPOculomargi = emmeans(KPCSQModelOculoBet, ~Condition:Timepoint)
pairs(KPOculomargi, adjust="tukey")

```
```{r}
KPCSQModelOculoWith = lm(Value ~ Timepoint,
              data = CSQKPConversionOculo)

Anova(KPCSQModelOculoWith,
      type = "II")
```


```{r}
Oculomodel <- lmer(data = CSQKPConversionOculo, Value ~Timepoint+Condition + (1|ID))

Oculomodel2 <- lmer(data = CSQKPConversionOculo, Value ~Timepoint*Condition + (1|ID))

anova(Oculomodel2, Oculomodel)

summary(Oculomodel)
```
```{r}
Oculoresults <- report(Oculomodel, CI = 95)

#summary(results)
print(Oculoresults)
```

```{r}
#############################################################################
```


```{r}
CSQKPConversionNausea <- pivot_longer(data = CSQKPConversionTotal,
                          cols = c(9:11)) %>% 
  select(c(1,2,12,13))

colnames(CSQKPConversionNausea)[colnames(CSQKPConversionNausea) %in% c("name", "value")] <- c("Timepoint", "Value") 
  
CSQKPConversionNausea[c('Measure', "Timepoint")] <- str_split_fixed(CSQKPConversionNausea$Timepoint, "_", 2)

 # write.csv(CSQKPConversionNausea,"D:/Qualtrics_Data/Study1/CSQ/EXP1CSQSortKPNausea.csv", row.names = FALSE)
```


```{r}
CSQKPConversionNauseaSummary <- CSQKPConversionNausea %>% 
  
  group_by(Condition, Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(Value, na.rm = T),
  sd = sd(Value, na.rm = T)
  )   

CSQKPConversionNauseaSummary2 <- CSQKPConversionNausea %>% 
  
  group_by(Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(Value, na.rm = T),
  sd = sd(Value, na.rm = T)
  )   


```

```{r}
ggplot(CSQKPConversionNausea, aes(Condition, Value, fill = Timepoint ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Nausea")

interaction.plot(x.factor =  CSQKPConversionNauseaSummary$Timepoint,
                 trace.factor = CSQKPConversionNauseaSummary$Condition,
                 response = CSQKPConversionNauseaSummary$mean,
                 fun = mean,
                 ylim = c(0, 6),
                 xlab = "Timepoint",
                 ylab = "Score",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Nausea",
                 fixed=F,
                 leg.bty ="o")
```
```{r}
ggplot(CSQKPConversionNauseaSummary2,  aes(x = Timepoint, y = mean, colour = Timepoint, group = 1))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_line(colour = "black", alpha = 0.5) +
  geom_point (size = 3.5, shape = 13) +
  labs(x = "Block",
      y = "Chnage in Nausea subscale",
      title = "Nausea",
      tag = "")+  
  ylim(0,10) +

  theme_bw()
```


```{r}
KPCSQModelNauseaBet = lm(Value ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQKPConversionNausea)

Anova(KPCSQModelNauseaBet,
      type = "II")

KPNauseamargi = emmeans(KPCSQModelNauseaBet, ~Condition:Timepoint)
pairs(KPNauseamargi, adjust="tukey")

```
```{r}
KPCSQModelNauseaWith = lm(Value ~ Timepoint,
              data = CSQKPConversionNausea)

Anova(KPCSQModelNauseaWith,
      type = "II")
```
```{r}
Nauseamodel <- lmer(data = CSQKPConversionNausea, Value ~Timepoint*Condition + (1|ID))

summary(Nauseamodel)
```
```{r}
Nausearesults <- report(Nauseamodel, CI = 95)

#summary(results)
print(Nausearesults)
```


```{r}
#############################################################################
```

```{r}
CSQKPConversionDisori <- pivot_longer(data = CSQKPConversionTotal,
                          cols = c(12:14)) %>% 
  select(c(1,2,12,13))

colnames(CSQKPConversionDisori)[colnames(CSQKPConversionDisori) %in% c("name", "value")] <- c("Timepoint", "Value") 
  
CSQKPConversionDisori[c('Measure', "Timepoint")] <- str_split_fixed(CSQKPConversionDisori$Timepoint, "_", 2)


  #write.csv(CSQKPConversionDisori,"D:/Qualtrics_Data/Study1/CSQ/EXP1CSQSortKPDisori.csv", row.names = FALSE)

```


```{r}
CSQKPConversionDisoriSummary <- CSQKPConversionDisori %>% 
  
  group_by(Condition, Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(Value, na.rm = T),
  sd = sd(Value, na.rm = T)
  )   

CSQKPConversionDisoriSummary2 <- CSQKPConversionDisori %>% 
  
  group_by(Timepoint) %>% 
  summarise(
  n = n(),
  mean = mean(Value, na.rm = T),
  sd = sd(Value, na.rm = T)
  )   


```

```{r}
ggplot(CSQKPConversionDisori, aes(Condition, Value, fill = Timepoint ))+
  geom_violin(alpha = 0.5)+
  labs(title = "Disorientation")

interaction.plot(x.factor =  CSQKPConversionDisoriSummary$Timepoint,
                 trace.factor = CSQKPConversionDisoriSummary$Condition,
                 response = CSQKPConversionDisoriSummary$mean,
                 fun = mean,
                 ylim = c(-1 , 10),
                 xlab = "Timepoint",
                 ylab = "Change in Disorientation subscore",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Disorientation",
                 fixed=F,
                 leg.bty ="o")
```
```{r}
ggplot(CSQKPConversionDisoriSummary2,  aes(x = Timepoint, y = mean, colour = Timepoint, group = 1))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  geom_line(colour = "black", alpha = 0.5) +
  geom_point (size = 3.5, shape = 13) +
  labs(x = "Block",
      y = "Chnage in Disorientation subscale",
      title = "Disorientation",
      tag = "")+  
  ylim(0,10) +

  theme_bw()
```

```{r}
KPCSQModelDisoriBet = lm(Value ~ Timepoint + Condition + Timepoint:Condition,
              data = CSQKPConversionDisori)

Anova(KPCSQModelDisoriBet,
      type = "II")
```
```{r}
KPDisorimargi = emmeans(KPCSQModelDisoriBet, ~Condition:Timepoint)
pairs(KPDisorimargi, adjust="tukey")

```


```{r}
KPCSQModelDisoriWith = lm(Value ~ Timepoint,
              data = CSQKPConversionDisori)

Anova(KPCSQModelDisoriWith,
      type = "II")

```

```{r}
Disorimodel <- lmer(data = CSQKPConversionDisori, Value ~Timepoint+Condition + (1|ID))

Disorimodel2 <- lmer(data = CSQKPConversionDisori, Value ~Timepoint*Condition + (1|ID))

anova(Disorimodel, Disorimodel2)

summary(Disorimodel)
```
```{r}
Disoriresults <- report(Disorimodel, CI = 95)

#summary(results)
print(Disoriresults)
```

