---
title: "Study2Validation"
output: html_document
date: '2022-07-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(stringr)
library(plyr)
library(dplyr)
library(splitstackshape)
library(readxl)
library(xlsx)

```


```{r}
### Read in the Data Files ###

#set the working directory to the data folder
#setwd("D:/PsychoPyExperiments/Study 2 Clips")

#Define the filepath for where the data is coming from
#dataFolder <- "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 2/data"

dataFolder <- "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 2/data"

#Create a list of all the datafiles in the folder, and then convert to a list object - needs full names for the file path
file_list <- list.files(path = dataFolder, pattern = ".csv$", all.files = TRUE, full.names = TRUE, recursive = TRUE)

```

```{r}
#Loop through the files and create one large dataset
datasetRaw <- data.frame()

for (i in 1:length(file_list)){
  temp_data <- assign(paste(substr(file_list[i],26,29)),  
              read.csv(paste0(file_list[i])))
  temp_data <- data.frame(temp_data[-c(1,3,4,5,6,7,13:26)])
  
  datasetRaw <- rbind.fill(datasetRaw, temp_data) %>% 
    mutate(idx = as.integer(factor(participant))) 
    
}

datasetRaw <- datasetRaw %>% 
  select(-"participant") %>% 
  select(-"participant.")

```


```{r}

#Standardise age inputs

datasetRaw$Age.Years..months.. <- gsub("81 years 1 month", "81.83", as.character(datasetRaw$Age.Years..months..)) 
datasetRaw$Age.Years..months.. <- gsub("72 yrs 8 months", "72.67", as.character(datasetRaw$Age.Years..months..)) 
datasetRaw$Age.Years..months.. <- gsub("29, 4", "29.33", as.character(datasetRaw$Age.Years..months..)) 
datasetRaw$Age.Years..months.. <- gsub("56 years 8 months", "56.67", as.character(datasetRaw$Age.Years..months..)) 
datasetRaw$Age.Years..months.. <- gsub("71/09", "71.75", as.character(datasetRaw$Age.Years..months..)) 

datasetRaw$Age.Years..months.. <- gsub("62 years 11 months", "62.92", as.character(datasetRaw$Age.Years..months..)) 
datasetRaw$Age.Years..months.. <- gsub("80y 9m", "80.75", as.character(datasetRaw$Age.Years..months..)) 
datasetRaw$Age.Years..months.. <- gsub("66 years and 8 months", "66.67", as.character(datasetRaw$Age.Years..months..)) 
datasetRaw$Age.Years..months.. <- gsub("38, 8", "38.67", as.character(datasetRaw$Age.Years..months..)) 
datasetRaw$Age.Years..months.. <- gsub("54 yrs  1 month", "54.83", as.character(datasetRaw$Age.Years..months..)) 
datasetRaw$Age.Years..months.. <- gsub("41, 9", "41.75", as.character(datasetRaw$Age.Years..months..)) 


datasetRaw$Age.Years..months.. <- gsub("years", "", as.character(datasetRaw$Age.Years..months..)) 


datasetRaw$Age.Years..months.. <- as.numeric(datasetRaw$Age.Years..months..)

mean(datasetRaw$Age.Years..months.., na.rm = T)
  
```

```{r}

#standardise driving experience inputs

datasetRaw$Years.driving.experience..Years..months.. <- gsub("54yrs 5mths", "54.42", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("62y 0m", "62.0", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("24, 1", "24.83", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("19,8", "19.67", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("7,8", "7.67", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("47 years 8 months", "47.67", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("38 years 4 months ", "38.33", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("81 years 1 month", "81.83", as.character(datasetRaw$Years.driving.experience..Years..months..)) 


datasetRaw$Years.driving.experience..Years..months.. <- gsub("years experience", "", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("years", "", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("Year", "", as.character(datasetRaw$Years.driving.experience..Years..months..)) 
datasetRaw$Years.driving.experience..Years..months.. <- gsub("yrs", "", as.character(datasetRaw$Years.driving.experience..Years..months..)) 




datasetRaw$Years.driving.experience..Years..months.. <- as.numeric(datasetRaw$Years.driving.experience..Years..months..)


  
```


```{r}
  #clean up dataset to only include hazard response data and reorganise
  datasetHazard <- datasetRaw %>% 
  #Remove drivers older then 75 - according to Horswill et al 2009 - A comparison of the hazard perception ability of matched #groups of healthy drivers aged 35 to 55, 65 to 74, and 75 to 84 years
 
  subset(Age.Years..months..< 75) 
  meanAge <- mean(datasetHazard$Age.Years..months..)
  sdAge <- sd(datasetHazard$Age.Years..months..) 
  meanDrExp <- mean(datasetHazard$Years.driving.experience..Years..months.., na.rm = T)
  sdDrExp <- sd(datasetHazard$Years.driving.experience..Years..months.., na.rm = T)
                
  datasetHazard <- datasetHazard %>%   
  select(idx, video_file, hazard_resp.rt) 

#magic line that gets rid of [ ] without using regex
  datasetHazard$hazard_resp.rt <-stringr::str_remove_all(datasetHazard$hazard_resp.rt,"[\\[\\]]")
   
   
   datasetHazard$video_file <- gsub('.{4}$', '', datasetHazard$video_file) 
   datasetHazard <- datasetHazard[-which(datasetHazard$hazard_resp.rt == "")] %>% 
   
     dplyr::rename(PilotClips = video_file)
     
   #remove empty rows by changing blank spaces to NA then remvoing incomplete cases
  datasetHazard$PilotClips[datasetHazard$PilotClips == ""] <- NA
  
  datasetHazard <- datasetHazard[complete.cases(datasetHazard$PilotClips), ]  
              
#Split the column with all responses into multiple columns per participants
  datasetHazard <-  cSplit(datasetHazard, "hazard_resp.rt", sep=",") 
  
   datasetHazard <- subset(datasetHazard, idx !="4")
    


```


```{r}
#Read in onset times spreadsheet

#setwd('C:/Users/thoma/OneDrive - University of Glasgow/Documents')
onsetTimes = read_excel("Study2HazardSheet.xlsx" ) %>% 
  select(-3)

```


```{r}
#Combine dataframes

datasetHazardSorted <- left_join(datasetHazard, onsetTimes, by='PilotClips')
datasetHazardSorted$HazardOnset <- 0
  
datasetHazardSorted <- datasetHazardSorted %>% 
    select(c(1,2,Hazard, `Hazard Location`,HazardOnset, ClipOnset, ClipOffset, 3:15))

```


```{r}

# ## iterate through each column and remove values not close to the exp hazard onset
# ##Hard coded because the automated way doesn't work
# 
# for (i in 1:nrow(datasetHazardSorted))
#   {
#     datasetHazardSorted$hazard_resp.rt_01[i] <- 
#     ifelse(datasetHazardSorted$hazard_resp.rt_01[i] <= datasetHazardSorted$ClipOnset[i] -2 ||
#            datasetHazardSorted$hazard_resp.rt_01[i] >= datasetHazardSorted$ClipOnset[i] + 2 , 
#            NA, datasetHazardSorted$hazard_resp.rt_01[i])
#   }
# 

```

```{r}
#Iterate through all the columns and all the rows removing the numbers not around
#the hazard onset


###McKenna et al (2006) - excluding those after the hazard

for (c in c(8:ncol(datasetHazardSorted)))
{

  for (r in 1:nrow(datasetHazardSorted))
    {
      datasetHazardSorted[[c]][r] <- 
      ifelse(datasetHazardSorted[[c]][r] < datasetHazardSorted$ClipOnset[r] -1.0  ||
             datasetHazardSorted[[c]][r] >  datasetHazardSorted$ClipOffset[r] , 
             NA, datasetHazardSorted[[c]][r])
    }
}


resp1 <- data.frame(datasetHazardSorted$hazard_resp.rt_01)
resp2 <- data.frame(datasetHazardSorted$hazard_resp.rt_02)
resp3 <- data.frame(datasetHazardSorted$hazard_resp.rt_03)
resp4 <- data.frame(datasetHazardSorted$hazard_resp.rt_04)
resp5 <- data.frame(datasetHazardSorted$hazard_resp.rt_05)
resp6 <- data.frame(datasetHazardSorted$hazard_resp.rt_06)

Responses <- data.frame(resp1, resp2,resp3,resp4, resp5, resp6)

Responses <- Responses %>% 
  mutate(A = coalesce(datasetHazardSorted.hazard_resp.rt_01, datasetHazardSorted.hazard_resp.rt_02, datasetHazardSorted.hazard_resp.rt_03, datasetHazardSorted.hazard_resp.rt_04, datasetHazardSorted.hazard_resp.rt_05, datasetHazardSorted.hazard_resp.rt_06))
  
datasetHazardSorted$HazardOnset <- Responses$A
# for (c in c(8:ncol(datasetHazardSorted)))
# {
# 
#   for (r in 1:nrow(datasetHazardSorted))
#     {
#       datasetHazardSorted[[c]][r] <- 
#        ifelse(datasetHazardSorted[[c]][r] < datasetHazardSorted$ClipOnset[r] - 2  ||
#              datasetHazardSorted[[c]][r] >  datasetHazardSorted$ClipOnset[r] + 2 , 
#              NA, datasetHazardSorted[[c]][r])
#     }
# }


# 
# #iterate through and average the hazard responses
# for (i in 1:length(datasetHazardSorted$idx))
# {
#      datasetHazardSorted$HazardOnset[i] <- rowMeans(datasetHazardSorted[i,c(8:19)], na.rm = T )
# }
# 
#   datasetHazardSorted <- datasetHazardSorted %>% 
#   #remove participants with low responses rates
#    subset(idx !="1") %>% 
#    subset(idx !="4") 

```


```{r}
#Create summary table

datasetHazardWide <- datasetHazardSorted %>% 
  
  pivot_wider(
    names_from = PilotClips,
    values_from = HazardOnset,
  ) 
  
  datasetHazardWide <- datasetHazardWide %>% 
    select(1:4, 19:ncol(datasetHazardWide)) 

#recode(datasetHazardWide,(NaN = NA))
```

```{r}
#Create a data frame with the number of responses per clip to be mutated later

RespCounts <- data.frame(
  PilotClip1 = sum(!is.na(datasetHazardWide$PilotClip1)),
  PilotClip2 = sum(!is.na(datasetHazardWide$PilotClip2)),
  PilotClip3 = sum(!is.na(datasetHazardWide$PilotClip3)),
  PilotClip4 = sum(!is.na(datasetHazardWide$PilotClip4)),
  PilotClip5 = sum(!is.na(datasetHazardWide$PilotClip5)),
  PilotClip6 = sum(!is.na(datasetHazardWide$PilotClip6)),
  PilotClip7 = sum(!is.na(datasetHazardWide$PilotClip7)),
  PilotClip8 = sum(!is.na(datasetHazardWide$PilotClip8)),
  PilotClip9 = sum(!is.na(datasetHazardWide$PilotClip9)),
  PilotClip10 = sum(!is.na(datasetHazardWide$PilotClip10)),
  PilotClip11 = sum(!is.na(datasetHazardWide$PilotClip11)),
  PilotClip12 = sum(!is.na(datasetHazardWide$PilotClip12)),
  PilotClip13 = sum(!is.na(datasetHazardWide$PilotClip13)),
  PilotClip14 = sum(!is.na(datasetHazardWide$PilotClip14)),
  PilotClip15 = sum(!is.na(datasetHazardWide$PilotClip15)),
  PilotClip16 = sum(!is.na(datasetHazardWide$PilotClip16)),
  PilotClip17 = sum(!is.na(datasetHazardWide$PilotClip17)),
  PilotClip18 = sum(!is.na(datasetHazardWide$PilotClip18)),
  PilotClip19 = sum(!is.na(datasetHazardWide$PilotClip19)),
  PilotClip20 = sum(!is.na(datasetHazardWide$PilotClip20)),
  PilotClip21 = sum(!is.na(datasetHazardWide$PilotClip21)),
  PilotClip22 = sum(!is.na(datasetHazardWide$PilotClip22)),
  PilotClip23 = sum(!is.na(datasetHazardWide$PilotClip23)),
  PilotClip24 = sum(!is.na(datasetHazardWide$PilotClip24))
    ) %>% 
  pivot_longer(cols = 1:24,
               names_to = "ClipNumber",
               values_to = "RespCount")
```


```{r}
#SUmmarise the mean of each Pilot Clip response into a final table

datasetHazardWideSummary <- datasetHazardWide %>% 
  group_by(idx) %>% 
  summarise(PilotClip1 = mean(PilotClip1, na.rm = T),
            PilotClip2 = mean(PilotClip2, na.rm = T),
            PilotClip3 = mean(PilotClip3, na.rm = T),
            PilotClip4 = mean(PilotClip4, na.rm = T),
            PilotClip5 = mean(PilotClip5, na.rm = T),
            PilotClip6 = mean(PilotClip6, na.rm = T),
            PilotClip7 = mean(PilotClip7, na.rm = T),
            PilotClip8 = mean(PilotClip8, na.rm = T),
            PilotClip9 = mean(PilotClip9, na.rm = T),
            PilotClip10 = mean(PilotClip10, na.rm = T),
            PilotClip11 = mean(PilotClip11, na.rm = T),
            PilotClip12 = mean(PilotClip12, na.rm = T),
            PilotClip13 = mean(PilotClip13, na.rm = T),
            PilotClip14 = mean(PilotClip14, na.rm = T),
            PilotClip15 = mean(PilotClip15, na.rm = T),
            PilotClip16 = mean(PilotClip16, na.rm = T),
            PilotClip17 = mean(PilotClip17, na.rm = T),
            PilotClip18 = mean(PilotClip18, na.rm = T),
            PilotClip19 = mean(PilotClip19, na.rm = T),
            PilotClip20 = mean(PilotClip20, na.rm = T),
            PilotClip21 = mean(PilotClip21, na.rm = T),
            PilotClip22 = mean(PilotClip22, na.rm = T),
            PilotClip23 = mean(PilotClip23, na.rm = T),
            PilotClip24 = mean(PilotClip24, na.rm = T)
            ) %>% 
  pivot_longer(cols = 1:24,
               names_to = "ClipNumber",
               values_to = "HazardResponse"
               
               ) %>% 
  #add descriptive columns
  mutate(Hazard = onsetTimes$Hazard) %>% 
  mutate(OriginalOnset = onsetTimes$ClipOnset) %>% 
  mutate(Difference = HazardResponse - OriginalOnset) %>% 
  mutate(RespCount = RespCounts$RespCount) %>% 
  mutate(PercentageResponses = (RespCount / length(unique(datasetHazardWide$idx))) * 100 ) %>% 
  mutate(AcceptReject = (ifelse(PercentageResponses >= 75, 1, 0)))
```


```{r}
#Write final table to excel file
write.xlsx(datasetHazardWideSummary, "Study2ValidationOnsetTimes.xlsx")
```




