---
title: "Study2HPAnalysis"
author: "TGoodge"
date: '2022-11-08'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(splitstackshape)
library(stringr)
library(data.table)
library(dplyr)
library(tidyr)
library(gridExtra)
library(lme4)
library(lmerTest)

```
####DATA WRANGLING#####

```{r}
#Set the folder where the data is stored

#dataFolder = "D:/Study2Data/hp_data/"
dataFolder = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 2/Study2Data/hp_data"

#Create a list of all the csv files in the folder
file_list <- list.files(path = dataFolder, pattern = "..csv$", all.files = TRUE, full.names = TRUE, recursive = TRUE) 
```

```{r}
RawHPDataset <- data.frame()
#loop through all the fills, create a temporary container, remove the first, second and last rows and then add 1 to the trials counter. Then bind it to the dataset
for (file in file_list){
  tempData <- read.csv(file, header = T) %>% 
    slice(c(-1, -2, -23)) 
    tempData$trials_3.thisTrialN <- tempData$trials_3.thisTrialN + 1
  RawHPDataset <- rbind(RawHPDataset, tempData)
}
```

```{r}
#Sorted dataset with relevant columns selected
SortedHPDataset <- RawHPDataset %>% 
  select(participant, video_file, trials_3.thisTrialN, button_resp.rt)


#Remove th e/mp4 tail from the clip number so it can be joined to hazard data table
SortedHPDataset <- SortedHPDataset %>%  separate(video_file, c('ClipNumber', 'del')) %>% 
  select(-3)

SortedHPDataset$Block <- 'Baseline HP'  
SortedHPDataset$Block[SortedHPDataset$trials_3.thisTrialN > 10] <- "Experiment AR" 


SortedHPDataset$ClipNumber[SortedHPDataset$ClipNumber == "PilotClip2"] <- "PilotClip02"
SortedHPDataset$ClipNumber[SortedHPDataset$ClipNumber == "PilotClip3"] <- "PilotClip03"
SortedHPDataset$ClipNumber[SortedHPDataset$ClipNumber == "PilotClip4"] <- "PilotClip04"
SortedHPDataset$ClipNumber[SortedHPDataset$ClipNumber == "PilotClip5"] <- "PilotClip05"
SortedHPDataset$ClipNumber[SortedHPDataset$ClipNumber == "PilotClip6"] <- "PilotClip06"
SortedHPDataset$ClipNumber[SortedHPDataset$ClipNumber == "PilotClip7"] <- "PilotClip07"
SortedHPDataset$ClipNumber[SortedHPDataset$ClipNumber == "PilotClip8"] <- "PilotClip08"
SortedHPDataset$ClipNumber[SortedHPDataset$ClipNumber == "PilotClip9"] <- "PilotClip09"
  


```

```{r}
#Read in onset and offset times

HazardData <- read.csv("C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 2/Study2Data/FinalStudy2HazardSheet.csv")

#Rename clip numbers so there are sequential
HazardData$ClipNumber[HazardData$ClipNumber == "PilotClip2"] <- "PilotClip02"
HazardData$ClipNumber[HazardData$ClipNumber == "PilotClip3"] <- "PilotClip03"
HazardData$ClipNumber[HazardData$ClipNumber == "PilotClip4"] <- "PilotClip04"
HazardData$ClipNumber[HazardData$ClipNumber == "PilotClip5"] <- "PilotClip05"
HazardData$ClipNumber[HazardData$ClipNumber == "PilotClip6"] <- "PilotClip06"
HazardData$ClipNumber[HazardData$ClipNumber == "PilotClip7"] <- "PilotClip07"
HazardData$ClipNumber[HazardData$ClipNumber == "PilotClip8"] <- "PilotClip08"
HazardData$ClipNumber[HazardData$ClipNumber == "PilotClip9"] <- "PilotClip09"
  
```

```{r}
# onsetTimes = read_excel("Study2HazardSheet.xlsx" ) %>% 
#   select(-3)
# 
# onsetTimes$PilotClips[onsetTimes$PilotClips == "PilotClip2"] <- "PilotClip02"
# onsetTimes$PilotClips[onsetTimes$PilotClips == "PilotClip3"] <- "PilotClip03"
# onsetTimes$PilotClips[onsetTimes$PilotClips == "PilotClip4"] <- "PilotClip04"
# onsetTimes$PilotClips[onsetTimes$PilotClips == "PilotClip5"] <- "PilotClip05"
# onsetTimes$PilotClips[onsetTimes$PilotClips == "PilotClip6"] <- "PilotClip06"
# onsetTimes$PilotClips[onsetTimes$PilotClips == "PilotClip7"] <- "PilotClip07"
# onsetTimes$PilotClips[onsetTimes$PilotClips == "PilotClip8"] <- "PilotClip08"
# onsetTimes$PilotClips[onsetTimes$PilotClips == "PilotClip9"] <- "PilotClip09"
```

```{r}

FullHPDataset <- left_join(SortedHPDataset, HazardData, by = "ClipNumber") %>% 
  select(-6,-7)

FullHPDataset$button_resp.rt <-stringr::str_remove_all(FullHPDataset$button_resp.rt,"[\\[\\]]")

FullHPDataset$Condition <- FullHPDataset$participant

FullHPDataset$Condition[as.numeric(str_sub(FullHPDataset$Condition, -1))%%2 == 0] <- "Wider"

FullHPDataset$Condition[as.numeric(str_sub(FullHPDataset$Condition, -1))%%2 == 1] <- "Focused"


```

```{r}
#prep data
RTData <- FullHPDataset 

#RTData$button_resp.rt <-stringr::str_remove_all(RTData$button_resp.rt,"[\\[\\]]")

RTData <- RTData %>% 
  separate_rows(button_resp.rt, sep = ",")

RTData$button_resp.rt <- as.numeric(RTData$button_resp.rt)


```
###Plot number of responses
```{r}
ggplotRT <- function(lm.input) {
  x <- ggplot(lm.input, aes(button_resp.rt, fill = Block, na.rm = T))+
    labs(x = lm.input$ClipNumber)+
    geom_histogram(binwidth = 0.5, colour = 'black', na.rm = T) +
    #xlim(0, lm.input$Offset)+
    geom_vline(xintercept = lm.input$Onset, linetype = "dotted", colour = "black", size = 1.0)
   # geom_density()
  return(x)
}
```
#Number of responses per clip
```{r}
#Split the data frame into individual ones based on each clip
RTList <- split(RTData, f= RTData$ClipNumber)

RTPlots <- lapply(RTList, ggplotRT)

for (p in RTPlots){
  print(p)
}

```


```{r}

#Add Split the condition column into focused and wider for the xperimental condition
RTExpData <- RTData %>% 
  mutate(Condition = if_else(Block != "Control", Condition, Block ))

```

```{r}
RTExpDataSumm <- RTExpData %>%
  group_by(participant, trials_3.thisTrialN, Block, Condition, ClipNumber) %>%
  dplyr::summarise(n = n()) %>%
  group_by(ClipNumber) %>% 
  dplyr::summarise(mean = mean(n),
                   median = median(n),
                   round = round(mean(n)))
```

```{r}

#Create a function over to loop through data and plot it
ggplotExpRT <- function(lm.input) {
  x <- ggplot(lm.input, aes(button_resp.rt, fill = Condition, na.rm = T))+
    labs(x = lm.input$ClipNumber)+
    geom_histogram(binwidth = 0.5, colour = 'black', na.rm = T) +
    #xlim(0, lm.input$Offset)+
    geom_vline(xintercept = lm.input$Onset, linetype = "dotted", colour = "black", size = 1.0)
   # geom_density()
  return(x)
}
```

```{r}

RTExpList <- split(RTExpData, f= RTExpData$ClipNumber)
RTExpPlots <- lapply(RTExpList, ggplotExpRT)

for (p in RTExpPlots){
  print(p)
}

arg_list <- c(RTExpPlots, list(ncol=2))
#jpeg('histogram', width=1024, height=968)
#grid.arrange(grobs = RTExpPlots, ncol = 2, nrow = 4)
#graphics.off()

```

```{r}
RTHazardData <- RTExpData
RTHazardData$Group <- paste(RTHazardData$Block, RTHazardData$Condition, sep=" ")

RTHazardData <- na.omit(RTHazardData) 
RTHazardData$RTStandard <- RTHazardData$button_resp.rt - RTHazardData$Onset

RTHazardData<- RTHazardData[RTHazardData$button_resp.rt <= RTHazardData$Offset ,]

RTHazardData$PreWindow <- 0
RTHazardData$PreWindow <- if_else(RTHazardData$RTStandard > 0, FALSE, TRUE)

RTPreWindowSumm <- RTHazardData %>%
  group_by(ClipNumber) %>%
  dplyr::summarise(n = n(),
            sdRT = sd(RTStandard, na.rm = T))
            

RTHazardData <- RTHazardData[RTHazardData$button_resp.rt >= RTHazardData$Onset -1.0,] #######


table(RTHazardData$PreWindow)
#Remove duplicate responses from each participant, taking only the first one
RTHazardData <-  subset(RTHazardData, !duplicated(subset(RTHazardData, select = c(participant, ClipNumber))))
RTHazardData$Group <- paste(RTHazardData$Block, RTHazardData$Condition, sep=" ")

```

```{r}

# RTHazardDataStrict <- na.omit(RTHazardDataStrict) 
# 
# RTHazardDataStrict$RTStandard <- RTHazardDataStrict$button_resp.rt - RTHazardDataStrict$Onset  
# RTHazardDataStrict$PreWindow <- 0
# RTHazardDataStrict$PreWindow <- if_else(RTHazardDataStrict$RTStandard > 0, FALSE, TRUE)
# 
# RTPreWindowSumm <- RTHazardDataStrict %>% 
#   group_by(Block, PreWindow, Condition) %>% 
#   summarise(n = n(),
#             mean = mean(RTStandard))
# #Remove duplicate responses from each participant, taking only the first one
# RTHazardDataStrict <-  subset(RTHazardDataStrict, !duplicated(subset(RTHazardDataStrict, select = c(participant, ClipNumber))))
```

```{r}

RTPreHazardData<- RTHazardData %>% 
  filter(PreWindow == TRUE)

RTPreHazardDataSum <- RTPreHazardData %>% 
   group_by(Block, Condition, ClipNumber) %>% 
  summarise(n = n(),
            mean = mean(RTStandard),
            sd = sd(RTStandard))
```
```{r}
# RTPostHazardData<- RTHazardData %>% 
#   filter(PreWindow == FALSE) %>% 
#   groupb
#   summarise(sd = sd(RTStandard))
# 
# RTPostHazardDataSum <- RTPostHazardData %>% 
#    group_by(ClipNumber) %>% 
#   summarise(n = n(),
#             mean = mean(RTStandard),
#             sd = sd(RTStandard))
```

```{r}
RTHazardDataCorr <- RTHazardData %>% 
  group_by(Block, Condition) %>% 
  summarise(count = n())
RTHazardDataCorr$Group <- paste(RTHazardDataCorr$Block, RTHazardDataCorr$Condition, sep=" ")


ClipCount <- table(RTHazardData$ClipNumber)

ClipCount

ggplot(RTHazardDataCorr, aes(x = Condition, y = count, fill = Block ))+
  geom_col(position = 'dodge')+
  ylim(0,140)+
  geom_hline(yintercept = 140)


```

```{r}
# RTHazardDataCorr <- RTHazardDataStrict %>% 
#   group_by(Block, Condition) %>% 
#   summarise(count = n())
# RTHazardDataCorr$Group <- paste(RTHazardDataCorr$Block, RTHazardDataCorr$Condition, sep=" ")
# 
# 
# ClipCount <- table(RTHazardData$ClipNumber)
# 
# ClipCount
# 
# ggplot(RTHazardDataCorr, aes(x = Condition, y = count, fill = Block ))+
#   geom_col(position = 'dodge')+
#   ylim(0,140)+
#   geom_hline(yintercept = 140)
# 

```

```{r}
RTHazardDataClip <- RTHazardData %>% 
  group_by(ClipNumber, Block, Condition) %>% 
  summarise(resp = mean(button_resp.rt),
            onset = Onset,
            RT = resp - onset)

RTHazardDataClip <- RTHazardDataClip[!duplicated(RTHazardDataClip),]
RTHazardDataClip$Group <- paste(RTHazardDataClip$Block, RTHazardDataClip$Condition, sep=" ")

```
```{r}
# RTHazardDataClipStrict <- RTHazardDataStrict %>% 
#   group_by(ClipNumber, Block, Condition) %>% 
#   summarise(resp = mean(button_resp.rt),
#             onset = Onset,
#             RT = resp - onset)
# 
# RTHazardDataClipStrict <- RTHazardDataClipStrict[!duplicated(RTHazardDataClipStrict),]
# RTHazardDataClipStrict$Group <- paste(RTHazardDataClipStrict$Block, RTHazardDataClipStrict$Condition, sep=" ")
```

```{r}
ggplot(RTHazardData, aes(x = ClipNumber, y = button_resp.rt, colour = Block))+
   # geom_point(shape = 4, size = 2)+
  geom_boxplot()+
  geom_point(aes(x = ClipNumber, y = Onset), colour = 'black', shape = 4)
   # geom_density(
```


```{r}

# ggplot(RTHazardDataStrict, aes(x = ClipNumber, y = button_resp.rt, colour = Block))+
#    # geom_point(shape = 4, size = 2)+
#   geom_boxplot()+
#   geom_point(aes(x = ClipNumber, y = Onset), colour = 'black', shape = 4)
#    # geom_density(
# 


```

```{r}
ggplotHazRT <- function(lm.input) {
  x <- ggplot(lm.input, aes(RTStandard, fill = Condition, na.rm = T))+
    labs(x = lm.input$ClipNumber, )+
    geom_histogram(binwidth = 0.1, colour = 'black', na.rm = T, position = "stack", show.legend = F)+
    xlim(-2.0, 2.0)+
    ylim(0,7)+
    geom_vline(xintercept = 0, linetype = "dotted", colour = "black", size = 1.0)
   # geom_density()
  return(x)
}
```

```{r}
RTHazardList <- split(RTHazardData, f= RTHazardData$ClipNumber)
RTHazardPlots <- lapply(RTHazardList, ggplotHazRT)

#list2env(RTHazardPlots, envir=globalenv())

for (p in RTHazardPlots){
  print(p)
}

#grid.arrange(grobs = RTHazardPlots, ncol = 2, legend())


```


```{r}
RTHazardSummary <- RTHazardData %>% 
group_by(Condition, Block, ClipNumber) %>% 
  summarise(
    mean = mean(RTStandard)
  ) 


RTOverallSummary <- RTHazardData %>% 
group_by(Block) %>% 
  summarise(
    mean = mean(RTStandard),
    sd = sd(RTStandard)
  ) %>% 
  mutate(Condition = "Overall")


RTGroupSummary <- RTHazardData %>% 
group_by(Condition, Block, ) %>% 
  summarise(
    mean = mean(RTStandard),
    sd = sd(RTStandard)
  )

RTGroupSummary <- rbind(RTGroupSummary, RTOverallSummary)



```

```{r}
PivotRTHazardSummary<- RTHazardSummary %>% 
  pivot_wider(names_from = ClipNumber, values_from =mean)
```

```{r}

#Function for interaction plots
ggplotIntRT <- function(lm.input) {
  x <-  ggplot(lm.input,  aes(x = Block, y = RTStandard, colour = Condition))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  #geom_line() +
  geom_boxplot()+
  labs(x = "Block",
      y = "Mean Reaction Time (s)",
      title = lm.input$ClipNumber, 
      subtitle =  lm.input$Hazard.Location,
      tag = "",)+  
  geom_hline(yintercept = 0,  linetype = "dotted", colour = "black", size = 1.0)
  theme_bw()
  return(x)
}
```

```{r}

#Print out the interaction plots for each clip

RTHazList <- split(RTHazardData, f= RTHazardData$ClipNumber)
RTHazPlots <- lapply(RTHazList, ggplotIntRT)

for (p in RTHazPlots){
  print(p)
}

```

```{r}
ggplot(RTOverallSummary,  aes(x = Block, y = mean))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  #geom_line() +
  geom_line(size = 0.3,) +
  geom_point(size = 4.5 ) +
  labs(x = "Block",
      y = "Mean Reaction Time for hazard windows",
      title = "Overall",
      tag = "")+  
  ylim(-1.0,1.0) +
  #geom_hline(yintercept = 0,  linetype = "dotted", colour = "black", size = 1.0)+
  geom_hline(yintercept = -1.0,  linetype = "solid", colour = "black", size = 1.0)+
#geom_hline(yintercept = -1.0,  linetype = "dotted", colour = "red", size = 1.0)+
  scale_shape(solid = F)+

  theme_bw()



ggsave("OverallRTPlot.png")
```


```{r}
ggplot(RTGroupSummary,  aes(x = Block, y = mean, group = Condition))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  #geom_line() +
  geom_line(size = 0.3, aes(linetype = Condition, colour = Condition)) +
  geom_point (size = 4.5, aes(shape = Condition, colour = Condition), ) +
  labs(x = "Block",
      y = "Mean Reaction Time for hazard windows",
      title = "Overall",
      tag = "")+  
  ylim(-1.0,1.0) +
  geom_hline(yintercept = 0,  linetype = "dotted", colour = "black", size = 1.0)+
  geom_hline(yintercept = -1.0,  linetype = "solid", colour = "black", size = 1.0)+
#geom_hline(yintercept = -1.0,  linetype = "dotted", colour = "red", size = 1.0)+
  scale_shape(solid = F) +

  theme_bw()



ggsave("GroupRTPlot.png")
```

```{r}

interaction.plot(x.factor =  RTGroupSummary$Block,
                 trace.factor = RTGroupSummary$Condition,
                 response = RTGroupSummary$mean,
                 fun = mean,
                 ylim = (c(-1.0,1.0)),
                 xlab = "Block",
                 ylab = "Hazard Perception Reaction time (s)",
                 type= "b",
                 col=c("red","blue", "green"),
                 pch=c(19,17,15),
                 trace.label = "Condition",
                 fixed=T,
                 leg.bty ="o")
  
```


```{r}


ggplot(RTHazardData,  aes(x = Block, y = RTStandard, colour = Condition))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  #geom_line() +
  geom_boxplot()+
  #geom_line(size = 0.3, aes(group = Condition, color = Condition)) +
  geom_hline(yintercept = 0,  linetype = "dotted", colour = "black", size = 1.0)+
  geom_hline(yintercept = -1.0,  linetype = "dotted", colour = "red", size = 1.0)+
  ylim(-1.0,1.5) +

  ylab("Reaction Time difference from Hazard Onset")+
  xlab("Block")+
  theme_bw()
```

```{r}
ANOVA <- aov(RTStandard ~ Condition * Block, data = RTHazardData)
summary(ANOVA)

TukeyPH <- TukeyHSD((ANOVA))

TukeyPH
```

```{r}
RTHazardData <- RTHazardData %>% 
  mutate(
    Condition = as.factor(Condition),
    Block = as.factor(Block)
  ) %>%
  mutate(
    Condition = relevel(Condition, ref = "Wider"),
    Block = relevel(Block, ref = "Baseline HP")
  )

model1 <- lm(RTStandard ~ Condition * Block, data = RTHazardData)
summary(model1)
```

```{r}
RTHazardData <- RTHazardData %>% 
  mutate(
    Condition = as.factor(Condition),
    Block = as.factor(Block)
  ) %>%
  mutate(
    Condition = relevel(Condition, ref = "Focused"),
    Block = relevel(Block, ref = "Experiment AR")
  )

model2 <- lm(RTStandard ~ Condition*Block, data = RTHazardData)
summary(model2)
```

```{r}

library(effects)

plot(allEffects(model1))
plot(predictorEffect("Block", model1))

plot(allEffects(model2))
plot(predictorEffect("Block", model2))

```

```{r}
hats <- as.data.frame(hatvalues(model1))

hats <- hats[order(-hats['hatvalues(model1)']), ]

##hats
```
```{r}
plot(hatvalues(model1), type = 'h')
```


```{r}
#list2env(RTHazardList, envir = globalenv())

```

```{r}
ClipAnova <-function(lm.input){
  a <- aov(RTStandard ~ Condition * Block, data = lm.input)
  summary(a)
  TukeyHSD(a)
  
}
#lapply(RTHazList, ClipAnova)

```

```{r}
NullModel <- lmer(data = RTHazardData, formula = button_resp.rt ~  (1|participant))

summary(NullModel)

```

```{r}
Model1 = lmer(data = RTHazardData, formula = button_resp.rt ~ Block + Condition + Block * Condition + (1|participant))

summary(Model1)
```


```{r}
anova(NullModel, Model1)


#anova(Model1)
```

```{r}
RTIntModel = lmer(data = RTHazardData, formula = RTStandard ~ Block + Condition + Block*Condition + (1|participant) + (1|ClipNumber))

RTMainModel = lmer(data = RTHazardData, formula = RTStandard ~ Block + Condition + (1|participant) + (1|ClipNumber))
```


```{r}
anova(RTMainModel, NullModel)
```


```{r}
summary(RTMainModel)

summary(RTIntModel)
```


```{r}
anova(RTIntModel, RTMainModel)

```


```{r}
plot(predictorEffect("Block", RTIntModel))
```



```{r}
library(report)
results <- report(RTMainModel, CI = 95)

print(results)
```

```{r}
##################Response Count#############################
```

```{r}
#Split the column with all responses into multiple columns per participants
RespCountDataset <-  cSplit(FullHPDataset, "button_resp.rt", sep=",") 
TotalResponse <- sum(str_detect(colnames(RespCountDataset), 'button_resp.rt'))

RespCountDataset$RespCount <- TotalResponse - rowSums(is.na(RespCountDataset[,9:ncol(RespCountDataset)]))
  
RespCountDataset <- RespCountDataset %>% 
    mutate(Condition = if_else(Block != "Control", Condition, Block )) %>% 
  select(c(1:8, ncol(RespCountDataset))) %>% 
  subset(participant !="P21")
#remove P21 for pressing too many times

```

```{r}
ggplotRespCount <- function(lm.input) {
  x <- ggplot(lm.input, aes(fill = Condition))+
    geom_histogram(aes(RespCount), position = "dodge", colour = "black", binwidth = 1.0)+
    labs(x = lm.input$ClipNumber)
  return(x)
}
```

```{r}

RespCountOverall <- RespCountDataset %>% 
  group_by(Condition) %>% 
  dplyr::summarise(RespCount = mean(RespCount))

RespCountGroup <- RespCountDataset %>% 
  group_by(ClipNumber, Condition)  %>%  
  summarise(RespCount = mean(RespCount))

```

```{r}
PivotRespCountHazardSummary<- RespCountGroup %>% 
  pivot_wider(names_from = ClipNumber, values_from = RespCount)
```


```{r}
RespCountList <- split(RespCountDataset, f= RespCountDataset$ClipNumber)
RespCountPlots <- lapply(RespCountList, ggplotRespCount)

for (p in RespCountPlots){
  print(p)
}
```
```{r}
RespIntModel = lmer(data = RespCountDataset, formula = RespCount ~ Block*Condition + (1|participant) + (1|ClipNumber))

summary(RespIntModel)

```
```{r}
RTHazardStrictSummary <- RTHazardDataStrict %>% 
group_by(Condition, Block, ClipNumber) %>% 
  summarise(
    mean = mean(button_resp.rt)
  ) 

RTOverallStrictSummary <- RTHazardDataStrict %>% 
group_by(Condition, Block, ) %>% 
  summarise(
    mean = mean(button_resp.rt),
    sd = sd(button_resp.rt)
  ) 


table(RTHazardDataStrict$ClipNumber)

```

```{r}
PivotRTHazardStrictSummary<- RTHazardStrictSummary %>% 
  pivot_wider(names_from = ClipNumber, values_from =mean) 



```


```{r}
ggplot(RTOverallStrictSummary,  aes(x = Block, y = mean, colour = Condition, na.omit()))+
  #geom_point (size = 4.5, aes(color = Condition), shape = 8) +
  #geom_line() +
  geom_line(size = 0.3, aes(group = Condition, color = Condition)) +
  geom_point (size = 4.5, aes(color = Condition), shape = 2) +
  labs(x = "Block",
      y = "Mean Reaction Time for hazard windows",
      title = "Overall",
      tag = "")+  
  ylim(-1.0,1.0) +
  geom_hline(yintercept = 0,  linetype = "dotted", colour = "black", size = 1.0)+
  geom_hline(yintercept = -1.0,  linetype = "dotted", colour = "red", size = 1.0)+


  theme_bw()
```

