---
title: "Study5ARTaskAnalysis"
author: "TGoodge"
date: "2024-04-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(stringr)
library(rstatix)
library(ggplot2)


```

```{r}
library(RColorBrewer)

base_palette <- brewer.pal(n = 12, name = "Paired")
custom_palette <- c(
  base_palette[3], base_palette[4],   # Group 2: 2 similar colors
    base_palette[1], base_palette[2],   # Group 1: 2 similar colors

  "#F45B5B", base_palette[6], "#A50F15",  # Group 3: 3 similar colors
  base_palette[8]                     # Group 4: 1 color
)


S5_palette <- c(base_palette[3],base_palette[1],"#F45B5B", base_palette[8])
S6_palette <- c(base_palette[4], base_palette[2],base_palette[6], "#A50F15")

#scale_fill_manual(values = S5_palette) +


# Print the custom palette to verify
print(custom_palette)
#"#A6CEE3" "#1F78B4" "#B2DF8A" "#33A02C" "#FB9A99" "#E31A1C" "#FDBF6F" "#FF7F00" "#F45B5B
```

```{r}

dataFolder = "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 5/Study5Data/AR Task"

fileList <- list.files(path = dataFolder, pattern = "..txt$", all.files = TRUE, full.names = TRUE, recursive = TRUE) 
```

```{r}
#Loop through the files and create one large dataset
scoreDatasetRaw <- data.frame() 
  
scoreDatasetRaw <- scoreDatasetRaw %>% 
  mutate("ID") %>% 
  mutate("DiamondProportion") %>% 
  mutate("EmeraldProportion") %>% 
  mutate("Average Proportion")
# datasetRaw[nrow(datasetRaw) + 1,] = c(1,1,1)
  


for (file in fileList)
{
    tempData <- read.csv(file, header = F)
    tempData["ID"] = substr(file, start =84,stop = 100)
    
    
    nlast <- 1
    DiamondScore <- as.numeric(substr(tempData[1,1], nchar(tempData[1,1]) - nlast, nchar(tempData[1,1])))
    EmeraldScore <- as.numeric(substr(tempData[2,1], nchar(tempData[2,1]) - nlast, nchar(tempData[2,1])))
  
    mlast <- 2
    DiamondTotal <- as.numeric(substr(tempData[3,1], nchar(tempData[3,1]) - mlast, nchar(tempData[3,1])))
    EmeraldTotal <- as.numeric(substr(tempData[4,1], nchar(tempData[4,1]) - mlast, nchar(tempData[4,1])))
    
    DiamondProportion = DiamondScore/ DiamondTotal * 100
    EmeraldProportion = EmeraldScore/ EmeraldTotal * 100
    
    AverageProportion = (DiamondProportion + EmeraldProportion) / 2
    
    scoreDatasetRaw[nrow(scoreDatasetRaw) + 1,] = c(tempData[1,2],DiamondProportion,EmeraldProportion, AverageProportion)
  
}



```


```{r}

scoreDatasetRaw$`"DiamondProportion"` <- as.numeric( scoreDatasetRaw$`"DiamondProportion"`)
scoreDatasetRaw$`"EmeraldProportion"` <- as.numeric( scoreDatasetRaw$`"EmeraldProportion"`)
scoreDatasetRaw$`"Average Proportion"` <- as.numeric( scoreDatasetRaw$`"Average Proportion"`)

scoreDatasetRaw[c('Ppt','Block')] <- str_split_fixed(scoreDatasetRaw$`"ID"`, 'S5', 4)

```

```{r}

summaryScoreDataset <-scoreDatasetRaw %>% 
  group_by(Block) %>% 
  summarise(mean = mean(`"Average Proportion"`, na.rm = T),
            sd = sd(`"Average Proportion"`, na.rm = T),
            meanDiamond = mean(`"DiamondProportion"`, na.rm = T),
            sdDiamond = sd(`"DiamondProportion"`, na.rm=T),
            meanEmerald = mean(`"EmeraldProportion"`,na.rm=T),
            sdEmerald = sd(`"EmeraldProportion"`, na.rm = T))
```

```{r}
scoreDataset <- scoreDatasetRaw 

  colnames(scoreDataset) <- c('text', 'Diamond', 'Emerald', 'AverageProportion', 'ID', 'Condition')
  
  
scoreDataset$ID <- substring(scoreDataset$ID,2,5)

write.csv(scoreDataset, "C:/Users/thoma/OneDrive - University of Glasgow/Desktop/Study 6/ComparisonData/S5NDRT.csv", row.names=FALSE)

```



```{r}
ggplot(summaryScoreDataset, aes(x = Block, y = mean, fill = Block))+
  geom_col()+
  geom_errorbar(aes(ymin = mean - (sd/2), ymax = mean + (sd/2)),
                width = 0.2, 
                position = position_dodge(0.9))
```



```{r}
scoreAnova <- aov(`"Average Proportion"` ~ Block, data = scoreDatasetRaw)
summary(scoreAnova)

diaAnova <- aov(`"DiamondProportion"` ~ Block, data = scoreDatasetRaw)
summary(diaAnova)

emeAnova <- aov(`"EmeraldProportion"` ~ Block, data = scoreDatasetRaw)
summary(emeAnova)

```
```{r}


scoreDataset %>% 
  group_by(Condition) %>% 
  identify_outliers(AverageProportion)

scoreDataset %>% 
  group_by(Condition) %>% 
  shapiro_test(AverageProportion)



ggqqplot(scoreDataset, "AverageProportion", facet.by = "Condition")
```

```{r}


AP.aov <- anova_test(data = scoreDataset, dv = AverageProportion, wid = ID, within = Condition)

get_anova_table(AP.aov)

APpwc <- scoreDataset %>% 
  pairwise_t_test(AverageProportion ~ Condition, paired = TRUE,
                  p.adjust.method = "bonferroni")

APpwc <- APpwc %>%  add_xy_position(x = "Condition")
APpwc


APbxp <- ggboxplot(scoreDataset, x = "Condition", y = "AverageProportion", add = "point")

APbxp + 
  #stat_pvalue_manual(pwc) +
  labs(
    subtitle = get_test_label(AP.aov, detailed = TRUE),
    caption = get_pwc_label(APpwc)
  )


```







#Rankings
```{r}
library(ggplot2)
library(tidyr)
library(dplyr)

# Data as a tibble
data <- tribble(
  ~Condition, ~`1`, ~`2`, ~`3`, ~`4`, ~Total,
  "Avatar",   6,    7,    3,    9,    25,
  "Visual",      1,    8,    9,    7,    25,
  "NDRT",     2,    8,   10,    5,    25,
  "Control", 16,    5,    1,    3,    25
)

# Pivot data to long format
data_long <- data %>%
  select(-Total) %>%
  pivot_longer(cols = `1`:`4`, names_to = "Number", values_to = "Frequency") %>% 
    mutate(Condition = factor(Condition, levels = c( "Visual", "Avatar","NDRT", "Control")))

# Plotting
S5RankingPlot <- ggplot(data_long, aes(x = Condition, y = Frequency, fill = Number)) +
  geom_col(position = "fill", width = 0.5) +  # Stacked column with relative frequencies
  scale_y_continuous(labels = scales::percent_format()) +  # Convert y-axis to percentages
  labs(title = "Preference Ranking for each Condition",
       x = "Condition",
       y = "Proportion of Total",
       fill = "Ranking Position") +
  scale_fill_manual(values = S5_palette) +  # Custom colors
  coord_flip() +  # Flip the plot to horizontal
  theme_minimal()

S5RankingPlot

ggsave(filename = "S5RankingPlot.png",
       plot = S5RankingPlot,
       device = png)



```
```{r}

```

