---
title: "Study1_Demogs"
output: html_document
date: '2022-04-24'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = 'D:/Qualtrics_Data/Study1/Demographics', echo = TRUE)
```

```{r}
  library(tidyverse)
  library(readr)
  library(janitor)

```

```{r}
#Set the working directory of the data ***HARD CODED ***
 setwd("D:/Qualtrics_Data/Study1/Demographics")

```

```{r}
  list.files()
  #Read in the data
  DemogDataRaw <- read.csv("D:/Qualtrics_Data/Study1/Demographics/TGExperiment1_DemogData.csv") %>%  
    select(starts_with('Q')) 
```
```{r}
#Change the first row into column headers
DemogDataOrg <- row_to_names(DemogDataRaw, row_number = 1)
#Remove pilot data and consent form columns
DemogDataOrg <- DemogDataOrg[-c(1:7),-c(1:7)]
  
  DemogDataOrg[DemogDataOrg == 'Po3g'] <- 'P03G'
  DemogDataOrg[DemogDataOrg == 'P04'] <- 'P04L'
  DemogDataOrg[DemogDataOrg == '13g'] <- 'P13G'
  DemogDataOrg[DemogDataOrg == '16l'] <- 'P16L'
  
  
  DemogDataOrg[DemogDataOrg == 'female'] <- 'Female'
  DemogDataOrg[DemogDataOrg == 'Man'] <- 'Male'
  
  DemogDataOrg[DemogDataOrg == '1hour'] <- 1
  DemogDataOrg[DemogDataOrg == 'Do not play at all'] <- 0
  DemogDataOrg[DemogDataOrg == 'Not much. But whenever i go to my friends house every couple months'] <- 0
  
DemogDataOrg <- DemogDataOrg %>% 
  rename(Age = `What is your age?`) %>% 
  rename(Gender = `Which gender do you identify with?`) %>% 
  rename(ARExp = `Have you had much experience with Augmented Reality (AR) before?`) %>% 
  rename(ARHeadsets = `Which of these AR devices, if any, have you interacted with before? - Selected Choice`) %>% 
  rename(ARHeadsetsText = `Which of these AR devices, if any, have you interacted with before? - Other (Please describe) - Text`) %>% 
  rename(VRExp = `Have you had much experience with Virtual Reality (VR) before?`) %>% 
  rename(VRExpHeadset = `Which of these VR devices, if any, have you interacted with before? - Selected Choice`) %>%
  rename(VRExpHeadsetText = `Which of these VR devices, if any, have you interacted with before? - Other (Please describe) - Text`) %>% 
  rename(VideoGamesTime = `Roughly how many hours do you play video games for in an average week?`) %>% 
  rename(MotionSickness = `Do you have any history of motion sickness? - Selected Choice`) %>% 
  rename(MotionSicknessText = `Do you have any history of motion sickness? - Other (Please describe) - Text`)

```



```{r}
DemogDataOrg<- DemogDataOrg %>%
  mutate(ID = substr(`Enter your Participant ID:`,
                     start = 1,
                     stop = 3)) %>%
  mutate(Condition = substr(`Enter your Participant ID:`,
                            start = 4,
                           stop  = 5))

DemogDataOrg<- DemogDataOrg[-1] %>%
  select(c(ID, Condition, 1:12)) 

DemogDataOrg$Condition = toupper(DemogDataOrg$Condition)
DemogDataOrg$Age = as.numeric(DemogDataOrg$Age)
DemogDataOrg$VideoGamesTime = as.numeric(DemogDataOrg$VideoGamesTime)

```

```{r}
DemogSummary <- DemogDataOrg %>% 
  
  group_by(Condition) %>% 
  summarise(
  n = n(),
  AgeMean = mean(Age),
  AgeSD = sd(Age),
  Male = sum(Gender == 'Male'),
  Female = sum(Gender == "Female"),
  meanVG = mean(VideoGamesTime)
  )   
```


```{r}
ARExp <- table(DemogDataOrg$ARExp)
ARExpType <- table(DemogDataOrg$ARHeadsets)
VRExp <- table(DemogDataOrg$VRExp)
VRExpType <- table(DemogDataOrg$VRExpHeadset)

View(ARExp) 
View(VRExp) 



```

