---
title: "NASATLX_Qualtrics"
output: html_document
date: '2022-03-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(janitor)
library(car)
library(emmeans)
```


```{r}
setwd("D:/Qualtrics_Data/Study1/NASATLX")
#Read in the data
TLXdataRaw <- read.csv("TGExp1NasaTLX.csv") %>%

# Tidy the data - select scores,
  select(starts_with('Q'))
  TLXdataOrg <- TLXdataRaw[-c(1:2),]
  colnames(TLXdataOrg) <- c('Ppt_ID','Block', 'Mental Demand', 'Physical Demand', 'Temporal Demand', 'Overall Performance', 'Effort', 'Frustration')
  TLXdataOrg <- TLXdataOrg[-c(1:2),]
  #Convert columns with ratings in to numeric
  TLXdataOrg[3:8] = lapply(TLXdataOrg[3:8], FUN = function(y){as.numeric(y)})
  
  #Remove Pilot data rows
  TLXdataOrg <- TLXdataOrg[-c(1:9),]
  
  #Change incorrect entries
  TLXdataOrg[TLXdataOrg == 'P04'] <- 'P04L'
  TLXdataOrg[TLXdataOrg == 'P118'] <- 'P11G'
  TLXdataOrg[TLXdataOrg == '13g'] <- 'P13G'
  TLXdataOrg[TLXdataOrg == 'G19p'] <- 'P19G'
  TLXdataOrg[TLXdataOrg == '21g'] <- 'P21G'
  

```
```{r}
#Reorganise the columns

#Split up the IDs and groups
TLXdataOrg<- TLXdataOrg %>%
    mutate(ID = substr(Ppt_ID,
                     start = 1,
                     stop = 3)) %>%
  mutate(Condition = substr(Ppt_ID,
                            start = 4,
                           stop  = 5))
#Rearrange the columns and remove extra ID column
TLXdataOrg <- TLXdataOrg[,-1] %>% 
  select(c(ID, Condition, 1:7))

#Change the conditions to upper case and remove whitespace

TLXdataOrg[,2] = toupper(TLXdataOrg[,2]) %>% 
  trimws(which = c("both"))

  TLXdataOrg[TLXdataOrg == "G"] <- "Global"
  TLXdataOrg[TLXdataOrg == "L"] <- "Local" 


#Convert to wrangled dataset
TLXdata <- TLXdataOrg

```

###Need to choose a weighting method and work out how to calculate it!


```{r}
# #Condition the data and summarise the descriptives
# TLXWeighted <- TLXdata 
# 
# TLXWeighted$`Mental Demand` <- TLXWeighted$`Mental Demand` * 3
# TLXWeighted$`Physical Demand` <- TLXWeighted$`Physical Demand` * 0
# TLXWeighted$`Temporal Demand` <- TLXWeighted$`Temporal Demand` * 5
# TLXWeighted$`Overall Performance` <- TLXWeighted$`Overall Performance` * 1
# TLXWeighted$Frustration <- TLXWeighted$Frustration*3
# TLXWeighted$Effort <- TLXWeighted$Effort * 3
# 
# TLXWeighted <- TLXWeighted %>% 
#   mutate(Total = 
#            TLXWeighted$`Mental Demand` +
#            TLXWeighted$`Physical Demand`+
#            TLXWeighted$`Temporal Demand`+
#            TLXWeighted$`Overall Performance` +
#            TLXWeighted$Frustration +
#            TLXWeighted$Effort
#            )
#   


```



```{r}

TLXdataSumm <- TLXdata %>% 
  
  group_by(Block, Condition) %>% 
  summarise(
    n = n(),
    Mental_mean = mean(`Mental Demand`),
    Physical_mean = mean(`Physical Demand`),
    Temporal_mean = mean(`Temporal Demand`),
    Performance_mean = mean(`Overall Performance`),
    Frustration_mean = mean(Frustration),
    Effort_mean = mean(Effort)
    
  )


```

```{r}
ggplot(TLXdata, aes(Condition, `Mental Demand`, fill = Block ))+
  geom_violin(alpha = 0.5)+
  ylim(0,100)+
  labs(title = "Mental Demand")

ggplot(TLXdata, aes(Condition, `Physical Demand`, fill = Block ))+
  geom_violin(alpha = 0.5)+
  ylim(0,100)+
    labs(title = "Physical Demand")

ggplot(TLXdata, aes(Condition, `Temporal Demand`, fill = Block ))+
  geom_violin(alpha = 0.5)+
  ylim(0,100)+
    labs(title = "Temporal Demand")

ggplot(TLXdata, aes(Condition,`Overall Performance`, fill = Block ))+
  geom_violin(alpha = 0.5)+
  ylim (100,0)+
    labs(title = "Overall Performance (Inverted)")

ggplot(TLXdata, aes(Condition, Effort, fill = Block ))+
  geom_violin(alpha = 0.5)+
  ylim (0,100)+
    labs(title = "Effort")
  
ggplot(TLXdata, aes(Condition, Frustration, fill = Block ))+
  geom_violin(alpha = 0.5)+
  ylim (0,100)+
    labs(title = "Frustration")





```
```{r}

interaction.plot(x.factor = TLXdata$Block,
                 trace.factor = TLXdata$Condition,
                 response = TLXdata$`Mental Demand`,
                 fun = mean,
                 type = "b",
                 col = c("red", "blue"),
                 pch = c(19,17),
                 trace.label = "Mental Demand",
                 fixed = T,
                 leg.bty="o"
                 )

interaction.plot(x.factor = TLXdata$Block,
                 trace.factor = TLXdata$Condition,
                 response = TLXdata$`Physical Demand`,
                 fun = mean,
                 type = "b",
                 col = c("red", "blue"),
                 pch = c(19,17),
                 trace.label = "Physical Demand",
                 fixed = T,
                 leg.bty="o"
                 )
interaction.plot(x.factor = TLXdata$Block,
                 trace.factor = TLXdata$Condition,
                 response = TLXdata$`Temporal Demand`,
                 fun = mean,
                 type = "b",
                 col = c("red", "blue"),
                 pch = c(19,17),
                 trace.label = "Temporal Demand",
                 fixed = T,
                 leg.bty="o"
                 )

interaction.plot(x.factor = TLXdata$Block,
                 trace.factor = TLXdata$Condition,
                 response = TLXdata$`Overall Performance`,
                 fun = mean,
                 type = "b",
                 col = c("red", "blue"),
                 pch = c(19,17),
                 trace.label = "Overall Performance",
                 fixed = T,
                 leg.bty="o"
                 )

interaction.plot(x.factor = TLXdata$Block,
                 trace.factor = TLXdata$Condition,
                 response = TLXdata$Effort,
                 fun = mean,
                 type = "b",
                 col = c("red", "blue"),
                 pch = c(19,17),
                 trace.label = "Effort",
                 fixed = T,
                 leg.bty="o"
                 )


interaction.plot(x.factor = TLXdata$Block,
                 trace.factor = TLXdata$Condition,
                 response = TLXdata$Frustration,
                 fun = mean,
                 type = "b",
                 col = c("red", "blue"),
                 pch = c(19,17),
                 trace.label = "Frustration",
                 fixed = T,
                 leg.bty="o"
                 )


```




```{r}

MD_Aov = lm(`Mental Demand` ~ Block + Condition + Block:Condition, data = TLXdata) 
print("Mental Demand")

Anova(MD_Aov,
      type = "II")

print("Physical Demand")
PD_Aov = lm(`Physical Demand` ~ Block + Condition + Block:Condition, data = TLXdata) 

Anova(PD_Aov,
      type = "II")

TD_Aov = lm(`Temporal Demand` ~ Block + Condition + Block:Condition, data = TLXdata) 
print("Temporal Demand")

Anova(TD_Aov,
      type = "II")

OP_Aov = lm(`Overall Performance` ~ Block + Condition + Block:Condition, data = TLXdata) 
print("Overall Performance")

Anova(OP_Aov,
      type = "II")

EF_Aov = lm(Effort ~ Block + Condition + Block:Condition, data = TLXdata) 
print("Effort")

Anova(EF_Aov,
      type = "II")

FR_Aov = lm(Frustration ~ Block + Condition + Block:Condition, data = TLXdata)
print("Frustration")

Anova(FR_Aov,
      type = "II")
```


```{r}
MDmarginal = emmeans(MD_Aov, ~Block:Condition)
pairs(MDmarginal, adjust="tukey")
```


```{r}
PDmarginal = emmeans(PD_Aov, ~Block:Condition)
pairs(PDmarginal, adjust="tukey")

```


```{r}
TDmarginal = emmeans(TD_Aov, ~Block:Condition)
pairs(TDmarginal, adjust="tukey")

```

```{r}
OPmarginal = emmeans(OP_Aov, ~Block:Condition)
pairs(OPmarginal, adjust="tukey")

```

```{r}
EFmarginal = emmeans(EF_Aov, ~Block:Condition)
pairs(EFmarginal, adjust="tukey")

```

```{r}
FRmarginal = emmeans(FR_Aov, ~Block:Condition)
pairs(FRmarginal, adjust="tukey")

```

