---
title: "ReactionTimeAnalysisScript"
output: html_document
date: '2022-03-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(stringr)
library(car)
library(ggpubr)
library(lme4)
library(lmerTest)
library(emmeans)
```


```{r}
### Read in the Data Files ###

#set the working directory to the data folder
setwd("D:/PsychoPyExperiments/Study 1 GoNoGo/")

#Define the filepath for where the data is coming from
dataFolder <- "D:/PsychoPyExperiments/Study 1 GoNoGo/RTData"

#Create a list of all the datafiles in the folder, and then convert to a list object - needs full names for the file path
file_list <- list.files(path = dataFolder, pattern = ".csv$", all.files = TRUE, full.names = TRUE, recursive = TRUE)

```

```{r}
#Loop through the files and create one large dataset
datasetRaw <- data.frame()

for (i in 1:length(file_list)){
  temp_data <- assign(paste(substr(file_list[i],26,29)),  
              read.csv(paste0(file_list[i])))
  temp_data <- temp_data[-c(1:12,103),]
  
  datasetRaw <- rbind(datasetRaw, temp_data)

}

#Change a data naming error
datasetRaw[datasetRaw == 'P04'] <- 'P04L'
colnames(datasetRaw)[colnames(datasetRaw) == "ï..cue_file"]<- "Cue"

```


```{r}
#Tidy up the large datasat with the block, ID and Condition
dataset <- datasetRaw %>% select(1,15,19,30,31,34,39)
dataset<- dataset %>%
  mutate(ID = substr(participant,
                     start = 1,
                     stop = 3)) %>%
  mutate(Condition = substr(participant,
                            start = 4,
                           stop  = 5))
# Remove and reorganise columns
dataset <- dataset[,-7] %>%
  select(c(ID, Condition, 1:6))

#Convert the two colums with block number into one label
  dataset$Block1.thisRepN <- ifelse(grepl("[0-9]", dataset$Block1.thisRepN), " Cognitive Only", "")
  dataset$Block2.thisRepN <- ifelse(grepl("[0-9]", dataset$Block2.thisRepN), "Dual Cognitive-AR", "")
  
  dataset <-dataset %>% 
    mutate( Block =  paste(dataset$Block1.thisRepN, 
                                    dataset$Block2.thisRepN)) %>% 
    select(-c(4,5))
  
  
dataset[dataset== 'G'] <- 'Wider'
dataset[dataset== 'L'] <- 'Focused'



```


```{r}
#Create a dataset with only the RT data for the target stimulus
  datasetRT <- dataset %>% 
  rename("ReactionTime" = "Block_resp.rt") %>% 
# #   #Remove all NA values
  drop_na(ReactionTime)
# Delete all rows where the stimulus isn't red ( Participants were not correct)
datasetRT <- datasetRT[!(datasetRT$Block_resp.corr == 0),]

datasetRT <- datasetRT %>% 
  mutate(
    Condition = as.factor(Condition),
    Block = as.factor(Block)
  ) 


levels(datasetRT$Block)



```




```{r}
#Summarise the RT data by Condition and Group
datasetMeanRT <- datasetRT %>% 
 group_by(Condition, Block) %>% 

  summarise(
    n = n(),
    avg = mean(ReactionTime, na.rm = T),
    sd_total = sd(ReactionTime, na.rm = T) 
        ) 



```

```{r}

ggplot(datasetRT, aes(reorder(Block, ReactionTime), ReactionTime,) ) +
  geom_violin(aes(x = Block,  y = ReactionTime, colour = Condition, fill = Condition))
 

```
```{r}
datasetMeanRT %>% 
  ggplot(aes(reorder(Block, avg), avg, ))+
  geom_line(size = 0.3, aes(group = Condition, color = Condition)) +
  geom_point (size = 4.5, aes(color = Condition), shape = 2) +
  labs(x = "Block",
      y = "Mean Reaction Time (s)",
      tag = "",)+
      

      ylim(0,1)+
  theme_bw()

```
```{r}
interaction.plot(x.factor =  datasetMeanRT$Block,
                 trace.factor = datasetMeanRT$Condition,
                 response = datasetMeanRT$avg,
                 fun = mean,
                 ylim = (c(0.3,0.8)),
                 xlab = "Block",
                 ylab = "Reaction time (s)",
                 type= "b",
                 col=c("red","blue"),
                 pch=c(19,17,15),
                 trace.label = "Condition",
                 fixed=T,
                 leg.bty ="o")
```


```{r}

RTAovInt = aov(ReactionTime ~ Condition * Block, data = datasetRT) 

RTAovIntLM = lm(ReactionTime ~ Condition * Block, data = datasetRT) 
summary(RTAovIntLM)

summary(RTAovInt)
```

```{r}

TukeyPH <- TukeyHSD((RTAovInt))

TukeyPH
```

```{r}
RTLM = lm(ReactionTime ~ Condition + Block + Condition:Block, data = datasetRT) 

Anova(RTLM,
      type = "II")

RTmarginal = emmeans(RTLM, ~Condition:Block)
pairs(RTmarginal, adjust="tukey")
```

```{r}

datasetCorr <- dataset %>% 
 group_by(ID, Block) %>% 
  mutate(PercentCorrect = (sum(Block_resp.corr) / n() )* 100
    ) 

  datasetCorr <- datasetCorr %>% 
  group_by(ID, Block, Condition, PercentCorrect) %>% 
    summarise()
  
  datasetCorrSumm <- dataset %>% 
 group_by(Condition, Block) %>% 
  summarise(
    n =n(),
    Correct = (sum(Block_resp.corr) / n() )* 100,
    Incorrect = 100 -(sum(Block_resp.corr) / n() )* 100
    )



```


```{r}

CorrAovInt = aov(PercentCorrect ~ Condition * Block, data = datasetCorr) 
summary(CorrAovInt)

```
```{r}
NullModel <- lmer(ReactionTime ~ 1 + (1|ID) + Condition, data = datasetRT)

summary(NullModel)

```
```{r}
RTModelNull = lmer(data = datasetRT, formula =  ReactionTime ~ (1|ID))
summary(RTModelNull)
```

```{r}

RTModel1 = lmer(data = datasetRT, formula = ReactionTime ~ Condition*Block + (1|ID))
summary(RTModel1)
anova(RTModelNull, RTModel1)
```
```{r}
RTModel2 = lmer(data = datasetRT, formula = ReactionTime ~ Block + Condition + (1|ID))
summary(RTModel1)

```
```{r}
anova(RTModel1, RTModel2)
```


```{r}
library(effects)
plot(predictorEffect("Block", RTModel1))
```



```{r}

results <- report(RTModel1, CI = 95)

print(results)
```
```{r}
RTModel2 = lmer(data = datasetRT, formula = ReactionTime ~Condition*Block + (1|ID) + (1|Block))
summary(RTModel2)

```


```{r}

plot(predictorEffect("Block", RTModel1), 
     title = "",
     ylab = "Reaction time",
 
) 

```
```{r}
###################   SIGNAL DETECTION ANALYSIS   ###############################
```


```{r}
datasetSD <- dataset %>% 
  rename("ReactionTime" = "Block_resp.rt")
```


```{r}
datasetSD[datasetSD== 'images/StopIcon.png'] <- 'Go'
datasetSD[datasetSD== 'images/OrangeIcon.png'] <- 'NoGo'
datasetSD[datasetSD== 'images/YellowIcon.png'] <- 'NoGo'

datasetSD <- datasetSD %>% 
  mutate(SigDet = ifelse(grepl("[0-9]", datasetSD$ReactionTime) & datasetSD$Cue == "Go", "Hit", 
                    ifelse(grepl("[0-9]", datasetSD$ReactionTime) & datasetSD$Cue == "NoGo", "FA",
                      ifelse(is.na(datasetSD$ReactionTime) & datasetSD$Cue == "Go", "Miss",
                        ifelse(is.na(datasetSD$ReactionTime) & datasetSD$Cue == "NoGo", "CR", ""
                         ))))) #%>% 
 # mutate(SigDet = ifelse(grepl("[0-9]", datasetSD$ReactionTime) & datasetSD$Cue == "NoGo", "FA","")) 
 # mutate(SigDet = ifelse(is.na(datasetSD$ReactionTime)) & datasetSD$Cue == "Go", "Miss","")
  #dataset$Block1.thisRepN <- ifelse(grepl("[0-9]", dataset$Block1.thisRepN), "Cognitive Only", "")


```

```{r}

library(psycho)

datasetSDSumm <- datasetSD %>% 
  group_by(ID, SigDet, Block, Condition) %>% 
  
  summarise(
  Count = n(),
  ) 

datasetSDSumm <- datasetSDSumm %>% 
  pivot_wider(names_from = SigDet, values_from = Count)

datasetSDSumm[is.na(datasetSDSumm)] <- 0

indices <- psycho::dprime(datasetSDSumm$Hit, datasetSDSumm$FA,datasetSDSumm$Miss, datasetSDSumm$CR)

datasetSDSumm <- cbind(datasetSDSumm, indices) 




```


```{r}
datasetSDSummary <- datasetSDSumm %>% 
  group_by(Block, Condition) %>% 
  summarise(n = n(),
            CR = mean(CR),
            Hit = mean(Hit),
            Miss= mean(Miss),
            FA = mean(FA)
            
            )
```


```{r}
ggplot(data = datasetSDSummary)+
  geom_col(aes(Block, CR,)) +
  geom_col(aes(Block, FA))
   geom_point(aes(Block, Hit, colour = Condition)) +
   geom_point(aes(Block, Miss, colour = Condition)) +
   geom_point(aes(Block, FA, colour = Condition)) +
  labs(x = "Block",
      y = "Mean Reaction Time (s)")+
  theme_bw()

```


```{r}
SDCRModel <- lmer(data = datasetSDSumm, formula = CR ~ Block+Condition + (1|ID))
SDCRModel2 <- lmer(data = datasetSDSumm, formula = CR ~ Block * Condition + (1|ID))
anova(SDCRModel, SDCRModel2)
summary(SDCRModel2)

summary(SDCRModel)
```
```{r}
SDCRresults <- report(SDCRModel2, CI = 95)

print(SDCRresults)
```
```{r}
plot(predictorEffect("Block", SDCRModel2), 
     title = "",
     ylab = "Reaction time",
 
) 
```


```{r}
SDHitModel <- lmer(data = datasetSDSumm, formula = Hit ~ Condition +Block + (1|ID))

SDHitModel2 <- lmer(data = datasetSDSumm, formula = Hit ~ Condition *Block + (1|ID))

anova(SDHitModel, SDHitModel2)

summary(SDHitModel2)
```

```{r}
SDMissModel <- lmer(data = datasetSDSumm, formula = Miss ~ Condition +Block + (1|ID))
summary(SDMissModel)
```


```{r}
SDFAModel <- lmer(data = datasetSDSumm, formula = FA ~ Block + Condition + (1|ID))
SDFAModel2 <- lmer(data = datasetSDSumm, formula = FA ~ Block * Condition + (1|ID))
anova(SDFAModel2, SDFAModel)
summary(SDFAModel)
summary(SDFAModel2)
```



```{r}
SDFAresults <- report(SDFAModel2, CI = 95)

print(SDFAresults)
```





