---
title: "Study2Validation"
output: html_document
date: '2022-07-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readr)
library(stringr)
library(plyr)
library(splitstackshape)

```


```{r}
### Read in the Data Files ###

#set the working directory to the data folder
setwd("D:/Python Scripts/")

#Define the filepath for where the data is coming from
dataFolder <- "D:/Road Footage/PavloviaData/data"

#Create a list of all the datafiles in the folder, and then convert to a list object - needs full names for the file path
file_list <- list.files(path = dataFolder, pattern = ".csv$", all.files = TRUE, full.names = TRUE, recursive = TRUE)

```

```{r}
#Loop through the files and create one large dataset
datasetRaw <- data.frame()

for (i in 1:length(file_list)){
  temp_data <- assign(paste(substr(file_list[i],26,29)),  
              read.csv(paste0(file_list[i])))
  temp_data <- data.frame(temp_data[-c(1,3,4,5,6,7,13:26)])
  
  datasetRaw <- rbind.fill(datasetRaw, temp_data) %>% 
    mutate(idx = as.integer(factor(participant))) 
}
```

```{r}
  #clean up dataset to only include hazard response data and reorganise
  datasetHazard <- datasetRaw %>% 
    select(idx, video_file, hazard_resp.rt) 
   datasetHazard$video_file <- gsub('.{4}$', '', datasetHazard$video_file)
   datasetHazard <- datasetHazard[-which(datasetHazard$hazard_resp.rt == ""), ]
             

```


```{r}
#Split the column with all responses into multiple columns per participants
datasetHazard <- cSplit(datasetHazard, "hazard_resp.rt", sep=",")
#splitstackshape

```

