---
title: "EmilyANOVA2"
author: "TGoodge"
date: '2023-08-23'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(rstatix)
library(afex)
library(lme4)
library(lmerTest)
library(emmeans)
library(ggpubr)


```

```{r}
rawData <- read.csv("C:/Users/thoma/Downloads/final_df_ppt.csv")

```

```{r}
rawData$Extraversion <- rawData$Extraversion_Condition 

NoFiller <- rawData %>% 
  subset(Filler == "no filler")

Extraversion <- rawData %>% 
  subset(Extraversion != "no filler: male") %>% 
  subset(Extraversion != "no filler: female")

Extraversion$Extraversion<- substr(Extraversion$Extraversion, 1, 4)

```


```{r}

#Plot a very basic histogram of all the data
ggplot(rawData, aes(x = Competence_Q ))+
 geom_histogram(binwidth = 1)
```




```{r}

#check for outliers in the main dataset
outlier<-Extraversion %>% 
group_by(Extraversion) %>%
identify_outliers(Competence_Q)
data.frame(outlier)
```



```{r}

#Plot a very basic histogram of all the data
ggplot(rawData, aes(x = Discomfort_Q ))+
 geom_histogram(binwidth = 1)
```

```{r}

#Plot a very basic histogram of all the data
ggplot(rawData, aes(x = Warmth_Q ))+
 geom_histogram(binwidth = 1)
```
```{r}
ggplot(rawData, aes(x=Extraversion_Condition, y=Competence_Q)) + 
  geom_boxplot(outlier.shape = NA) 
```

```{r}

SexSum <- Extraversion %>% 
  group_by(Sex) %>% 
  summarise(n = n(),
            mean = mean(Warmth_Q),
            sd = sd(Warmth_Q))
```



```{r}

bartlett.test(Competence_Q ~ Sex, data = Extraversion)
# 
 summary(aov(Competence_Q ~ Sex, data = Extraversion))
# 
# 
# summary(aov(Discomfort_Q ~ Sex, data = Extraversion))
# 
# 
# summary(aov(Warmth_Q ~ Sex, data = Extraversion))

oneway.test(Competence_Q ~ Sex, data = Extraversion, var.equal = FALSE)

```
```{r}

summary(aov(Competence_Q ~ Pitch_Category, data = Extraversion))


summary(aov(Discomfort_Q ~ Pitch_Category, data = Extraversion))


summary(aov(Warmth_Q ~  Pitch_Category,data = Extraversion))

```


```{r}

PitchComp <- Extraversion %>% 
  group_by(Pitch_Category) %>% 
  summarise(n = n(),
            mean = mean(Competence_Q),
            sd = sd(Competence_Q))

PitchWarm <- Extraversion %>% 
  group_by(Pitch_Category) %>% 
  summarise(n = n(),
            mean = mean(Warmth_Q),
            sd = sd(Warmth_Q))

```

```{r}


summary(aov(Competence_Q ~ Extraversion, data = Extraversion))


summary(aov(Discomfort_Q ~ Extraversion, data = Extraversion))


summary(aov(Warmth_Q ~ Extraversion, data = Extraversion))

```
```{r}

# Full 2x2x2 within subjects ANOVA
summary(aov(Competence_Q ~ Pitch_Category * Sex * Extraversion, data = Extraversion))


summary(aov(Discomfort_Q ~ Pitch_Category * Sex * Extraversion, data = Extraversion))


summary(aov(Warmth_Q ~ Pitch_Category * Sex * Extraversion, data = Extraversion))
```

```{r}


summary(aov(Competence_Q ~ Sex, data = NoFiller))


summary(aov(Discomfort_Q ~ Sex, data = NoFiller))


summary(aov(Warmth_Q ~ Sex, data = NoFiller))

```
```{r}

summary(aov(Competence_Q ~ Pitch_Category  , data = NoFiller))


summary(aov(Discomfort_Q ~ Pitch_Category  , data = NoFiller))


summary(aov(Warmth_Q ~ Pitch_Category , data = NoFiller))
```


```{r}



summary(aov(Competence_Q ~ Pitch_Category * Sex , data = NoFiller))


summary(aov(Discomfort_Q ~ Pitch_Category * Sex , data = NoFiller))


summary(aov(Warmth_Q ~ Pitch_Category * Sex , data = NoFiller))
```

```{r}
CompModelSex <- lmer(data = Extraversion, formula = Competence_Q ~ Sex + (1 |Ppt.) + (1|Audiofile), REML = F)

CompModelPitch <- lmer(data = Extraversion, formula = Competence_Q ~ Pitch_Category + (1 |Ppt.) + (1|Audiofile), REML = F)

CompModelExtr <- lmer(data = Extraversion, formula = Competence_Q ~ Extraversion + (1 |Ppt.) + (1|Audiofile), REML = F)



#######################

CompModelSexPitch <- lmer(data = Extraversion, formula = Competence_Q ~ Sex * Pitch_Category + (1 |Ppt.) + (1|Audiofile), REML = F)

CompModelPitchExtr <- lmer(data = Extraversion, formula = Competence_Q ~ Extraversion * Pitch_Category + (1 |Ppt.) + (1|Audiofile), REML = F)

CompModelSexExtr <- lmer(data = Extraversion, formula = Competence_Q ~ Extraversion * Sex + (1 |Ppt.) + (1|Audiofile), REML = F)

#####################


CompModelSexPitchExtr <- lmer(data = Extraversion, formula = Competence_Q ~ Sex * Extraversion* Pitch_Category + (1 |Ppt.) + (1|Audiofile), REML = F)

###################
anova(CompModelSex, CompModelSexPitch,CompModelSexExtr,CompModelSexPitchExtr)

#summary(CompModelBasic)

library(report)

WHNresults <- report(CompModelSexPitchExtr, CI = 95)

summary(WHNresults)
```

