---
title: "Emilanalysis"
author: "TGoodge"
date: '2023-03-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning = FALSE, message = FALSE}
library(readxl)
library(tidyverse)
library(dplyr)
library(rstatix)
library(afex)
library(lme4)
library(emmeans)
library(ggpubr)


```

```{r}
#Bring in Data file
rawData <- read.csv("C:/Users/thoma/Documents/anovadf1.csv")
maleData <-  read.csv("C:/Users/thoma/Documents/male_anova_df.csv")
femaleData <-  read.csv("C:/Users/thoma/Documents/fem_anova_df.csv")

#Rename DUration column
colnames(rawData)[colnames(rawData) == 'Duration_.ms.'] <- 'Duration'


#Remove long strings from ID (Still retains all 144 ppts)
rawData$ID <- substr(rawData$ID, 1, 6)  

#Convert relevent columns to factors for ANOVA
rawData$Duration <- as.factor(rawData$Duration)
rawData$Type <- as.factor(rawData$Type)
rawData$ID <- as.factor(rawData$ID)
rawData$File <- as.factor(rawData$File)

rawData$X <- as.factor(rawData$X)

#show the levels in the ID factor (Used for debugging)
#levels(rawData$ID)

```


```{r}
#Plot a very basic histogram of all the data
ggplot(rawData, aes(x = Rating ))+
 geom_histogram(binwidth = 1)
```
```{r}
#Boxplot of the data for both within and between conditions
ggplot(rawData, aes(x=Duration, y=Rating, fill=Type)) + 
  geom_boxplot(outlier.shape = NA) 
```


```{r}
#Split the data set into 3 based on each Dimensions
AttrData <- rawData[rawData$Dimension == 'Attractiveness',]

DomData <- rawData[rawData$Dimension == 'Dominance',]

TrustData <- rawData[rawData$Dimension == 'Trustworthiness',]

```

```{r}
#Summarise the means and SD ratings for each of the 3 dimensions
AttrSum <- AttrData %>% 
  group_by(Duration, Type) %>% 
  summarise(n = n(),
            mean = mean(Rating),
            sd = sd(Rating))

DomSum <- DomData %>% 
  group_by(Duration, Type) %>% 
  summarise(n = n(),
            mean = mean(Rating),
            sd = sd(Rating))


TrustSum <- TrustData %>% 
  group_by(Duration, Type) %>% 
  summarise(n = n(),
            mean = mean(Rating),
            sd = sd(Rating))
```

```{r}
#plot the spread of the data for each fo the dimensions
ggplot(AttrData, aes(x = Duration, y = Rating, fill = Type ))+
  geom_violin()+
  geom_boxplot()+
  labs(title = "Attractiveness")

ggplot(DomData, aes(x = Duration, y = Rating, fill = Type ))+
  geom_violin()+
  geom_boxplot()+
  labs(title = "Dominance")

ggplot(TrustData, aes(x = Duration, y = Rating, fill = Type ))+
  geom_violin()+
  geom_boxplot()+
  labs(title = "Trustworthiness")

```

```{r}
#check for outliers in the main dataset
outlier<-rawData %>% 
group_by(Duration,Type) %>%
identify_outliers(Rating)
data.frame(outlier)
```



```{r}

#plot a quantile-quantile plot to compare distributions
#sigmoidal shape because ratings are between 0 and 100
ggqqplot(rawData, "Rating", ggtheme = theme_bw()) +
  facet_grid(Type ~ Duration)


#qqplot(rawData$Type, rawData$Rating, xlab = "test x", ylab = "test y", main = "Q-Q Plot")

```
```{r}
#Test assumptions of big data set - not sure if they meet them
rawData %>% 
  group_by(Duration) %>% 
  levene_test(Rating ~ Type)

box_m(rawData[, "Rating", drop = FALSE], rawData$Duration)


```
```{r}
#FIrst attempt at mixed ANOVA but produces an error due to number of factors
#resATTR <- anova_test(data = AttrData, dv = Rating, between = Duration, within = Type, wid = X)
#get_anova_table(res)
```

```{r}

#Conduct mixed ANOVA for each of the dimensions(next 3 chunks) from the afex package
mixed_anova_Attr <- aov_ez(
  id = "ID",
  dv = "Rating",
  data = AttrData,
  between = "Duration",
  within = "Type"
)

summary(mixed_anova_Attr)
knitr::kable(nice(mixed_anova_Attr))


```


```{r}
mixed_anova_Dom <- aov_ez(
  id = "ID",
  dv = "Rating",
  data = DomData,
  between = "Duration",
  within = "Type",
  anova_table = list(p_adjust_method = "holm")
)


summary(mixed_anova_Dom)
knitr::kable(nice(mixed_anova_Dom))
```


```{r}
mixed_anova_Trust<- aov_ez(
  id = "ID",
  dv = "Rating",
  data = TrustData,
  between = "Duration",
  within = "Type",
  anova_table = list(p_adjust_method = "holm")
)


summary(mixed_anova_Trust)

pairwise.t.test(TrustData$Rating, TrustData$Type, p.adjust.method="bonferroni")


knitr::kable(nice(mixed_anova_Trust))
```

```{r}
#Test sphericity for each of the dimensions

test_sphericity(mixed_anova_Attr)

test_sphericity(mixed_anova_Dom)

test_sphericity(mixed_anova_Trust)

```

```{r}
#Produce horrific plots for each of the dimensions
afex_plot(mixed_anova_Attr, x = "Type", trace = "Duration")
afex_plot(mixed_anova_Dom, x = "Type", trace = "Duration")
afex_plot(mixed_anova_Trust, x = "Type", trace = "Duration")
```

```{r}
#Different method for Mixed ANOVA
Mixed.aov.Attr<-aov_car(Rating ~ Duration*Type + Error(ID/Type), data=AttrData)

summary(Mixed.aov.Attr)
```

```{r}

Mixed_Fitted_Type_Attr<-emmeans(Mixed.aov.Attr, ~Type)
Mixed_Fitted_Type_Attr

Mixed_Fitted_Duration_Attr<-emmeans(Mixed.aov.Attr, ~Duration)
Mixed_Fitted_Duration_Attr

Mixed_Fitted_Interaction_Attr<-emmeans(Mixed.aov.Attr, specs = pairwise ~Type*Duration, type = "response", adjust = "holm")
Mixed_Fitted_Interaction_Attr


knitr::kable((Mixed_Fitted_Interaction_Attr$emmeans))
knitr::kable((Mixed_Fitted_Interaction_Attr$contrast))

```
```{r}
pairs(Mixed_Fitted_Interaction_Attr)
knitr::kable((pairs(Mixed_Fitted_Interaction_Attr)))
```

```{r}
ggplot(AttrData, aes(x = Duration, y = Rating, fill = Type ))+
  geom_boxplot()+
  labs(title = "Attractiveness")
```

```{r}
#Different method for Mixed ANOVA
Mixed.aov.Dom<-aov_car(Rating ~ Duration*Type + Error(ID/Type), data=DomData)

summary(Mixed.aov.Dom)
```

```{r}

Mixed_Fitted_Type_Dom<-emmeans(Mixed.aov.Dom,  ~Type)
Mixed_Fitted_Type_Dom


Mixed_Fitted_Duration_Dom<-emmeans(Mixed.aov.Dom, ~Duration)
Mixed_Fitted_Duration_Dom

Mixed_Fitted_Interaction_Dom<-emmeans(Mixed.aov.Dom, specs = pairwise ~Type*Duration, type = "response", adjust = "holm")
Mixed_Fitted_Interaction_Dom


knitr::kable((Mixed_Fitted_Interaction_Dom$emmeans))
knitr::kable((Mixed_Fitted_Interaction_Dom$contrast))


```

```{r}
pairs(Mixed_Fitted_Interaction_Dom)
knitr::kable((pairs(Mixed_Fitted_Interaction_Dom)))
```


```{r}

pairs2 <- emmeans(Mixed.aov.Dom, pairwise ~Type|Duration)
pairs2

```

```{r}
ggplot(DomData, aes(x = Duration, y = Rating, fill = Type ))+
  geom_boxplot()+
  labs(title = "Dominance")
```

```{r}
#Different method for Mixed ANOVA
Mixed.aov.Trust<-aov_car(Rating ~ Duration*Type + Error(ID/Type), data=TrustData)

summary(Mixed.aov.Trust)
```

```{r}

Mixed_Fitted_Type_Trust<-emmeans(Mixed.aov.Trust, ~Type)
Mixed_Fitted_Type_Trust

Mixed_Fitted_Duration_Trust<-emmeans(Mixed.aov.Trust, ~Duration)
Mixed_Fitted_Duration_Trust

Mixed_Fitted_Interaction_Trust<-emmeans(Mixed.aov.Trust, specs = pairwise ~Type*Duration, type = "response", adjust = "holm")
Mixed_Fitted_Interaction_Trust

knitr::kable((Mixed_Fitted_Interaction_Trust$emmeans))
knitr::kable((Mixed_Fitted_Interaction_Trust$contrast))

```

```{r}

pairs(Mixed_Fitted_Interaction_Trust)
knitr::kable(pairs(Mixed_Fitted_Interaction_Trust))


```

```{r}
ggplot(TrustData, aes(x = Duration, y = Rating, fill = Type ))+
  geom_boxplot()+
  labs(title = "Trustworthiness")
```



```{r}
#Code for mixed effets models
NullModelAttr <- lmer(data = AttrData, formula = Rating ~ (1|ID))
summary(NullModelAttr)

```

```{r}
Model1Attr = lmer(data = AttrData, formula = Rating ~ Duration * Type + (1|ID))

summary(Model1Attr)
```


```{r}
maleData <-  read.csv("C:/Users/thoma/Documents/male_anova_df.csv")



#Rename DUration column
colnames(maleData)[colnames(maleData) == 'Duration_.ms.'] <- 'Duration'


#Remove long strings from ID (Still retains all 144 ppts)
maleData$ID <- substr(maleData$ID, 1, 6)  

#Convert relevent columns to factors for ANOVA
maleData$Duration <- as.factor(maleData$Duration)
maleData$Type <- as.factor(maleData$Type)
maleData$ID <- as.factor(maleData$ID)
#maleData$File <- as.factor(maleData$File)

maleData$X <- as.factor(maleData$X)

#show the levels in the ID factor (Used for debugging)
#levels(maleData$ID)

```


```{r}
femaleData <-  read.csv("C:/Users/thoma/Documents/fem_anova_df.csv")

```

